//! Custom primitive shader declarations, including raster and multipass kernels.
pub struct CustomAbiCase {
    pub source: &'static str,
    pub rust_struct: &'static str,
    pub shader: &'static str,
    pub shader_struct: &'static str,
    pub aliases: &'static [(&'static str, &'static str)],
}

/// Both cut-map primitives dispatch the same custom `CutMapUniforms` ABI.
pub const CUT_MAP_TYPE_IDS: &[&str] = &["node.cut_mesh_bands", "node.cut_mesh_cells"];

pub const CASES: &[CustomAbiCase] = &[
    CustomAbiCase {
        source: "liquid_stats.rs",
        rust_struct: "StatsParams",
        shader: "shaders/liquid_stats.wgsl",
        shader_struct: "StatsParams",
        aliases: &[],
    },
    CustomAbiCase {
        source: "../liquid/grid.rs",
        rust_struct: "FaceParams",
        shader: "shaders/liquid_frame_faces.wgsl",
        shader_struct: "FaceParams",
        aliases: &[],
    },
    CustomAbiCase {
        source: "matter_stats.rs",
        rust_struct: "StatsParams",
        shader: "shaders/matter_stats.wgsl",
        shader_struct: "StatsParams",
        aliases: &[],
    },
    CustomAbiCase {
        source: "matter_to_grid.rs",
        rust_struct: "P2gParams",
        shader: "shaders/matter_to_grid.wgsl",
        shader_struct: "P2gParams",
        aliases: &[],
    },
    CustomAbiCase {
        source: "../liquid/body_buffers.rs",
        rust_struct: "UploadParams",
        shader: "shaders/liquid_body_upload.wgsl",
        shader_struct: "UploadParams",
        aliases: &[],
    },
    CustomAbiCase {
        source: "matter_frame.rs",
        rust_struct: "FrameParams",
        shader: "shaders/matter_frame.wgsl",
        shader_struct: "FrameParams",
        aliases: &[],
    },
    CustomAbiCase {
        source: "volume_optics.rs",
        rust_struct: "Uniforms",
        shader: "shaders/volume_optics.wgsl",
        shader_struct: "Uniforms",
        aliases: &[],
    },
    CustomAbiCase {
        source: "../instance_upload.rs",
        rust_struct: "UploadParams",
        shader: "shaders/physics_instance_upload.wgsl",
        shader_struct: "UploadParams",
        aliases: &[],
    },
    CustomAbiCase {
        source: "bokeh_gather.rs",
        rust_struct: "BokehRadiusUniforms",
        shader: "shaders/bokeh_tile_dilate.wgsl",
        shader_struct: "Uniforms",
        aliases: &[],
    },
    CustomAbiCase {
        source: "bokeh_gather.rs",
        rust_struct: "BokehCompositeUniforms",
        shader: "shaders/bokeh_reconstruct.wgsl",
        shader_struct: "Uniforms",
        aliases: &[],
    },
    CustomAbiCase {
        source: "bokeh_gather.rs",
        rust_struct: "BokehCompositeUniforms",
        shader: "shaders/bokeh_prefilter.wgsl",
        shader_struct: "Uniforms",
        aliases: &[],
    },
    CustomAbiCase {
        source: "filter.rs",
        rust_struct: "DualBlurUniforms",
        shader: "shaders/blur_dual.wgsl",
        shader_struct: "Uniforms",
        aliases: &[],
    },
    CustomAbiCase {
        source: "platonic_mesh.rs",
        rust_struct: "UploadUniforms",
        shader: "shaders/platonic_mesh_upload.wgsl",
        shader_struct: "Uniforms",
        aliases: &[],
    },
    CustomAbiCase {
        source: "mesh_cut_map.rs",
        rust_struct: "CutMapUniforms",
        shader: "shaders/mesh_cut_map.wgsl",
        shader_struct: "Params",
        aliases: &[],
    },
    CustomAbiCase {
        source: "render_mesh_diagram.rs",
        rust_struct: "DiagramUniforms",
        shader: "shaders/render_mesh_diagram.wgsl",
        shader_struct: "U",
        aliases: &[],
    },
    CustomAbiCase {
        source: "render_mesh_diagram.rs",
        rust_struct: "HistoryCaptureUniforms",
        shader: "shaders/history_capture.wgsl",
        shader_struct: "Capture",
        aliases: &[],
    },
    CustomAbiCase {
        source: "cylinder_wrap_field.rs",
        rust_struct: "Uniforms",
        shader: "shaders/cylinder_wrap_field.wgsl",
        shader_struct: "Uniforms",
        aliases: &[],
    },
    CustomAbiCase {
        source: "torus_wrap_field.rs",
        rust_struct: "Uniforms",
        shader: "shaders/torus_wrap_field.wgsl",
        shader_struct: "Uniforms",
        aliases: &[],
    },
    CustomAbiCase {
        source: "remove_drift_3d.rs",
        rust_struct: "RemoveDriftUniforms",
        shader: "shaders/remove_drift_3d.wgsl",
        shader_struct: "Uniforms",
        aliases: &[],
    },
    CustomAbiCase {
        source: "scatter_on_mesh.rs",
        rust_struct: "ScatterOnMeshUniforms",
        shader: "shaders/scatter_on_mesh.wgsl",
        shader_struct: "Params",
        aliases: &[],
    },
    CustomAbiCase {
        source: "seed_particles.rs",
        rust_struct: "SeedUniforms",
        shader: "shaders/seed_particles.wgsl",
        shader_struct: "SeedUniforms",
        aliases: &[],
    },
    CustomAbiCase {
        source: "seed_particles_from_texture.rs",
        rust_struct: "SeedFromTextureUniforms",
        shader: "shaders/seed_particles_from_texture.wgsl",
        shader_struct: "Params",
        aliases: &[],
    },
    CustomAbiCase {
        source: "spawn_from_mesh.rs",
        rust_struct: "SpawnFromMeshUniforms",
        shader: "shaders/spawn_from_mesh.wgsl",
        shader_struct: "Params",
        aliases: &[],
    },
    CustomAbiCase {
        source: "sort_particles_into_cells.rs",
        rust_struct: "SortParams",
        shader: "shaders/sort_particles_into_cells.wgsl",
        shader_struct: "SortParams",
        aliases: &[],
    },
    CustomAbiCase {
        source: "prefix_scan.rs",
        rust_struct: "ScanParams",
        shader: "shaders/prefix_scan.wgsl",
        shader_struct: "ScanParams",
        aliases: &[],
    },
    CustomAbiCase {
        source: "dot_products.rs",
        rust_struct: "DotParams",
        shader: "shaders/dot_products.wgsl",
        shader_struct: "Params",
        aliases: &[],
    },
    CustomAbiCase {
        source: "gpu_flip_pressure.rs",
        rust_struct: "Params",
        shader: "shaders/gpu_flip_pressure.wgsl",
        shader_struct: "Params",
        aliases: &[],
    },
    CustomAbiCase {
        source: "gpu_flip_step.rs",
        rust_struct: "StepParams",
        shader: "shaders/gpu_flip_step.wgsl",
        shader_struct: "Params",
        aliases: &[],
    },
    CustomAbiCase {
        source: "whitewater_step.rs",
        rust_struct: "HandParams",
        shader: "shaders/whitewater_step.wgsl",
        shader_struct: "StepParams",
        aliases: &[],
    },
    CustomAbiCase {
        source: "gpu_flip_pressure.rs",
        rust_struct: "InverseParams",
        shader: "shaders/coarse_inverse.wgsl",
        shader_struct: "Params",
        aliases: &[],
    },
    CustomAbiCase {
        source: "gpu_flip_bodies.rs",
        rust_struct: "Params",
        shader: "shaders/gpu_flip_bodies.wgsl",
        shader_struct: "Params",
        aliases: &[],
    },
    CustomAbiCase {
        source: "running_total.rs",
        rust_struct: "TotalParams",
        shader: "shaders/running_total.wgsl",
        shader_struct: "TotalParams",
        aliases: &[],
    },
    CustomAbiCase {
        source: "live_draw_args.rs",
        rust_struct: "LiveArgs",
        shader: "shaders/live_draw_args.wgsl",
        shader_struct: "LiveArgs",
        aliases: &[],
    },
    CustomAbiCase {
        source: "blob_detect_ffi.rs",
        rust_struct: "UploadUniforms",
        shader: "shaders/blob_detect_ffi_upload.wgsl",
        shader_struct: "Uniforms",
        aliases: &[],
    },
    CustomAbiCase {
        source: "blob_detect_ffi.rs",
        rust_struct: "BlobRect",
        shader: "shaders/blob_detect_ffi_upload.wgsl",
        shader_struct: "Blob",
        aliases: &[],
    },
    CustomAbiCase {
        source: "affine_transform.rs",
        rust_struct: "AffineTransformUniforms",
        shader: "shaders/affine_transform.wgsl",
        shader_struct: "Uniforms",
        aliases: &[],
    },
    CustomAbiCase {
        source: "filter.rs",
        rust_struct: "ThresholdUniforms",
        shader: "shaders/threshold.wgsl",
        shader_struct: "Uniforms",
        aliases: &[],
    },
    CustomAbiCase {
        source: "filter.rs",
        rust_struct: "BlurUniforms",
        shader: "shaders/blur.wgsl",
        shader_struct: "Uniforms",
        aliases: &[],
    },
    CustomAbiCase {
        source: "lambert_directional.rs",
        rust_struct: "LambertUniforms",
        shader: "shaders/lambert_directional.wgsl",
        shader_struct: "Uniforms",
        aliases: &[
            ("light_x", "light_dir[0]"),
            ("light_y", "light_dir[1]"),
            ("light_z", "light_dir[2]"),
            ("_vec3_pad", "_pad"),
            ("light_color_r", "light_color[0]"),
            ("light_color_g", "light_color[1]"),
            ("light_color_b", "light_color[2]"),
        ],
    },
    CustomAbiCase {
        source: "color_sample.rs",
        rust_struct: "UvUniform",
        shader: "shaders/color_sample.wgsl",
        shader_struct: "UvParam",
        aliases: &[],
    },
    CustomAbiCase {
        source: "bake_equirect_envmap.rs",
        rust_struct: "EnvmapUniforms",
        shader: "shaders/bake_equirect_envmap.wgsl",
        shader_struct: "Uniforms",
        aliases: &[],
    },
    CustomAbiCase {
        source: "digital_plants_render.rs",
        rust_struct: "RenderUniforms",
        shader: "../../generators/shaders/digital_plants_render.wgsl",
        shader_struct: "Uniforms",
        aliases: &[],
    },
    CustomAbiCase {
        source: "digital_plants_render.rs",
        rust_struct: "ShadowUniforms",
        shader: "../../generators/shaders/digital_plants_shadow.wgsl",
        shader_struct: "ShadowUniforms",
        aliases: &[],
    },
    CustomAbiCase {
        source: "gltf_texture_source.rs",
        rust_struct: "GltfTextureBlitUniforms",
        shader: "shaders/gltf_texture_blit.wgsl",
        shader_struct: "Uniforms",
        aliases: &[],
    },
    CustomAbiCase {
        source: "hdri_source.rs",
        rust_struct: "HdriBlitUniforms",
        shader: "shaders/hdri_source_blit.wgsl",
        shader_struct: "Uniforms",
        aliases: &[],
    },
    CustomAbiCase {
        source: "layer_source.rs",
        rust_struct: "LayerSourceBlitUniforms",
        shader: "shaders/layer_source_blit.wgsl",
        shader_struct: "Uniforms",
        aliases: &[],
    },
    CustomAbiCase {
        source: "image_folder.rs",
        rust_struct: "ImageFolderUniforms",
        shader: "shaders/image_folder.wgsl",
        shader_struct: "Uniforms",
        aliases: &[],
    },
    CustomAbiCase {
        source: "nested_cubes_geometry.rs",
        rust_struct: "NestedCubesUniforms",
        shader: "shaders/nested_cubes_geometry.wgsl",
        shader_struct: "Uniforms",
        aliases: &[],
    },
    CustomAbiCase {
        source: "render_3d_mesh.rs",
        rust_struct: "GBufferUniforms",
        shader: "shaders/render_3d_mesh.wgsl",
        shader_struct: "Uniforms",
        aliases: &[],
    },
    CustomAbiCase {
        source: "render_lines.rs",
        rust_struct: "LineRenderUniforms",
        shader: "shaders/render_lines.wgsl",
        shader_struct: "LineUniforms",
        aliases: &[],
    },
    CustomAbiCase {
        source: "render_scene.rs",
        rust_struct: "RenderSceneUniforms",
        shader: "shaders/render_scene.wgsl",
        shader_struct: "Uniforms",
        aliases: &[],
    },
    CustomAbiCase {
        source: "render_scene.rs",
        rust_struct: "MaterialMapUniform",
        shader: "shaders/render_scene.wgsl",
        shader_struct: "MaterialMapUniform",
        aliases: &[],
    },
    CustomAbiCase {
        source: "render_scene.rs",
        rust_struct: "PrefilterUniforms",
        shader: "shaders/ibl_prefilter_specular.wgsl",
        shader_struct: "PrefilterUniforms",
        aliases: &[],
    },
    CustomAbiCase {
        source: "render_scene.rs",
        rust_struct: "IrradianceUniforms",
        shader: "shaders/ibl_irradiance.wgsl",
        shader_struct: "IrradianceUniforms",
        aliases: &[],
    },
    CustomAbiCase {
        source: "render_scene.rs",
        rust_struct: "LutUniforms",
        shader: "shaders/ibl_brdf_lut.wgsl",
        shader_struct: "LutUniforms",
        aliases: &[],
    },
    CustomAbiCase {
        source: "render_scene.rs",
        rust_struct: "ShadowUniforms",
        shader: "shaders/shadow_depth.wgsl",
        shader_struct: "ShadowUniforms",
        aliases: &[],
    },
    CustomAbiCase {
        source: "render_scene.rs",
        rust_struct: "ShaftMarchUniforms",
        shader: "shaders/shaft_march.wgsl",
        shader_struct: "Uniforms",
        aliases: &[],
    },
    CustomAbiCase {
        source: "render_scene.rs",
        rust_struct: "ShaftCompositeUniforms",
        shader: "shaders/shaft_composite.wgsl",
        shader_struct: "Uniforms",
        aliases: &[],
    },
    CustomAbiCase {
        source: "render_text.rs",
        rust_struct: "RenderTextUniforms",
        shader: "shaders/render_text.wgsl",
        shader_struct: "Uniforms",
        aliases: &[],
    },
    CustomAbiCase {
        source: "watercolor.rs",
        rust_struct: "WatercolorUniforms",
        shader: "../../effects/shaders/fx_watercolor_compute.wgsl",
        shader_struct: "Uniforms",
        aliases: &[],
    },
    // The GPU water surface's barriered kernels and the whitewater stage's
    // internal padding pass.
    CustomAbiCase {
        source: "lattice_bricks.rs",
        rust_struct: "BrickUniforms",
        shader: "shaders/lattice_bricks.wgsl",
        shader_struct: "Params",
        aliases: &[],
    },
    CustomAbiCase {
        source: "blob_bounds.rs",
        rust_struct: "BoundsParams",
        shader: "shaders/blob_bounds.wgsl",
        shader_struct: "Params",
        aliases: &[],
    },
    CustomAbiCase {
        source: "pad_distance_lattice.rs",
        rust_struct: "PadUniforms",
        shader: "shaders/pad_distance_lattice.wgsl",
        shader_struct: "Params",
        aliases: &[],
    },
    // GPU FLIP's live clock, narrow band and Lentine coarse solve, with the
    // records their value proofs upload.
    CustomAbiCase {
        source: "gpu_flip_clock.rs",
        rust_struct: "GpuFlipClockParams",
        shader: "shaders/gpu_flip_clock.wgsl",
        shader_struct: "ClockParams",
        aliases: &[],
    },
    CustomAbiCase {
        source: "gpu_flip_clock.rs",
        rust_struct: "GpuFlipBodyVertex",
        shader: "shaders/gpu_flip_clock.wgsl",
        shader_struct: "BodyVertex",
        aliases: &[],
    },
    CustomAbiCase {
        source: "gpu_flip_clock.rs",
        rust_struct: "EventFieldParams",
        shader: "shaders/gpu_flip_clock.wgsl",
        shader_struct: "EventFieldParams",
        aliases: &[],
    },
    CustomAbiCase {
        source: "gpu_flip_narrow_band.rs",
        rust_struct: "NbParams",
        shader: "shaders/gpu_flip_narrow_band.wgsl",
        shader_struct: "NbParams",
        aliases: &[],
    },
    CustomAbiCase {
        source: "gpu_flip_narrow_band_tests.rs",
        rust_struct: "NbFace",
        shader: "shaders/gpu_flip_narrow_band.wgsl",
        shader_struct: "NbFace",
        aliases: &[],
    },
    CustomAbiCase {
        source: "gpu_flip_narrow_band_tests.rs",
        rust_struct: "NbParticle",
        shader: "shaders/gpu_flip_narrow_band.wgsl",
        shader_struct: "NbParticle",
        aliases: &[],
    },
    CustomAbiCase {
        source: "gpu_flip_narrow_band_tests.rs",
        rust_struct: "NbRange",
        shader: "shaders/gpu_flip_narrow_band.wgsl",
        shader_struct: "NbRange",
        aliases: &[],
    },
    CustomAbiCase {
        source: "gpu_flip_lentine.rs",
        rust_struct: "Params",
        shader: "shaders/gpu_flip_lentine.wgsl",
        shader_struct: "Params",
        aliases: &[],
    },
    CustomAbiCase {
        source: "gpu_flip_pressure_tests.rs",
        rust_struct: "LentineFluxParams",
        shader: "shaders/gpu_flip_pressure.wgsl",
        shader_struct: "Params",
        aliases: &[],
    },
];
