//! Custom primitive shader declarations, including raster and multipass kernels.
pub struct CustomAbiCase {
    pub source: &'static str,
    pub rust_struct: &'static str,
    pub shader: &'static str,
    pub shader_struct: &'static str,
    pub aliases: &'static [(&'static str, &'static str)],
}
pub const CASES: &[CustomAbiCase] = &[
    CustomAbiCase {
        source: "cylinder_wrap_field.rs",
        rust_struct: "Uniforms",
        shader: "shaders/cylinder_wrap_field.wgsl",
        shader_struct: "Uniforms",
        aliases: &[],
    },
    CustomAbiCase {
        source: "torus_wrap_field.rs",
        rust_struct: "Uniforms",
        shader: "shaders/torus_wrap_field.wgsl",
        shader_struct: "Uniforms",
        aliases: &[],
    },
    CustomAbiCase {
        source: "remove_drift_3d.rs",
        rust_struct: "RemoveDriftUniforms",
        shader: "shaders/remove_drift_3d.wgsl",
        shader_struct: "Uniforms",
        aliases: &[],
    },
    CustomAbiCase {
        source: "scatter_on_mesh.rs",
        rust_struct: "ScatterOnMeshUniforms",
        shader: "shaders/scatter_on_mesh.wgsl",
        shader_struct: "Params",
        aliases: &[],
    },
    CustomAbiCase {
        source: "seed_particles.rs",
        rust_struct: "SeedUniforms",
        shader: "shaders/seed_particles.wgsl",
        shader_struct: "SeedUniforms",
        aliases: &[],
    },
    CustomAbiCase {
        source: "seed_particles_from_texture.rs",
        rust_struct: "SeedFromTextureUniforms",
        shader: "shaders/seed_particles_from_texture.wgsl",
        shader_struct: "Params",
        aliases: &[],
    },
    CustomAbiCase {
        source: "spawn_from_mesh.rs",
        rust_struct: "SpawnFromMeshUniforms",
        shader: "shaders/spawn_from_mesh.wgsl",
        shader_struct: "Params",
        aliases: &[],
    },
    CustomAbiCase {
        source: "blob_detect_ffi.rs",
        rust_struct: "UploadUniforms",
        shader: "shaders/blob_detect_ffi_upload.wgsl",
        shader_struct: "Uniforms",
        aliases: &[],
    },
    CustomAbiCase {
        source: "blob_detect_ffi.rs",
        rust_struct: "BlobRect",
        shader: "shaders/blob_detect_ffi_upload.wgsl",
        shader_struct: "Blob",
        aliases: &[],
    },
    CustomAbiCase {
        source: "affine_transform.rs",
        rust_struct: "AffineTransformUniforms",
        shader: "shaders/affine_transform.wgsl",
        shader_struct: "Uniforms",
        aliases: &[],
    },
    CustomAbiCase {
        source: "filter.rs",
        rust_struct: "ThresholdUniforms",
        shader: "shaders/threshold.wgsl",
        shader_struct: "Uniforms",
        aliases: &[],
    },
    CustomAbiCase {
        source: "filter.rs",
        rust_struct: "BlurUniforms",
        shader: "shaders/blur.wgsl",
        shader_struct: "Uniforms",
        aliases: &[],
    },
    CustomAbiCase {
        source: "lambert_directional.rs",
        rust_struct: "LambertUniforms",
        shader: "shaders/lambert_directional.wgsl",
        shader_struct: "Uniforms",
        aliases: &[
            ("light_x", "light_dir[0]"),
            ("light_y", "light_dir[1]"),
            ("light_z", "light_dir[2]"),
            ("_vec3_pad", "_pad"),
            ("light_color_r", "light_color[0]"),
            ("light_color_g", "light_color[1]"),
            ("light_color_b", "light_color[2]"),
        ],
    },
    CustomAbiCase {
        source: "color_sample.rs",
        rust_struct: "UvUniform",
        shader: "shaders/color_sample.wgsl",
        shader_struct: "UvParam",
        aliases: &[],
    },
    CustomAbiCase {
        source: "bake_equirect_envmap.rs",
        rust_struct: "EnvmapUniforms",
        shader: "shaders/bake_equirect_envmap.wgsl",
        shader_struct: "Uniforms",
        aliases: &[],
    },
    CustomAbiCase {
        source: "bokeh_gather.rs",
        rust_struct: "BokehDilateUniforms",
        shader: "shaders/bokeh_coc_dilate_wide.wgsl",
        shader_struct: "Uniforms",
        aliases: &[],
    },
    CustomAbiCase {
        source: "digital_plants_render.rs",
        rust_struct: "RenderUniforms",
        shader: "../../generators/shaders/digital_plants_render.wgsl",
        shader_struct: "Uniforms",
        aliases: &[],
    },
    CustomAbiCase {
        source: "digital_plants_render.rs",
        rust_struct: "ShadowUniforms",
        shader: "../../generators/shaders/digital_plants_shadow.wgsl",
        shader_struct: "ShadowUniforms",
        aliases: &[],
    },
    CustomAbiCase {
        source: "gltf_texture_source.rs",
        rust_struct: "GltfTextureBlitUniforms",
        shader: "shaders/gltf_texture_blit.wgsl",
        shader_struct: "Uniforms",
        aliases: &[],
    },
    CustomAbiCase {
        source: "hdri_source.rs",
        rust_struct: "HdriBlitUniforms",
        shader: "shaders/hdri_source_blit.wgsl",
        shader_struct: "Uniforms",
        aliases: &[],
    },
    CustomAbiCase {
        source: "layer_source.rs",
        rust_struct: "LayerSourceBlitUniforms",
        shader: "shaders/layer_source_blit.wgsl",
        shader_struct: "Uniforms",
        aliases: &[],
    },
    CustomAbiCase {
        source: "image_folder.rs",
        rust_struct: "ImageFolderUniforms",
        shader: "shaders/image_folder.wgsl",
        shader_struct: "Uniforms",
        aliases: &[],
    },
    CustomAbiCase {
        source: "nested_cubes_geometry.rs",
        rust_struct: "NestedCubesUniforms",
        shader: "shaders/nested_cubes_geometry.wgsl",
        shader_struct: "Uniforms",
        aliases: &[],
    },
    CustomAbiCase {
        source: "render_3d_mesh.rs",
        rust_struct: "MaterialRenderUniforms",
        shader: "shaders/render_3d_mesh.wgsl",
        shader_struct: "Uniforms",
        aliases: &[],
    },
    CustomAbiCase {
        source: "render_instanced_3d_mesh.rs",
        rust_struct: "InstancedMaterialUniforms",
        shader: "shaders/render_instanced_3d_mesh.wgsl",
        shader_struct: "Uniforms",
        aliases: &[],
    },
    CustomAbiCase {
        source: "render_lines.rs",
        rust_struct: "LineRenderUniforms",
        shader: "shaders/render_lines.wgsl",
        shader_struct: "LineUniforms",
        aliases: &[],
    },
    CustomAbiCase {
        source: "render_scene.rs",
        rust_struct: "RenderSceneUniforms",
        shader: "shaders/render_scene.wgsl",
        shader_struct: "Uniforms",
        aliases: &[],
    },
    CustomAbiCase {
        source: "render_scene.rs",
        rust_struct: "PrefilterUniforms",
        shader: "shaders/ibl_prefilter_specular.wgsl",
        shader_struct: "PrefilterUniforms",
        aliases: &[],
    },
    CustomAbiCase {
        source: "render_scene.rs",
        rust_struct: "IrradianceUniforms",
        shader: "shaders/ibl_irradiance.wgsl",
        shader_struct: "IrradianceUniforms",
        aliases: &[],
    },
    CustomAbiCase {
        source: "render_scene.rs",
        rust_struct: "LutUniforms",
        shader: "shaders/ibl_brdf_lut.wgsl",
        shader_struct: "LutUniforms",
        aliases: &[],
    },
    CustomAbiCase {
        source: "render_scene.rs",
        rust_struct: "ShadowUniforms",
        shader: "shaders/shadow_depth.wgsl",
        shader_struct: "ShadowUniforms",
        aliases: &[],
    },
    CustomAbiCase {
        source: "render_scene.rs",
        rust_struct: "ShaftMarchUniforms",
        shader: "shaders/shaft_march.wgsl",
        shader_struct: "Uniforms",
        aliases: &[],
    },
    CustomAbiCase {
        source: "render_scene.rs",
        rust_struct: "ShaftCompositeUniforms",
        shader: "shaders/shaft_composite.wgsl",
        shader_struct: "Uniforms",
        aliases: &[],
    },
    CustomAbiCase {
        source: "render_text.rs",
        rust_struct: "RenderTextUniforms",
        shader: "shaders/render_text.wgsl",
        shader_struct: "Uniforms",
        aliases: &[],
    },
    CustomAbiCase {
        source: "watercolor.rs",
        rust_struct: "WatercolorUniforms",
        shader: "../../effects/shaders/fx_watercolor_compute.wgsl",
        shader_struct: "Uniforms",
        aliases: &[],
    },
];
