//! Standalone texture/table/resolve uniform mirrors, tied to their runtime atom.
pub struct TextureAbiCase {
    pub source: &'static str,
    pub rust_struct: &'static str,
    pub type_id: &'static str,
    pub shader_struct: &'static str,
    pub aliases: &'static [(&'static str, &'static str)],
}
pub const CASES: &[TextureAbiCase] = &[
    TextureAbiCase {
        source: "basic_shape.rs",
        rust_struct: "BasicShapeUniforms",
        type_id: "node.basic_shape",
        shader_struct: "Params",
        aliases: &[],
    },
    TextureAbiCase {
        source: "bilateral_blur.rs",
        rust_struct: "BilateralBlurUniforms",
        type_id: "node.bilateral_blur",
        shader_struct: "Params",
        aliases: &[],
    },
    TextureAbiCase {
        source: "blinn_specular.rs",
        rust_struct: "BlinnUniforms",
        type_id: "node.shininess",
        shader_struct: "Params",
        aliases: &[],
    },
    TextureAbiCase {
        source: "blob_overlay_render.rs",
        rust_struct: "OverlayUniforms",
        type_id: "node.blob_overlay",
        shader_struct: "Params",
        aliases: &[],
    },
    TextureAbiCase {
        source: "block_displace_field.rs",
        rust_struct: "BlockDisplaceUniforms",
        type_id: "node.block_displace_field",
        shader_struct: "Params",
        aliases: &[],
    },
    TextureAbiCase {
        source: "blur_3d_separable.rs",
        rust_struct: "Blur3DUniforms",
        type_id: "node.blur_3d",
        shader_struct: "Params",
        aliases: &[],
    },
    TextureAbiCase {
        source: "bokeh_gather.rs",
        rust_struct: "BokehGatherUniforms",
        type_id: "node.bokeh_gather",
        shader_struct: "Params",
        aliases: &[],
    },
    TextureAbiCase {
        source: "box_mask.rs",
        rust_struct: "BoxMaskUniforms",
        type_id: "node.rectangle_mask",
        shader_struct: "Params",
        aliases: &[],
    },
    TextureAbiCase {
        source: "centered_uv.rs",
        rust_struct: "CenteredUvUniforms",
        type_id: "node.centered_uv",
        shader_struct: "Params",
        aliases: &[],
    },
    TextureAbiCase {
        source: "checkerboard.rs",
        rust_struct: "CheckerUniforms",
        type_id: "node.checkerboard",
        shader_struct: "Params",
        aliases: &[],
    },
    TextureAbiCase {
        source: "chroma_key.rs",
        rust_struct: "ChromaKeyUniforms",
        type_id: "node.chroma_key",
        shader_struct: "Params",
        aliases: &[
            ("key_r", "key_color_x"),
            ("key_g", "key_color_y"),
            ("key_b", "key_color_z"),
            ("invert", "mode"),
        ],
    },
    TextureAbiCase {
        source: "chromatic_displace.rs",
        rust_struct: "ChromaticDisplaceUniforms",
        type_id: "node.rgb_split",
        shader_struct: "Params",
        aliases: &[],
    },
    TextureAbiCase {
        source: "clamp_texture.rs",
        rust_struct: "ClampUniforms",
        type_id: "node.clamp",
        shader_struct: "Params",
        aliases: &[],
    },
    TextureAbiCase {
        source: "coc_from_depth.rs",
        rust_struct: "CocFromDepthUniforms",
        type_id: "node.coc_from_depth",
        shader_struct: "Params",
        aliases: &[],
    },
    TextureAbiCase {
        source: "color.rs",
        rust_struct: "BrightnessUniforms",
        type_id: "node.brightness",
        shader_struct: "Params",
        aliases: &[("weights[3]", "_pad0")],
    },
    TextureAbiCase {
        source: "color.rs",
        rust_struct: "ChannelMixUniforms",
        type_id: "node.channel_mixer",
        shader_struct: "Params",
        aliases: &[],
    },
    TextureAbiCase {
        source: "color.rs",
        rust_struct: "ColorRampUniforms",
        type_id: "node.gradient_map",
        shader_struct: "Params",
        aliases: &[],
    },
    TextureAbiCase {
        source: "colorize.rs",
        rust_struct: "ColorizeUniforms",
        type_id: "node.colorize",
        shader_struct: "Params",
        aliases: &[],
    },
    TextureAbiCase {
        source: "compose.rs",
        rust_struct: "MixUniforms",
        type_id: "node.mix",
        shader_struct: "Params",
        aliases: &[],
    },
    TextureAbiCase {
        source: "contrast.rs",
        rust_struct: "ContrastUniforms",
        type_id: "node.contrast",
        shader_struct: "Params",
        aliases: &[],
    },
    TextureAbiCase {
        source: "convolution_2d_9tap.rs",
        rust_struct: "ConvUniforms",
        type_id: "node.custom_convolution",
        shader_struct: "Params",
        aliases: &[],
    },
    TextureAbiCase {
        source: "curl_slope_force_3d.rs",
        rust_struct: "CurlSlope3DUniforms",
        type_id: "node.swirl_force_3d",
        shader_struct: "Params",
        aliases: &[],
    },
    TextureAbiCase {
        source: "distance_to_point.rs",
        rust_struct: "DistanceUniforms",
        type_id: "node.distance_to_point",
        shader_struct: "Params",
        aliases: &[],
    },
    TextureAbiCase {
        source: "dither.rs",
        rust_struct: "DitherUniforms",
        type_id: "node.dither",
        shader_struct: "Params",
        aliases: &[],
    },
    TextureAbiCase {
        source: "dither_pattern.rs",
        rust_struct: "DitherPatternUniforms",
        type_id: "node.dither_pattern",
        shader_struct: "Params",
        aliases: &[],
    },
    TextureAbiCase {
        source: "downsample.rs",
        rust_struct: "DownsampleUniforms",
        type_id: "node.downsample",
        shader_struct: "Params",
        aliases: &[],
    },
    TextureAbiCase {
        source: "draw_connections.rs",
        rust_struct: "ConnectionsUniforms",
        type_id: "node.draw_connections",
        shader_struct: "Params",
        aliases: &[],
    },
    TextureAbiCase {
        source: "draw_dots.rs",
        rust_struct: "DotsUniforms",
        type_id: "node.draw_dots",
        shader_struct: "Params",
        aliases: &[],
    },
    TextureAbiCase {
        source: "draw_gauge.rs",
        rust_struct: "GaugeUniforms",
        type_id: "node.draw_gauge",
        shader_struct: "Params",
        aliases: &[],
    },
    TextureAbiCase {
        source: "draw_markers.rs",
        rust_struct: "MarkersUniforms",
        type_id: "node.draw_markers",
        shader_struct: "Params",
        aliases: &[],
    },
    TextureAbiCase {
        source: "draw_scanlines.rs",
        rust_struct: "ScanlinesUniforms",
        type_id: "node.draw_scanlines",
        shader_struct: "Params",
        aliases: &[],
    },
    TextureAbiCase {
        source: "draw_ticks.rs",
        rust_struct: "TicksUniforms",
        type_id: "node.draw_ticks",
        shader_struct: "Params",
        aliases: &[],
    },
    TextureAbiCase {
        source: "edge_detect.rs",
        rust_struct: "EdgeDetectUniforms",
        type_id: "node.edge_detect",
        shader_struct: "Params",
        aliases: &[],
    },
    TextureAbiCase {
        source: "ellipse_mask.rs",
        rust_struct: "EllipseMaskUniforms",
        type_id: "node.circle_mask",
        shader_struct: "Params",
        aliases: &[],
    },
    TextureAbiCase {
        source: "field_combine.rs",
        rust_struct: "FieldCombineUniforms",
        type_id: "node.field_combine",
        shader_struct: "Params",
        aliases: &[],
    },
    TextureAbiCase {
        source: "film_grain.rs",
        rust_struct: "FilmGrainUniforms",
        type_id: "node.film_grain",
        shader_struct: "Params",
        aliases: &[],
    },
    TextureAbiCase {
        source: "flash.rs",
        rust_struct: "FlashUniforms",
        type_id: "node.flash",
        shader_struct: "Params",
        aliases: &[],
    },
    TextureAbiCase {
        source: "flow_field_noise.rs",
        rust_struct: "FlowFieldUniforms",
        type_id: "node.flow_field_noise",
        shader_struct: "Params",
        aliases: &[],
    },
    TextureAbiCase {
        source: "fract_texture.rs",
        rust_struct: "FractUniforms",
        type_id: "node.wrap",
        shader_struct: "Params",
        aliases: &[],
    },
    TextureAbiCase {
        source: "fresnel_rim.rs",
        rust_struct: "FresnelUniforms",
        type_id: "node.rim_light",
        shader_struct: "Params",
        aliases: &[],
    },
    TextureAbiCase {
        source: "gain.rs",
        rust_struct: "GainUniforms",
        type_id: "node.exposure",
        shader_struct: "Params",
        aliases: &[],
    },
    TextureAbiCase {
        source: "gaussian_blur_variable_width.rs",
        rust_struct: "BlurUniforms",
        type_id: "node.variable_blur",
        shader_struct: "Params",
        aliases: &[("direction", "axis")],
    },
    TextureAbiCase {
        source: "gradient_central_diff.rs",
        rust_struct: "GradientUniforms",
        type_id: "node.edge_slope",
        shader_struct: "Params",
        aliases: &[],
    },
    TextureAbiCase {
        source: "gradient_central_diff_3d.rs",
        rust_struct: "Gradient3DUniforms",
        type_id: "node.edge_slope_3d",
        shader_struct: "Params",
        aliases: &[],
    },
    TextureAbiCase {
        source: "gradient_ramp.rs",
        rust_struct: "GradientRampUniforms",
        type_id: "node.gradient",
        shader_struct: "Params",
        aliases: &[("count", "stops_count")],
    },
    TextureAbiCase {
        source: "hash_field_by_seed.rs",
        rust_struct: "HashFieldUniforms",
        type_id: "node.hash_field_by_seed",
        shader_struct: "Params",
        aliases: &[],
    },
    TextureAbiCase {
        source: "hdr_retention_mix.rs",
        rust_struct: "HdrRetentionMixUniforms",
        type_id: "node.hdr_mix",
        shader_struct: "Params",
        aliases: &[],
    },
    TextureAbiCase {
        source: "heightfield_shadow.rs",
        rust_struct: "HeightfieldShadowUniforms",
        type_id: "node.heightfield_shadow",
        shader_struct: "Params",
        aliases: &[],
    },
    TextureAbiCase {
        source: "heightmap_to_normal.rs",
        rust_struct: "HeightmapNormalUniforms",
        type_id: "node.surface_bumps",
        shader_struct: "Params",
        aliases: &[],
    },
    TextureAbiCase {
        source: "hue_saturation.rs",
        rust_struct: "HueSaturationUniforms",
        type_id: "node.hue_saturation",
        shader_struct: "Params",
        aliases: &[("hue_degrees", "hue")],
    },
    TextureAbiCase {
        source: "invert.rs",
        rust_struct: "InvertUniforms",
        type_id: "node.invert",
        shader_struct: "Params",
        aliases: &[],
    },
    TextureAbiCase {
        source: "levels.rs",
        rust_struct: "LevelsUniforms",
        type_id: "node.levels",
        shader_struct: "Params",
        aliases: &[],
    },
    TextureAbiCase {
        source: "lic_integrate.rs",
        rust_struct: "LicUniforms",
        type_id: "node.flow_lines",
        shader_struct: "Params",
        aliases: &[],
    },
    TextureAbiCase {
        source: "linear_gradient.rs",
        rust_struct: "LinearGradientUniforms",
        type_id: "node.linear_gradient",
        shader_struct: "Params",
        aliases: &[],
    },
    TextureAbiCase {
        source: "lut1d.rs",
        rust_struct: "Lut1dUniforms",
        type_id: "node.color_lut",
        shader_struct: "Params",
        aliases: &[],
    },
    TextureAbiCase {
        source: "masked_mix.rs",
        rust_struct: "MaskedMixUniforms",
        type_id: "node.masked_mix",
        shader_struct: "Params",
        aliases: &[],
    },
    TextureAbiCase {
        source: "matcap_two_tone.rs",
        rust_struct: "MatcapUniforms",
        type_id: "node.matcap_two_tone",
        shader_struct: "Params",
        aliases: &[],
    },
    TextureAbiCase {
        source: "mirror_axis.rs",
        rust_struct: "MirrorAxisUniforms",
        type_id: "node.flip",
        shader_struct: "Params",
        aliases: &[],
    },
    TextureAbiCase {
        source: "mirror_fold_uv.rs",
        rust_struct: "MirrorFoldUvUniforms",
        type_id: "node.mirror",
        shader_struct: "Params",
        aliases: &[],
    },
    TextureAbiCase {
        source: "motion_blur.rs",
        rust_struct: "MotionBlurUniforms",
        type_id: "node.motion_blur",
        shader_struct: "Params",
        aliases: &[],
    },
    TextureAbiCase {
        source: "noise.rs",
        rust_struct: "NoiseUniforms",
        type_id: "node.noise",
        shader_struct: "Params",
        aliases: &[("noise_type", "p_type")],
    },
    TextureAbiCase {
        source: "pack_channels.rs",
        rust_struct: "PackUniforms",
        type_id: "node.pack_rgba",
        shader_struct: "Params",
        aliases: &[],
    },
    TextureAbiCase {
        source: "polar_field.rs",
        rust_struct: "PolarUniforms",
        type_id: "node.polar_field",
        shader_struct: "Params",
        aliases: &[],
    },
    TextureAbiCase {
        source: "posterize.rs",
        rust_struct: "PosterizeUniforms",
        type_id: "node.posterize",
        shader_struct: "Params",
        aliases: &[],
    },
    TextureAbiCase {
        source: "power_texture.rs",
        rust_struct: "PowerUniforms",
        type_id: "node.power",
        shader_struct: "Params",
        aliases: &[],
    },
    TextureAbiCase {
        source: "radial_burst_force_field.rs",
        rust_struct: "BurstUniforms",
        type_id: "node.explosion_force",
        shader_struct: "Params",
        aliases: &[("time_val", "time")],
    },
    TextureAbiCase {
        source: "radial_fold_uv.rs",
        rust_struct: "RadialFoldUvUniforms",
        type_id: "node.kaleidoscope",
        shader_struct: "Params",
        aliases: &[],
    },
    TextureAbiCase {
        source: "radial_offset_field.rs",
        rust_struct: "RadialOffsetFieldUniforms",
        type_id: "node.radial_offset_field",
        shader_struct: "Params",
        aliases: &[],
    },
    TextureAbiCase {
        source: "reinhard_tone_map.rs",
        rust_struct: "ReinhardUniforms",
        type_id: "node.reinhard_tone_map",
        shader_struct: "Params",
        aliases: &[],
    },
    TextureAbiCase {
        source: "remap.rs",
        rust_struct: "RemapUniforms",
        type_id: "node.remap",
        shader_struct: "Params",
        aliases: &[],
    },
    TextureAbiCase {
        source: "resolve_3d_accumulator.rs",
        rust_struct: "Resolve3DUniforms",
        type_id: "node.resolve_scatter_3d",
        shader_struct: "Params",
        aliases: &[],
    },
    TextureAbiCase {
        source: "resolve_accumulator.rs",
        rust_struct: "ResolveUniforms",
        type_id: "node.resolve_scatter",
        shader_struct: "Params",
        aliases: &[],
    },
    TextureAbiCase {
        source: "rotate_2d.rs",
        rust_struct: "Rotate2DUniforms",
        type_id: "node.rotate_coordinates",
        shader_struct: "Params",
        aliases: &[],
    },
    TextureAbiCase {
        source: "rotate_vec2_by_angle.rs",
        rust_struct: "RotateUniforms",
        type_id: "node.rotate_vector",
        shader_struct: "Params",
        aliases: &[],
    },
    TextureAbiCase {
        source: "sample_volume_2d.rs",
        rust_struct: "SampleVolumeUniforms",
        type_id: "node.slice_volume",
        shader_struct: "Params",
        aliases: &[],
    },
    TextureAbiCase {
        source: "saturation.rs",
        rust_struct: "SaturationUniforms",
        type_id: "node.saturation",
        shader_struct: "Params",
        aliases: &[],
    },
    TextureAbiCase {
        source: "scale_offset_texture.rs",
        rust_struct: "ScaleOffsetUniforms",
        type_id: "node.scale_offset_image",
        shader_struct: "Params",
        aliases: &[],
    },
    TextureAbiCase {
        source: "scanline_jitter_field.rs",
        rust_struct: "ScanlineJitterUniforms",
        type_id: "node.scanline_jitter_field",
        shader_struct: "Params",
        aliases: &[],
    },
    TextureAbiCase {
        source: "separable_gaussian.rs",
        rust_struct: "SeparableGaussianUniforms",
        type_id: "node.gaussian_blur",
        shader_struct: "Params",
        aliases: &[],
    },
    TextureAbiCase {
        source: "set_alpha.rs",
        rust_struct: "SetAlphaUniforms",
        type_id: "node.set_alpha",
        shader_struct: "Params",
        aliases: &[],
    },
    TextureAbiCase {
        source: "sharpen.rs",
        rust_struct: "SharpenUniforms",
        type_id: "node.sharpen",
        shader_struct: "Params",
        aliases: &[],
    },
    TextureAbiCase {
        source: "simplex_field_2d.rs",
        rust_struct: "SimplexFieldUniforms",
        type_id: "node.simplex_field_2d",
        shader_struct: "Params",
        aliases: &[],
    },
    TextureAbiCase {
        source: "sin_term.rs",
        rust_struct: "SinTermUniforms",
        type_id: "node.sine_wave",
        shader_struct: "Params",
        aliases: &[],
    },
    TextureAbiCase {
        source: "slope_displace.rs",
        rust_struct: "SlopeDisplaceUniforms",
        type_id: "node.slope_displace",
        shader_struct: "Params",
        aliases: &[],
    },
    TextureAbiCase {
        source: "smoothstep_texture.rs",
        rust_struct: "SmoothstepUniforms",
        type_id: "node.smoothstep",
        shader_struct: "Params",
        aliases: &[],
    },
    TextureAbiCase {
        source: "ssao_gtao.rs",
        rust_struct: "SsaoGtaoUniforms",
        type_id: "node.ssao_gtao",
        shader_struct: "Params",
        aliases: &[],
    },
    TextureAbiCase {
        source: "texture_advect.rs",
        rust_struct: "AdvectUniforms",
        type_id: "node.texture_advect",
        shader_struct: "Params",
        aliases: &[],
    },
    TextureAbiCase {
        source: "texture_sum_5.rs",
        rust_struct: "TextureSum5Uniforms",
        type_id: "node.texture_sum_5",
        shader_struct: "Params",
        aliases: &[],
    },
    TextureAbiCase {
        source: "tone_map.rs",
        rust_struct: "ToneMapUniforms",
        type_id: "node.tone_map",
        shader_struct: "Params",
        aliases: &[],
    },
    TextureAbiCase {
        source: "trig_texture.rs",
        rust_struct: "TrigUniforms",
        type_id: "node.sine_cosine",
        shader_struct: "Params",
        aliases: &[],
    },
    TextureAbiCase {
        source: "uv_displace_by_flow.rs",
        rust_struct: "DisplaceUniforms",
        type_id: "node.uv_displace_by_flow",
        shader_struct: "Params",
        aliases: &[],
    },
    TextureAbiCase {
        source: "uv_strip_clamp.rs",
        rust_struct: "UvStripClampUniforms",
        type_id: "node.edge_stretch",
        shader_struct: "Params",
        aliases: &[("mode", "direction")],
    },
    TextureAbiCase {
        source: "vignette.rs",
        rust_struct: "VignetteUniforms",
        type_id: "node.vignette",
        shader_struct: "Params",
        aliases: &[],
    },
    TextureAbiCase {
        source: "voronoi_2d.rs",
        rust_struct: "VoronoiUniforms",
        type_id: "node.voronoi_2d",
        shader_struct: "Params",
        aliases: &[],
    },
    TextureAbiCase {
        source: "wet_dry_mix.rs",
        rust_struct: "WetDryMixUniforms",
        type_id: "node.wet_dry",
        shader_struct: "Params",
        aliases: &[],
    },
];
