use crate::effects::{EffectGroup, PresetInstance};
use crate::id::ClipId;
use crate::units::{Beats, Seconds};
use serde::{Deserialize, Serialize};
use std::collections::BTreeMap;

/// A single clip on the timeline. Beat-primary timing.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct TimelineClip {
    pub id: ClipId,
    #[serde(default)]
    pub video_clip_id: String,
    /// Audio file path for an audio-layer clip. Empty for video / generator
    /// clips; non-empty marks this as an audio clip (discriminated the same way
    /// `video_clip_id` marks a video clip). The owning layer is `LayerType::Audio`.
    /// The derived per-send feature curve is runtime-only (cached by `ClipId`),
    /// never serialized. See `docs/AUDIO_LAYER_DESIGN.md`.
    #[serde(default, skip_serializing_if = "String::is_empty")]
    pub audio_file_path: String,

    /// Absolute path to a still image for an image clip. Empty for
    /// video / generator / audio clips; non-empty marks this as a static
    /// image clip (discriminated the same way `video_clip_id` marks a
    /// video clip and `audio_file_path` marks an audio clip). The owning
    /// layer is `LayerType::Video`; the clip simply displays the image,
    /// aspect-fit into the canvas, for its timeline duration. The decoded
    /// texture is runtime-only (cached by `ClipId` in `ImageRenderer`),
    /// never serialized.
    #[serde(default, skip_serializing_if = "String::is_empty")]
    pub image_path: String,

    /// Per-clip percussion detection state (settings + cached analysis), present
    /// only on audio clips that have a detection config. See
    /// `docs/AUDIO_CLIP_DETECTION_DESIGN.md`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub audio_detection: Option<crate::audio_clip_detection::AudioClipDetection>,

    /// For a trigger clip generated by detection: the `ClipId` of the audio clip
    /// that produced it. Lets a re-detect clear only its own triggers. `None` for
    /// hand-placed clips and audio source clips.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub detection_source: Option<ClipId>,

    // ── Beat-primary timing (source of truth) ──
    #[serde(default)]
    pub start_beat: Beats,
    #[serde(default = "default_one_beat")]
    pub duration_beats: Beats,

    // ── Seconds (video source offset, BPM-independent) ──
    #[serde(default)]
    pub in_point: Seconds,
    /// Audio only: the full decoded length of the source file (seconds), captured
    /// at import. Bounds right-edge trimming — an audio clip can't be lengthened
    /// past the end of its file (Ableton model). Zero / unset for non-audio clips.
    #[serde(default, skip_serializing_if = "Seconds::is_zero")]
    pub source_duration: Seconds,

    // ── Metadata ──
    #[serde(default)]
    pub recorded_bpm: f32,
    #[serde(default)]
    pub is_locked: bool,
    #[serde(default)]
    pub is_muted: bool,

    /// Per-clip colour override. `None` (the default) means the clip draws in its
    /// owning layer's colour — the historical behaviour, so old projects round-trip
    /// untouched. `Some(c)` lets a clip carry its own identity colour independent of
    /// the layer. Skipped on serialize when unset.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub color_override: Option<crate::color::Color>,

    // ── Legacy fields (deserialized from old projects, never written back) ──
    #[serde(default, skip_serializing)]
    pub layer_id: crate::id::LayerId,
    #[serde(default, skip_serializing)]
    pub generator_type: crate::preset_type_id::PresetTypeId,
    #[serde(default, skip_serializing)]
    pub invert_colors: bool,

    // ── Transform ──
    #[serde(default)]
    pub translate_x: f32,
    #[serde(default)]
    pub translate_y: f32,
    #[serde(default = "default_one")]
    pub scale: f32,
    #[serde(default)]
    pub rotation: f32,

    // ── String params (per-clip, for generators that need text/string data) ──
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub string_params: Option<BTreeMap<String, String>>,

    // ── Looping ──
    #[serde(default)]
    pub is_looping: bool,
    #[serde(default)]
    pub loop_duration_beats: Beats,

    // ── MIDI tick ──
    #[serde(default)]
    pub start_absolute_tick: i32,
    #[serde(default)]
    pub has_start_absolute_tick: bool,

    // ── Legacy: per-clip effects removed (Ableton model: effects on layer/master only) ──
    // Fields kept for deserialization of old projects, never written back.
    #[serde(default, skip_serializing)]
    pub effects: Vec<PresetInstance>,
    #[serde(default, skip_serializing)]
    pub effect_groups: Option<Vec<EffectGroup>>,
    // Clip-level effect envelopes (legacy, never evaluated or written back)
    // moved onto each clip effect's `PresetInstance.envelopes` in the
    // v1.5→v1.6 migration — see envelope-home unification. No standalone
    // clip envelope field remains.

    // ── Legacy flat generator params (V1.0.0 clips) ──
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "genRotSpeedXY"
    )]
    pub legacy_gen_rot_speed_xy: Option<f32>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "genRotSpeedZW"
    )]
    pub legacy_gen_rot_speed_zw: Option<f32>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "genRotSpeedXW"
    )]
    pub legacy_gen_rot_speed_xw: Option<f32>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "genLineThickness"
    )]
    pub legacy_gen_line_thickness: Option<f32>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "genProjDistance"
    )]
    pub legacy_gen_proj_distance: Option<f32>,
}

impl TimelineClip {
    #[must_use]
    pub fn end_beat(&self) -> Beats {
        self.start_beat + self.duration_beats
    }

    pub fn is_active_at_beat(&self, beat: Beats) -> bool {
        beat >= self.start_beat && beat < self.end_beat()
    }

    pub fn overlaps_with(&self, other: &TimelineClip) -> bool {
        self.start_beat < other.end_beat() && self.end_beat() > other.start_beat
    }

    pub fn has_any_effect(&self) -> bool {
        self.translate_x != 0.0
            || self.translate_y != 0.0
            || self.scale != 1.0
            || self.rotation != 0.0
    }

    /// Deep clone with new ID.
    ///
    /// The clip's nested effects are also given fresh identities (via
    /// [`PresetInstance::duplicated`]); otherwise a duplicated/split/pasted
    /// clip's effects would share `EffectId`s with the source clip's effects
    /// and collide under the project's first-match `find_effect_by_id` lookup.
    pub fn clone_with_new_id(&self) -> Self {
        let mut cloned = self.clone();
        cloned.id = ClipId::new(crate::short_id());
        cloned.effects = self.effects.iter().map(|e| e.duplicated()).collect();
        cloned
    }

    /// Deep clone with optionally overridden start beat.
    pub fn clone_at(&self, start_beat: Option<Beats>) -> Self {
        let mut cloned = self.clone_with_new_id();
        if let Some(beat) = start_beat {
            cloned.start_beat = beat;
        }
        cloned
    }

    // ── Clamped setters (match Unity TimelineClip property setters) ──

    /// Set duration with non-negative clamp. Unity TimelineClip.cs line 82.
    pub fn set_duration_beats(&mut self, v: Beats) {
        self.duration_beats = v.max(Beats::ZERO);
    }

    /// Set in-point with non-negative clamp. Unity TimelineClip.cs line 114.
    pub fn set_in_point(&mut self, v: Seconds) {
        self.in_point = v.max(Seconds::ZERO);
    }

    /// Resolved recorded BPM: clamped to 20-300 if > 0, else 0.
    /// Unity TimelineClip.cs lines 122-123.
    pub fn recorded_bpm_resolved(&self) -> f32 {
        if self.recorded_bpm > 0.0 {
            self.recorded_bpm.clamp(20.0, 300.0)
        } else {
            0.0
        }
    }

    /// Warp ratio for this clip at `project_bpm` (Audio Layer §4.1): how much
    /// faster than 1× the source must play to lock the clip's recorded tempo to
    /// the project. `project_bpm / recorded_bpm`, or **1.0 when the clip has no
    /// recorded BPM** (0 = warp off → source plays at its native speed). The
    /// single source for both the audio voice (`playback_rate`) and the offline
    /// modulation-curve index, so what modulates stays aligned to what is heard.
    pub fn warp_ratio(&self, project_bpm: f32) -> f32 {
        let clip_bpm = self.recorded_bpm_resolved();
        if clip_bpm <= 0.0 || project_bpm <= 0.0 {
            1.0
        } else {
            project_bpm / clip_bpm
        }
    }

    /// Set recorded BPM with clamping. Unity TimelineClip.cs lines 126-133.
    pub fn set_recorded_bpm(&mut self, v: f32) {
        if v <= 0.0 {
            self.recorded_bpm = 0.0;
        } else {
            self.recorded_bpm = v.clamp(20.0, 300.0);
        }
    }

    /// Resolved start absolute tick: -1 when not available, else max(0, val).
    /// Unity TimelineClip.cs lines 94-95.
    pub fn start_absolute_tick_resolved(&self) -> i32 {
        if self.has_start_absolute_tick {
            self.start_absolute_tick.max(0)
        } else {
            -1
        }
    }

    /// Create a new video clip.
    pub fn new_video(
        video_clip_id: String,
        start_beat: Beats,
        duration_beats: Beats,
        in_point: Seconds,
    ) -> Self {
        Self {
            video_clip_id,
            start_beat,
            duration_beats: duration_beats.max(Beats::ZERO),
            in_point: in_point.max(Seconds::ZERO),
            ..Default::default()
        }
    }

    /// Create a new generator clip.
    pub fn new_generator(start_beat: Beats, duration_beats: Beats) -> Self {
        Self {
            start_beat,
            duration_beats: duration_beats.max(Beats::ZERO),
            ..Default::default()
        }
    }

    /// Create a new audio clip backed by a decoded file. `in_point` is the
    /// offset into the source file (seconds, BPM-independent, like video).
    /// `recorded_bpm` carries the clip's native tempo for warp (0 = no warp).
    pub fn new_audio(
        audio_file_path: String,
        start_beat: Beats,
        duration_beats: Beats,
        in_point: Seconds,
        source_duration: Seconds,
    ) -> Self {
        Self {
            audio_file_path,
            start_beat,
            duration_beats: duration_beats.max(Beats::ZERO),
            in_point: in_point.max(Seconds::ZERO),
            source_duration: source_duration.max(Seconds::ZERO),
            ..Default::default()
        }
    }

    /// Whether this clip is an audio clip (has a backing audio file path).
    pub fn is_audio(&self) -> bool {
        !self.audio_file_path.is_empty()
    }

    /// Create a new image clip that displays a still image for its timeline
    /// duration. `image_path` is the absolute path to the source file; the
    /// owning layer must be `LayerType::Video`.
    pub fn new_image(image_path: String, start_beat: Beats, duration_beats: Beats) -> Self {
        Self {
            image_path,
            start_beat,
            duration_beats: duration_beats.max(Beats::ZERO),
            ..Default::default()
        }
    }

    /// Whether this clip is a still-image clip (has a backing image path).
    pub fn is_image(&self) -> bool {
        !self.image_path.is_empty()
    }

    /// Set scale with clamp. Unity TimelineClip.cs line 179.
    pub fn set_scale(&mut self, v: f32) {
        self.scale = v.max(0.01);
    }

    /// Set loop duration with clamp. Unity TimelineClip.cs line 201.
    pub fn set_loop_duration_beats(&mut self, v: Beats) {
        self.loop_duration_beats = v.max(Beats::ZERO);
    }
}

impl Default for TimelineClip {
    fn default() -> Self {
        Self {
            id: ClipId::new(crate::short_id()),
            video_clip_id: String::new(),
            audio_file_path: String::new(),
            image_path: String::new(),
            audio_detection: None,
            detection_source: None,
            layer_id: crate::id::LayerId::default(),
            start_beat: Beats::ZERO,
            duration_beats: Beats::ONE,
            in_point: Seconds::ZERO,
            source_duration: Seconds::ZERO,
            recorded_bpm: 0.0,
            is_locked: false,
            is_muted: false,
            color_override: None,
            invert_colors: false,
            generator_type: crate::preset_type_id::PresetTypeId::NONE,
            translate_x: 0.0,
            translate_y: 0.0,
            scale: 1.0,
            rotation: 0.0,
            string_params: None,
            is_looping: false,
            loop_duration_beats: Beats::ZERO,
            start_absolute_tick: 0,
            has_start_absolute_tick: false,
            effects: Vec::new(),
            effect_groups: None,
            legacy_gen_rot_speed_xy: None,
            legacy_gen_rot_speed_zw: None,
            legacy_gen_rot_speed_xw: None,
            legacy_gen_line_thickness: None,
            legacy_gen_proj_distance: None,
        }
    }
}

fn default_one() -> f32 {
    1.0
}
fn default_one_beat() -> Beats {
    Beats::ONE
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_set_duration_beats_clamps_negative() {
        let mut clip = TimelineClip::default();
        clip.set_duration_beats(Beats(-5.0));
        assert_eq!(clip.duration_beats, Beats(0.0));
    }

    #[test]
    fn clone_with_new_id_regenerates_nested_effect_ids() {
        // BUG-002: a duplicated/split/pasted clip must give its effects fresh
        // EffectIds. Otherwise two clips' effects collide under the project's
        // first-match find_effect_by_id lookup (edits cross-talk).
        let mut clip = TimelineClip::new_generator(Beats(0.0), Beats(4.0));
        clip.effects
            .push(PresetInstance::new(crate::PresetTypeId::new("Blur")));
        clip.effects
            .push(PresetInstance::new(crate::PresetTypeId::new("Bloom")));

        let cloned = clip.clone_with_new_id();

        assert_ne!(cloned.id, clip.id, "clip gets a fresh ClipId");
        assert_eq!(cloned.effects.len(), clip.effects.len());
        for (a, b) in cloned.effects.iter().zip(&clip.effects) {
            assert_ne!(a.id, b.id, "each cloned effect gets a fresh EffectId");
        }
    }

    #[test]
    fn test_set_duration_beats_preserves_positive() {
        let mut clip = TimelineClip::default();
        clip.set_duration_beats(Beats(4.0));
        assert_eq!(clip.duration_beats, Beats(4.0));
    }

    #[test]
    fn test_set_in_point_clamps_negative() {
        let mut clip = TimelineClip::default();
        clip.set_in_point(Seconds(-2.0));
        assert_eq!(clip.in_point, Seconds(0.0));
    }

    #[test]
    fn color_override_defaults_none_and_is_skipped_when_unset() {
        // Default = layer colour (None), and an unset override never appears in
        // the JSON — old projects round-trip byte-for-byte on this field.
        let clip = TimelineClip::default();
        assert_eq!(clip.color_override, None);
        let json = serde_json::to_string(&clip).unwrap();
        assert!(
            !json.contains("colorOverride"),
            "unset override must be skipped on serialize, got: {json}"
        );
    }

    #[test]
    fn color_override_roundtrips_when_set() {
        let mut clip = TimelineClip::default();
        clip.color_override = Some(crate::color::Color::new(0.2, 0.4, 0.6, 1.0));
        let json = serde_json::to_string(&clip).unwrap();
        assert!(json.contains("colorOverride"));
        let back: TimelineClip = serde_json::from_str(&json).unwrap();
        assert_eq!(back.color_override, clip.color_override);
    }

    #[test]
    fn test_recorded_bpm_resolved_zero_passthrough() {
        let clip = TimelineClip {
            recorded_bpm: 0.0,
            ..Default::default()
        };
        assert_eq!(clip.recorded_bpm_resolved(), 0.0);
    }

    #[test]
    fn test_warp_ratio_passthrough_when_no_clip_bpm() {
        // recorded_bpm 0 ⇒ warp off ⇒ ratio 1.0 regardless of project tempo.
        let clip = TimelineClip { recorded_bpm: 0.0, ..Default::default() };
        assert_eq!(clip.warp_ratio(128.0), 1.0);
        assert_eq!(clip.warp_ratio(0.0), 1.0);
    }

    #[test]
    fn test_warp_ratio_project_over_clip() {
        // 120-BPM clip on a 128-BPM project must play 128/120× faster.
        let clip = TimelineClip { recorded_bpm: 120.0, ..Default::default() };
        assert!((clip.warp_ratio(128.0) - 128.0 / 120.0).abs() < 1e-6);
        // Clamp applies through recorded_bpm_resolved (10 ⇒ 20).
        let slow = TimelineClip { recorded_bpm: 10.0, ..Default::default() };
        assert!((slow.warp_ratio(120.0) - 120.0 / 20.0).abs() < 1e-6);
    }

    #[test]
    fn test_recorded_bpm_resolved_clamps_low() {
        let clip = TimelineClip {
            recorded_bpm: 10.0,
            ..Default::default()
        };
        assert_eq!(clip.recorded_bpm_resolved(), 20.0);
    }

    #[test]
    fn test_recorded_bpm_resolved_clamps_high() {
        let clip = TimelineClip {
            recorded_bpm: 500.0,
            ..Default::default()
        };
        assert_eq!(clip.recorded_bpm_resolved(), 300.0);
    }

    #[test]
    fn test_recorded_bpm_resolved_normal() {
        let clip = TimelineClip {
            recorded_bpm: 120.0,
            ..Default::default()
        };
        assert_eq!(clip.recorded_bpm_resolved(), 120.0);
    }

    #[test]
    fn test_set_recorded_bpm_clamps() {
        let mut clip = TimelineClip::default();
        clip.set_recorded_bpm(-1.0);
        assert_eq!(clip.recorded_bpm, 0.0);
        clip.set_recorded_bpm(10.0);
        assert_eq!(clip.recorded_bpm, 20.0);
        clip.set_recorded_bpm(500.0);
        assert_eq!(clip.recorded_bpm, 300.0);
    }

    #[test]
    fn test_start_absolute_tick_resolved_not_available() {
        let clip = TimelineClip {
            has_start_absolute_tick: false,
            start_absolute_tick: 42,
            ..Default::default()
        };
        assert_eq!(clip.start_absolute_tick_resolved(), -1);
    }

    #[test]
    fn test_start_absolute_tick_resolved_available() {
        let clip = TimelineClip {
            has_start_absolute_tick: true,
            start_absolute_tick: 48,
            ..Default::default()
        };
        assert_eq!(clip.start_absolute_tick_resolved(), 48);
    }

    #[test]
    fn test_start_absolute_tick_resolved_clamps_negative() {
        let clip = TimelineClip {
            has_start_absolute_tick: true,
            start_absolute_tick: -5,
            ..Default::default()
        };
        assert_eq!(clip.start_absolute_tick_resolved(), 0);
    }

    #[test]
    fn test_new_video_clamps_duration() {
        let clip = TimelineClip::new_video("v1".into(), Beats(0.0), Beats(-3.0), Seconds(-1.0));
        assert_eq!(clip.duration_beats, Beats(0.0));
        assert_eq!(clip.in_point, Seconds(0.0));
    }

    #[test]
    fn test_new_generator_clamps_duration() {
        let clip = TimelineClip::new_generator(Beats(0.0), Beats(-2.0));
        assert_eq!(clip.duration_beats, Beats(0.0));
    }

    #[test]
    fn test_new_audio_clip_discriminates_and_round_trips() {
        let clip = TimelineClip::new_audio(
            "/tmp/kick.wav".into(),
            Beats(4.0),
            Beats(8.0),
            Seconds(1.5),
            Seconds(10.0),
        );
        assert!(clip.is_audio());
        assert_eq!(clip.source_duration, Seconds(10.0));
        assert!(!TimelineClip::new_generator(Beats(0.0), Beats(1.0)).is_audio());
        assert_eq!(clip.in_point, Seconds(1.5));

        let json = serde_json::to_string(&clip).unwrap();
        assert!(json.contains("audioFilePath"));
        let back: TimelineClip = serde_json::from_str(&json).unwrap();
        assert_eq!(back.audio_file_path, "/tmp/kick.wav");
        assert!(back.is_audio());

        // A non-audio clip must not emit the key (byte-identical legacy fixtures).
        let video = TimelineClip::new_video("v1".into(), Beats(0.0), Beats(1.0), Seconds(0.0));
        assert!(!serde_json::to_string(&video).unwrap().contains("audioFilePath"));
    }

    #[test]
    fn test_new_image_clip_discriminates_and_round_trips() {
        let clip = TimelineClip::new_image("/tmp/logo.png".into(), Beats(2.0), Beats(4.0));
        assert!(clip.is_image());
        assert!(!clip.is_audio());
        assert!(clip.video_clip_id.is_empty());
        assert_eq!(clip.duration_beats, Beats(4.0));

        let json = serde_json::to_string(&clip).unwrap();
        assert!(json.contains("imagePath"));
        let back: TimelineClip = serde_json::from_str(&json).unwrap();
        assert_eq!(back.image_path, "/tmp/logo.png");
        assert!(back.is_image());

        // Non-image clips must not emit the key (legacy fixtures stay byte-identical).
        let video = TimelineClip::new_video("v1".into(), Beats(0.0), Beats(1.0), Seconds(0.0));
        assert!(!serde_json::to_string(&video).unwrap().contains("imagePath"));
        let generator = TimelineClip::new_generator(Beats(0.0), Beats(1.0));
        assert!(!generator.is_image());
    }

    #[test]
    fn test_audio_detection_and_source_round_trip() {
        use crate::audio_clip_detection::AudioClipDetection;

        let mut clip = TimelineClip::new_audio(
            "/tmp/song.wav".into(),
            Beats(0.0),
            Beats(8.0),
            Seconds(0.0),
            Seconds(120.0),
        );
        clip.audio_detection = Some(AudioClipDetection::new());

        let json = serde_json::to_string(&clip).unwrap();
        assert!(json.contains("audioDetection"));
        let back: TimelineClip = serde_json::from_str(&json).unwrap();
        let det = back.audio_detection.expect("detection survives roundtrip");
        assert_eq!(det.config.instruments.len(), 9);
        assert!(!det.has_analysis());

        // A trigger clip carries its source clip id back and forth.
        let mut trigger = TimelineClip::new_generator(Beats(1.0), Beats(0.25));
        trigger.detection_source = Some(clip.id.clone());
        let json = serde_json::to_string(&trigger).unwrap();
        assert!(json.contains("detectionSource"));
        let back: TimelineClip = serde_json::from_str(&json).unwrap();
        assert_eq!(back.detection_source, Some(clip.id.clone()));

        // Clips without detection omit both keys (legacy fixtures stay byte-identical).
        let plain = TimelineClip::new_generator(Beats(0.0), Beats(1.0));
        let json = serde_json::to_string(&plain).unwrap();
        assert!(!json.contains("audioDetection"));
        assert!(!json.contains("detectionSource"));
    }
}
