#![forbid(unsafe_code)]

pub mod ableton_mapping;
pub mod clip;
pub mod color;
pub mod effect_graph_def;
pub mod effect_registration;
pub mod effects;
pub mod flatten;
pub mod generator;
pub mod generator_metadata_submissions;
pub mod generator_registration;
pub mod graph_target;
pub mod group_edit;
pub mod id;
pub mod layer;
pub mod macro_bank;
pub mod marker;
pub mod math;
pub mod midi;
pub mod percussion;
pub mod percussion_analysis;
pub mod percussion_binding;
pub mod percussion_settings;
pub mod preset_def;
pub mod preset_definition_registry;
pub mod preset_type_id;
pub mod preset_type_registry;
pub mod project;
pub mod recording;
pub mod selection;
pub mod settings;
pub mod tempo;
pub mod timeline;
pub mod types;
pub mod units;
pub mod video;
pub use color::Color;
pub use effects::{EffectContainer, ParamSource};
pub use graph_target::GraphTarget;
pub use preset_type_id::PresetTypeId;
pub use id::{ClipId, EffectGroupId, EffectId, LayerId, MarkerId, NodeId};
pub use layer::OverlapAction;
pub use macro_bank::{
    MACRO_COUNT, MacroBank, MacroCurve, MacroMapping, MacroMappingTarget, MacroSlot,
};
pub use marker::TimelineMarker;
pub use math::{BeatQuantizer, MathUtils, short_id};
pub use selection::{SelectionRegion, SelectionRegionTarget};
pub use types::*;
pub use units::{Beats, Bpm, Seconds, beats_to_seconds, seconds_to_beats};
