use crate::node::*;
use crate::tree::UITree;

/// Pointer action type.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum PointerAction {
    Down,
    Up,
    Move,
}

/// Keyboard modifier flags.
///
/// `#[serde(default)]`: an `AutomationAction` script (`UI_AUTOMATION_DESIGN.md`
/// §4/§6) names a `Gesture::Click { modifiers }` far more often with no
/// modifiers held than with — every omitted field defaults to `false`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default, serde::Serialize, serde::Deserialize)]
#[serde(default)]
pub struct Modifiers {
    pub shift: bool,
    pub ctrl: bool,
    pub alt: bool,
    pub command: bool,
}

impl Modifiers {
    /// No modifiers held.
    pub const NONE: Self = Self {
        shift: false,
        ctrl: false,
        alt: false,
        command: false,
    };

    /// True when no modifier keys are pressed.
    /// Matches Unity's `ShortcutRegistry.WasPressed(kb, key, KeyModifiers.None)`.
    #[inline]
    pub fn is_none(self) -> bool {
        !self.shift && !self.ctrl && !self.alt && !self.command
    }

    /// True when EXACTLY Cmd/Super is held (no Shift, no Alt, no Ctrl).
    /// Matches Unity's `ShortcutRegistry.WasPressed(kb, key, KeyModifiers.Ctrl)`
    /// (Unity's "Ctrl" = macOS Cmd).
    #[inline]
    pub fn is_command_only(self) -> bool {
        self.command && !self.shift && !self.alt && !self.ctrl
    }

    /// True when EXACTLY Shift is held.
    #[inline]
    pub fn is_shift_only(self) -> bool {
        self.shift && !self.command && !self.alt && !self.ctrl
    }

    /// True when EXACTLY Alt is held.
    #[inline]
    pub fn is_alt_only(self) -> bool {
        self.alt && !self.command && !self.shift && !self.ctrl
    }

    /// True when EXACTLY Cmd+Shift are held.
    #[inline]
    pub fn is_command_shift(self) -> bool {
        self.command && self.shift && !self.alt && !self.ctrl
    }
}

/// Key identifier — subset of common keys used by the UI.
#[derive(Debug, Clone, Copy, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
pub enum Key {
    Space,
    Enter,
    Escape,
    Backspace,
    Delete,
    Tab,
    Left,
    Right,
    Up,
    Down,
    Home,
    End,
    // Letters
    A,
    B,
    C,
    D,
    E,
    F,
    G,
    H,
    I,
    J,
    K,
    L,
    M,
    N,
    O,
    P,
    Q,
    R,
    S,
    T,
    U,
    V,
    W,
    X,
    Y,
    Z,
    // Numbers
    Num0,
    Num1,
    Num2,
    Num3,
    Num4,
    Num5,
    Num6,
    Num7,
    Num8,
    Num9,
    // Function
    F1,
    F2,
    F3,
    F4,
    F5,
    F6,
    F7,
    F8,
    F9,
    F10,
    F11,
    F12,
    // Misc
    Minus,
    Plus,
    Period,
    Comma,
    Slash,
}

impl Key {
    /// The lowercase character this key types, for dropdown type-ahead matching.
    /// Letters → `'a'..='z'`, number row → `'0'..='9'`; non-printable keys → `None`.
    pub fn to_char(self) -> Option<char> {
        use Key::*;
        Some(match self {
            A => 'a', B => 'b', C => 'c', D => 'd', E => 'e', F => 'f', G => 'g',
            H => 'h', I => 'i', J => 'j', K => 'k', L => 'l', M => 'm', N => 'n',
            O => 'o', P => 'p', Q => 'q', R => 'r', S => 's', T => 't', U => 'u',
            V => 'v', W => 'w', X => 'x', Y => 'y', Z => 'z',
            Num0 => '0', Num1 => '1', Num2 => '2', Num3 => '3', Num4 => '4',
            Num5 => '5', Num6 => '6', Num7 => '7', Num8 => '8', Num9 => '9',
            _ => return None,
        })
    }
}

/// UI events generated by the input system.
#[derive(Debug, Clone)]
pub enum UIEvent {
    Click {
        node_id: NodeId,
        pos: Vec2,
        modifiers: Modifiers,
    },
    DoubleClick {
        node_id: NodeId,
        pos: Vec2,
        modifiers: Modifiers,
    },
    /// Right-click fires even on an empty hit (see [`UIInputSystem::process_right_click`]),
    /// so its node is optional: `None` is a miss that still carries `pos`.
    RightClick {
        node_id: Option<NodeId>,
        pos: Vec2,
        modifiers: Modifiers,
    },
    Scroll {
        pos: Vec2,
        delta: Vec2,
        modifiers: Modifiers,
    },
    PointerDown {
        node_id: NodeId,
        pos: Vec2,
        modifiers: Modifiers,
    },
    /// Terminal release event — fires on every mouse-up that followed a press,
    /// even when the pressed widget left the tree before release (a rebuild
    /// dropped it). `node_id` is best-effort context: `None` means "the press
    /// target is no longer in the build", not "no event". See
    /// [`UIInputSystem::process_pointer`].
    PointerUp {
        node_id: Option<NodeId>,
        pos: Vec2,
    },
    HoverEnter {
        node_id: NodeId,
        pos: Vec2,
    },
    HoverExit {
        node_id: NodeId,
    },
    /// `node_id` is best-effort context: the pressed
    /// widget resolved to a live node WHEN THIS EVENT WAS EMITTED, but the
    /// motion stream is emitted unconditionally — a `None` means the pressed
    /// widget left the tree before the drag threshold crossed, not "no
    /// event". See [`UIInputSystem::process_pointer`].
    DragBegin {
        node_id: Option<NodeId>,
        pos: Vec2,
        origin: Vec2,
        modifiers: Modifiers,
    },
    /// `node_id` is best-effort context, same contract as `DragBegin` (D9):
    /// `None` means the pressed widget is no longer in the build. Position is
    /// the payload every consumer should route on.
    Drag {
        node_id: Option<NodeId>,
        pos: Vec2,
        delta: Vec2,
    },
    /// Terminal drag event — fires for every drag that began, even when the
    /// pressed widget left the tree mid-drag. A drag that began MUST end: the
    /// consumer relies on this to tear down its drag state (overlay cursor,
    /// region select, scrub anchor). `node_id` is best-effort context — `None`
    /// means the originating node is gone, not that the drag didn't end. See
    /// [`UIInputSystem::process_pointer`].
    DragEnd {
        node_id: Option<NodeId>,
        pos: Vec2,
    },
    KeyDown {
        node_id: NodeId,
        key: Key,
        modifiers: Modifiers,
    },
}

impl UIEvent {
    /// Create a copy with all position fields offset by (dx, dy).
    /// Used to convert screen-space events to panel-local coordinates.
    pub fn with_offset(&self, dx: f32, dy: f32) -> Self {
        let off = |v: Vec2| Vec2::new(v.x + dx, v.y + dy);
        match self {
            Self::Click {
                node_id,
                pos,
                modifiers,
            } => Self::Click {
                node_id: *node_id,
                pos: off(*pos),
                modifiers: *modifiers,
            },
            Self::DoubleClick {
                node_id,
                pos,
                modifiers,
            } => Self::DoubleClick {
                node_id: *node_id,
                pos: off(*pos),
                modifiers: *modifiers,
            },
            Self::RightClick {
                node_id,
                pos,
                modifiers,
            } => Self::RightClick {
                node_id: *node_id,
                pos: off(*pos),
                modifiers: *modifiers,
            },
            Self::Scroll {
                pos,
                delta,
                modifiers,
            } => Self::Scroll {
                pos: off(*pos),
                delta: *delta,
                modifiers: *modifiers,
            },
            Self::PointerDown {
                node_id,
                pos,
                modifiers,
            } => Self::PointerDown {
                node_id: *node_id,
                pos: off(*pos),
                modifiers: *modifiers,
            },
            Self::PointerUp { node_id, pos } => Self::PointerUp {
                node_id: *node_id,
                pos: off(*pos),
            },
            Self::HoverEnter { node_id, pos } => Self::HoverEnter {
                node_id: *node_id,
                pos: off(*pos),
            },
            Self::HoverExit { node_id } => Self::HoverExit { node_id: *node_id },
            Self::DragBegin {
                node_id,
                pos,
                origin,
                modifiers,
            } => Self::DragBegin {
                node_id: *node_id,
                pos: off(*pos),
                origin: off(*origin),
                modifiers: *modifiers,
            },
            Self::Drag {
                node_id,
                pos,
                delta,
            } => Self::Drag {
                node_id: *node_id,
                pos: off(*pos),
                delta: *delta,
            },
            Self::DragEnd { node_id, pos } => Self::DragEnd {
                node_id: *node_id,
                pos: off(*pos),
            },
            Self::KeyDown {
                node_id,
                key,
                modifiers,
            } => Self::KeyDown {
                node_id: *node_id,
                key: *key,
                modifiers: *modifiers,
            },
        }
    }

    /// Extract the position from events that carry one, or None for position-less events.
    pub fn pos(&self) -> Option<Vec2> {
        match self {
            Self::Click { pos, .. } => Some(*pos),
            Self::DoubleClick { pos, .. } => Some(*pos),
            Self::RightClick { pos, .. } => Some(*pos),
            Self::Scroll { pos, .. } => Some(*pos),
            Self::PointerDown { pos, .. } => Some(*pos),
            Self::PointerUp { pos, .. } => Some(*pos),
            Self::HoverEnter { pos, .. } => Some(*pos),
            Self::DragBegin { pos, .. } => Some(*pos),
            Self::Drag { pos, .. } => Some(*pos),
            Self::DragEnd { pos, .. } => Some(*pos),
            Self::HoverExit { .. } | Self::KeyDown { .. } => None,
        }
    }
}

/// BUG-058 diagnostic tap — set `MANIFOLD_INPUT_TRACE=1` to print one line per
/// discrete pointer transition (press / release / drag begin / drag end) at each
/// seam of the drag pipeline: release received at the window, terminal events
/// emitted here, routed-or-eaten in `UIRoot::process_events`, drag ended in
/// `InteractionOverlay`. One live repro of a stuck drag then names the link
/// that broke. Discrete events only — never the per-frame Move/Drag stream.
/// Cached on first read; costs one branch on an initialized `OnceLock` after.
pub fn input_trace_enabled() -> bool {
    static ON: std::sync::OnceLock<bool> = std::sync::OnceLock::new();
    *ON.get_or_init(|| std::env::var_os("MANIFOLD_INPUT_TRACE").is_some_and(|v| v != "0"))
}

/// Processes pointer and keyboard input, dispatches UI events.
///
/// Maintains hover/press/focus state and manages:
/// - Click detection (up on same node as down, no drag)
/// - Double-click detection (0.3s window)
/// - Drag detection (4px threshold)
/// - Hover enter/exit tracking
pub struct UIInputSystem {
    // Interaction targets are tracked by durable WidgetId, NOT NodeId. A NodeId
    // captured at press goes stale the moment the tree is rebuilt (the editor
    // rebuilds every frame); a WidgetId names the same logical widget across
    // rebuilds. Each is resolved to a live NodeId only when an event is emitted or
    // a flag is set. This is what lets one input system serve both the
    // dirty-tracked timeline and the immediate-mode editor. See
    // `docs/INPUT_IDENTITY_UNIFICATION.md`.
    hovered_widget: Option<WidgetId>,
    pressed_widget: Option<WidgetId>,
    focused_widget: Option<WidgetId>,
    press_origin: Vec2,
    last_drag_pos: Vec2,
    is_dragging: bool,

    // D6 (`docs/DRAG_CAPTURE_DESIGN.md` §3.4): armed by `request_immediate_drag`
    // while routing the CURRENT press's `PointerDown`; makes the Move arm treat
    // the drag threshold as 0 for this press only. Cleared on `Up` alongside the
    // other per-press state — never carries over to the next gesture.
    immediate_drag_armed: bool,

    // Double-click detection (position-based, survives tree rebuilds)
    last_click_time: f32,
    last_click_pos: Vec2,

    // Current modifier state (set by app on ModifiersChanged)
    modifiers: Modifiers,

    // Event queue — polled each frame
    pending_events: Vec<UIEvent>,
}

const DRAG_THRESHOLD: f32 = crate::color::DRAG_THRESHOLD_PX;
const DOUBLE_CLICK_TIME: f32 = crate::color::DOUBLE_CLICK_TIME_SEC;

impl UIInputSystem {
    pub fn new() -> Self {
        Self {
            hovered_widget: None,
            pressed_widget: None,
            focused_widget: None,
            press_origin: Vec2::ZERO,
            last_drag_pos: Vec2::ZERO,
            is_dragging: false,
            immediate_drag_armed: false,
            last_click_time: 0.0,
            last_click_pos: Vec2::new(-100.0, -100.0),
            modifiers: Modifiers::default(),
            pending_events: Vec::new(),
        }
    }

    /// The durable identity of the hovered / pressed / focused widget (stable
    /// across rebuilds). Resolve to a live node with [`UITree::node_for_widget`]
    /// or the `*_node` helpers below.
    pub fn hovered_widget(&self) -> Option<WidgetId> {
        self.hovered_widget
    }
    pub fn pressed_widget(&self) -> Option<WidgetId> {
        self.pressed_widget
    }
    pub fn focused_widget(&self) -> Option<WidgetId> {
        self.focused_widget
    }

    /// The live [`NodeId`] currently carrying the hovered / pressed / focused
    /// widget in `tree`, if any. `None` once that widget leaves the build.
    pub fn hovered_node(&self, tree: &UITree) -> Option<NodeId> {
        self.hovered_widget.and_then(|w| tree.node_for_widget(w))
    }
    pub fn pressed_node(&self, tree: &UITree) -> Option<NodeId> {
        self.pressed_widget.and_then(|w| tree.node_for_widget(w))
    }
    pub fn focused_node(&self, tree: &UITree) -> Option<NodeId> {
        self.focused_widget.and_then(|w| tree.node_for_widget(w))
    }

    pub fn is_dragging(&self) -> bool {
        self.is_dragging
    }

    /// Arm zero-threshold drag for the CURRENT press only (cleared on Up).
    /// Call while routing the PointerDown of a precision surface (D6).
    pub fn request_immediate_drag(&mut self) {
        self.immediate_drag_armed = true;
    }

    /// Re-apply HOVERED / PRESSED flags to the live nodes carrying the currently
    /// hovered / pressed widgets. Call after a tree rebuild that clears node
    /// flags (the editor rebuilds every frame) so interaction visuals survive the
    /// rebuild instead of flickering off until the next pointer move. A no-op when
    /// the widgets no longer resolve.
    pub fn apply_interaction_flags(&self, tree: &mut UITree) {
        if let Some(n) = self.hovered_node(tree) {
            tree.set_flag(n, UIFlags::HOVERED);
        }
        if let Some(n) = self.pressed_node(tree) {
            tree.set_flag(n, UIFlags::PRESSED);
        }
    }

    /// Drain all pending events. Call this once per frame after processing input.
    pub fn drain_events(&mut self) -> Vec<UIEvent> {
        std::mem::take(&mut self.pending_events)
    }

    /// Peek at pending events without draining.
    pub fn pending_events(&self) -> &[UIEvent] {
        &self.pending_events
    }

    /// Reset cached hover state after a tree rebuild.
    /// Only clears hovered_id — pressed_id and is_dragging are preserved so
    /// an in-progress drag survives a tree rebuild (matches Unity IsDragging pin).
    pub fn invalidate_hover(&mut self) {
        self.hovered_widget = None;
        // Do NOT clear pressed_widget or is_dragging here.
    }

    /// Clear keyboard focus.
    pub fn clear_focus(&mut self) {
        self.focused_widget = None;
    }

    /// Update modifier state (called by app on ModifiersChanged).
    pub fn set_modifiers(&mut self, modifiers: Modifiers) {
        self.modifiers = modifiers;
    }

    /// Current modifier state.
    pub fn modifiers(&self) -> Modifiers {
        self.modifiers
    }

    /// Process a pointer event (down/move/up).
    /// `time` is the current time in seconds (for double-click detection).
    pub fn process_pointer(
        &mut self,
        tree: &mut UITree,
        screen_pos: Vec2,
        action: PointerAction,
        time: f32,
    ) {
        let hit_id = tree.hit_test(screen_pos);
        // The durable identity of whatever is under the cursor right now. hit_test
        // only returns interactive nodes, which are exactly the ones in the widget
        // map, so this is `Some(widget)` for any hit.
        let hit_widget = hit_id.map(|n| tree.widget_of(n));

        match action {
            PointerAction::Down => {
                if input_trace_enabled() {
                    eprintln!(
                        "[input-trace] input.rs DOWN ({:.0},{:.0}) hit={hit_widget:?}",
                        screen_pos.x, screen_pos.y
                    );
                }
                self.pressed_widget = hit_widget;
                self.press_origin = screen_pos;
                self.last_drag_pos = screen_pos;
                self.is_dragging = false;

                if let Some(uid) = hit_id {
                    tree.set_flag(uid, UIFlags::PRESSED);
                    self.focused_widget = hit_widget;
                    self.pending_events.push(UIEvent::PointerDown {
                        node_id: uid,
                        pos: screen_pos,
                        modifiers: self.modifiers,
                    });
                } else {
                    self.focused_widget = None;
                }
            }

            PointerAction::Move => {
                self.update_hover(tree, hit_id, screen_pos);

                if let Some(pw) = self.pressed_widget {
                    if !self.is_dragging {
                        let dist = screen_pos.distance(self.press_origin);
                        // D6: a precision surface armed zero-threshold drag for
                        // this press (`request_immediate_drag`) — the global
                        // `DRAG_THRESHOLD` constant is untouched; only this
                        // press's effective threshold drops to 0.
                        let threshold =
                            if self.immediate_drag_armed { 0.0 } else { DRAG_THRESHOLD };
                        if dist >= threshold {
                            self.is_dragging = true;
                            if input_trace_enabled() {
                                eprintln!(
                                    "[input-trace] input.rs DRAG-BEGIN origin=({:.0},{:.0}) \
                                     pressed={pw:?} resolves={}",
                                    self.press_origin.x,
                                    self.press_origin.y,
                                    tree.node_for_widget(pw).is_some()
                                );
                            }
                            // D9: emit unconditionally. The pressed widget's live
                            // node is best-effort context, not a delivery
                            // precondition — a rebuild between Down and the
                            // threshold crossing (e.g. a panel's own consume
                            // dirtying the overlay) must not silently swallow the
                            // whole motion stream (Peter's "first band-line click
                            // is always dead" trace, `docs/DRAG_CAPTURE_DESIGN.md`
                            // D9). Ownership routing decides delivery downstream,
                            // not node identity.
                            self.pending_events.push(UIEvent::DragBegin {
                                node_id: tree.node_for_widget(pw),
                                pos: screen_pos,
                                origin: self.press_origin,
                                modifiers: self.modifiers,
                            });
                        }
                    } else {
                        let delta = screen_pos - self.last_drag_pos;
                        self.last_drag_pos = screen_pos;
                        self.pending_events.push(UIEvent::Drag {
                            node_id: tree.node_for_widget(pw),
                            pos: screen_pos,
                            delta,
                        });
                    }
                }
            }

            PointerAction::Up => {
                if input_trace_enabled() {
                    eprintln!(
                        "[input-trace] input.rs UP ({:.0},{:.0}) pressed={:?} is_dragging={} \
                         (dragging ⇒ DragEnd+PointerUp emitted)",
                        screen_pos.x, screen_pos.y, self.pressed_widget, self.is_dragging
                    );
                }
                if let Some(pw) = self.pressed_widget {
                    // Clear PRESSED on whatever live node carries the pressed widget.
                    if let Some(n) = tree.node_for_widget(pw) {
                        tree.clear_flag(n, UIFlags::PRESSED);
                    }

                    if self.is_dragging {
                        // A drag that began MUST end. Emit DragEnd unconditionally
                        // — gating it on the pressed widget still resolving meant a
                        // rebuild that dropped the node mid-drag (clip drags
                        // invalidate the tracks bitmap every frame) silently ate the
                        // terminal event, leaving the consumer's drag state stuck
                        // forever (frozen Move cursor, un-finalized region select).
                        // The node id is best-effort context, same contract as
                        // RightClick's optional node.
                        self.pending_events.push(UIEvent::DragEnd {
                            node_id: tree.node_for_widget(pw),
                            pos: screen_pos,
                        });
                    } else if hit_widget == Some(pw)
                        && let Some(live) = hit_id
                    {
                        // A click is press+release on the same WIDGET. WidgetId is
                        // stable across rebuilds, so this holds even when the editor
                        // rebuilt the tree between press and release (where an exact
                        // NodeId compare always failed → no click ever fired inside
                        // the editor). `live` is the current node carrying that
                        // widget, so the emitted id matches the freshly-built panel
                        // nodes downstream.
                        self.pending_events.push(UIEvent::Click {
                            node_id: live,
                            pos: screen_pos,
                            modifiers: self.modifiers,
                        });

                        // Double-click detection — position-based (matches OS behavior).
                        if time - self.last_click_time < DOUBLE_CLICK_TIME
                            && screen_pos.distance(self.last_click_pos) < DRAG_THRESHOLD
                        {
                            self.pending_events.push(UIEvent::DoubleClick {
                                node_id: live,
                                pos: screen_pos,
                                modifiers: self.modifiers,
                            });
                            // Reset to prevent triple-click
                            self.last_click_time = 0.0;
                            self.last_click_pos = Vec2::new(-100.0, -100.0);
                        } else {
                            self.last_click_pos = screen_pos;
                            self.last_click_time = time;
                        }
                    }

                    // PointerUp always fires on release (its consumers — slider /
                    // scrub release — must clear their drag flags regardless of
                    // whether the pressed node survived). Best-effort node id.
                    self.pending_events.push(UIEvent::PointerUp {
                        node_id: tree.node_for_widget(pw),
                        pos: screen_pos,
                    });
                }
                self.pressed_widget = None;
                self.is_dragging = false;
                self.immediate_drag_armed = false;
            }
        }
    }

    /// Process a right-click at `pos`.
    ///
    /// Always emits a `RightClick` event, even when the hit test misses
    /// (`node_id == u32::MAX` sentinel). A miss carries no tree node but still
    /// carries `pos`, so position-based consumers (timeline overlay, canvas)
    /// and intent fold-up get their shot — historically a miss was dropped
    /// silently here, which is why right-click "sometimes" did nothing on any
    /// pixel not covered by an interactive node. See
    /// `docs/NODE_INTENT_DISPATCH.md`.
    pub fn process_right_click(&mut self, tree: &UITree, pos: Vec2) {
        let hit_id = tree.hit_test(pos);
        self.pending_events.push(UIEvent::RightClick {
            node_id: hit_id,
            pos,
            modifiers: self.modifiers,
        });
    }

    /// Process a scroll wheel event at `pos` with pixel `delta`.
    pub fn process_scroll(&mut self, pos: Vec2, delta: Vec2) {
        self.pending_events.push(UIEvent::Scroll {
            pos,
            delta,
            modifiers: self.modifiers,
        });
    }

    /// Process a key press on the currently focused node. `tree` resolves the
    /// focused widget to the live node carried in the `KeyDown` event.
    pub fn process_key(&mut self, tree: &UITree, key: Key, modifiers: Modifiers) {
        if let Some(node_id) = self.focused_node(tree) {
            self.pending_events.push(UIEvent::KeyDown {
                node_id,
                key,
                modifiers,
            });
        }
    }

    fn update_hover(&mut self, tree: &mut UITree, hit_id: Option<NodeId>, pos: Vec2) {
        let hit_widget = hit_id.map(|n| tree.widget_of(n));
        // Compare by durable identity, not NodeId. Pre-WidgetId this compared
        // stored-vs-fresh NodeId, so under the editor's per-frame rebuild the
        // stored id was always stale → hover "changed" every frame → a HoverExit +
        // HoverEnter pair fired every frame even with the cursor still. WidgetId is
        // stable, so a still cursor over the same widget is correctly a no-op.
        if hit_widget == self.hovered_widget {
            return;
        }

        // Clear the old hover on its current live node, if it is still in the build.
        if let Some(old_w) = self.hovered_widget
            && let Some(old_n) = tree.node_for_widget(old_w)
        {
            tree.clear_flag(old_n, UIFlags::HOVERED);
            self.pending_events
                .push(UIEvent::HoverExit { node_id: old_n });
        }

        self.hovered_widget = hit_widget;

        if let Some(new_n) = hit_id {
            tree.set_flag(new_n, UIFlags::HOVERED);
            self.pending_events.push(UIEvent::HoverEnter {
                node_id: new_n,
                pos,
            });
        }
    }
}

impl Default for UIInputSystem {
    fn default() -> Self {
        Self::new()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn setup() -> (UITree, UIInputSystem) {
        let mut tree = UITree::new();
        // Root panel
        let root = tree.add_panel(None, 0.0, 0.0, 800.0, 600.0, UIStyle::default());
        // Button at (50,50) size 100x30
        tree.add_button(Some(root), 50.0, 50.0, 100.0, 30.0, UIStyle::default(), "Click me");
        (tree, UIInputSystem::new())
    }

    #[test]
    fn click_detection() {
        let (mut tree, mut input) = setup();

        // Press on button
        input.process_pointer(&mut tree, Vec2::new(60.0, 60.0), PointerAction::Down, 0.0);
        // Release on same button
        input.process_pointer(&mut tree, Vec2::new(60.0, 60.0), PointerAction::Up, 0.0);

        let events = input.drain_events();
        let clicks: Vec<_> = events
            .iter()
            .filter(|e| matches!(e, UIEvent::Click { .. }))
            .collect();
        assert_eq!(clicks.len(), 1);
        if let UIEvent::Click { node_id, .. } = clicks[0] {
            assert_eq!(node_id.index(), 1); // button id
        }
    }

    /// Regression: a press+release must still register as a click when the tree
    /// is rebuilt from scratch between the two (the graph editor clears + rebuilds
    /// its UITree every frame, so the same node carries a fresh NodeId generation
    /// by release). Pre-fix, the `hit_id == pressed_id` exact-NodeId check failed
    /// across the generation bump and no click ever fired inside the editor.
    #[test]
    fn click_survives_tree_rebuild_between_press_and_release() {
        let (mut tree, mut input) = setup();

        // Press on the button (captures its current-generation id).
        input.process_pointer(&mut tree, Vec2::new(60.0, 60.0), PointerAction::Down, 0.0);

        // Rebuild the tree from scratch — same structure, fresh generations. The
        // button lands at the same index (1) but is a different NodeId now.
        tree.clear();
        let root = tree.add_panel(None, 0.0, 0.0, 800.0, 600.0, UIStyle::default());
        let button = tree.add_button(
            Some(root),
            50.0,
            50.0,
            100.0,
            30.0,
            UIStyle::default(),
            "Click me",
        );

        // Release over the same spot.
        input.process_pointer(&mut tree, Vec2::new(60.0, 60.0), PointerAction::Up, 0.0);

        let events = input.drain_events();
        let click = events
            .iter()
            .find_map(|e| match e {
                UIEvent::Click { node_id, .. } => Some(*node_id),
                _ => None,
            })
            .expect("a click must fire even though the tree was rebuilt mid-press");
        // The click must carry the LIVE (rebuilt) id, not the stale press id, so
        // downstream id-matching against the rebuilt panel still resolves.
        assert_eq!(click, button, "click must carry the live rebuilt node id");
        assert_ne!(
            tree.get_bounds(click),
            Rect::ZERO,
            "live id resolves in the rebuilt tree (a stale id would be inert → ZERO)"
        );
    }

    /// Rebuild the sample tree in place (same structure, fresh generations) —
    /// models the editor's per-frame clear+rebuild.
    fn rebuild(tree: &mut UITree) {
        tree.clear();
        let root = tree.add_panel(None, 0.0, 0.0, 800.0, 600.0, UIStyle::default());
        tree.add_button(Some(root), 50.0, 50.0, 100.0, 30.0, UIStyle::default(), "Click me");
    }

    /// Regression: a drag's events must keep flowing with a LIVE node id across a
    /// rebuild between press and move (editor-style). Pre-WidgetId, DragBegin/Drag
    /// carried the stale press id.
    #[test]
    fn drag_survives_tree_rebuild() {
        let (mut tree, mut input) = setup();
        input.process_pointer(&mut tree, Vec2::new(60.0, 60.0), PointerAction::Down, 0.0);
        rebuild(&mut tree);
        // Move past threshold after the rebuild.
        input.process_pointer(&mut tree, Vec2::new(70.0, 60.0), PointerAction::Move, 0.0);

        let begin = input
            .drain_events()
            .into_iter()
            .find_map(|e| match e {
                UIEvent::DragBegin { node_id, .. } => Some(node_id),
                _ => None,
            })
            .expect("DragBegin must fire after a rebuild")
            .expect("the rebuilt button is still live, so node_id must be Some");
        assert_ne!(
            tree.get_bounds(begin),
            Rect::ZERO,
            "DragBegin must carry the live rebuilt node id, not the stale press id"
        );
    }

    /// Regression: hovering still over the same widget must NOT churn events when
    /// the tree is rebuilt every frame. Pre-WidgetId the stored hover NodeId went
    /// stale each rebuild, so a HoverExit+HoverEnter pair fired every frame even
    /// with the cursor motionless — the "2 events/frame" the editor logs showed.
    #[test]
    fn hover_does_not_churn_across_rebuild() {
        let (mut tree, mut input) = setup();
        // Settle hover on the button.
        input.process_pointer(&mut tree, Vec2::new(60.0, 60.0), PointerAction::Move, 0.0);
        input.drain_events();

        // Rebuild, then a Move at the SAME position (cursor didn't really move).
        rebuild(&mut tree);
        input.process_pointer(&mut tree, Vec2::new(60.0, 60.0), PointerAction::Move, 0.0);

        let hover_events: Vec<_> = input
            .drain_events()
            .into_iter()
            .filter(|e| {
                matches!(e, UIEvent::HoverEnter { .. } | UIEvent::HoverExit { .. })
            })
            .collect();
        assert!(
            hover_events.is_empty(),
            "still cursor over the same widget must not churn hover across a rebuild, got {hover_events:?}"
        );
    }

    #[test]
    fn drag_detection() {
        let (mut tree, mut input) = setup();

        // Press
        input.process_pointer(&mut tree, Vec2::new(60.0, 60.0), PointerAction::Down, 0.0);
        // Move past drag threshold
        input.process_pointer(&mut tree, Vec2::new(70.0, 60.0), PointerAction::Move, 0.0);

        let events = input.drain_events();
        let drags: Vec<_> = events
            .iter()
            .filter(|e| matches!(e, UIEvent::DragBegin { .. }))
            .collect();
        assert_eq!(drags.len(), 1);

        // Continue dragging
        input.process_pointer(&mut tree, Vec2::new(80.0, 60.0), PointerAction::Move, 0.0);
        let events = input.drain_events();
        let drag_moves: Vec<_> = events
            .iter()
            .filter(|e| matches!(e, UIEvent::Drag { .. }))
            .collect();
        assert_eq!(drag_moves.len(), 1);

        // Release
        input.process_pointer(&mut tree, Vec2::new(80.0, 60.0), PointerAction::Up, 0.0);
        let events = input.drain_events();
        let drag_ends: Vec<_> = events
            .iter()
            .filter(|e| matches!(e, UIEvent::DragEnd { .. }))
            .collect();
        assert_eq!(drag_ends.len(), 1);

        // No click event after drag
        let clicks: Vec<_> = events
            .iter()
            .filter(|e| matches!(e, UIEvent::Click { .. }))
            .collect();
        assert_eq!(clicks.len(), 0);
    }

    /// P3 (D6, `docs/DRAG_CAPTURE_DESIGN.md` §3.4): a press that armed
    /// `request_immediate_drag` begins the drag on the very next Move, no
    /// matter how small — proving the effective per-press threshold really
    /// drops to 0, not just "lower". 1px is nowhere near the ordinary 4px
    /// `DRAG_THRESHOLD`, so this would fail without the override.
    #[test]
    fn request_immediate_drag_allows_one_pixel_move_to_begin_drag() {
        let (mut tree, mut input) = setup();

        input.process_pointer(&mut tree, Vec2::new(60.0, 60.0), PointerAction::Down, 0.0);
        input.request_immediate_drag();
        // 1px move — far under the ordinary 4px DRAG_THRESHOLD.
        input.process_pointer(&mut tree, Vec2::new(61.0, 60.0), PointerAction::Move, 0.01);

        let events = input.drain_events();
        let begins = events.iter().filter(|e| matches!(e, UIEvent::DragBegin { .. })).count();
        assert_eq!(begins, 1, "a 1px move must begin the drag once immediate-drag is armed");
        assert!(input.is_dragging());
    }

    /// P3 regression guard: a press that never calls `request_immediate_drag`
    /// keeps the ordinary 4px `DRAG_THRESHOLD` — a 3px wiggle before Up still
    /// resolves to a `Click`, never a `Drag`/`DragEnd`. Proves the global
    /// constant is untouched by D6's per-press override, and that the flag
    /// defaults off / doesn't leak from any prior press.
    #[test]
    fn three_pixel_wiggle_without_immediate_drag_still_resolves_to_click() {
        let (mut tree, mut input) = setup();

        input.process_pointer(&mut tree, Vec2::new(60.0, 60.0), PointerAction::Down, 0.0);
        // 3px wiggle — under the 4px threshold, no immediate-drag arm.
        input.process_pointer(&mut tree, Vec2::new(63.0, 60.0), PointerAction::Move, 0.01);
        assert!(!input.is_dragging(), "a 3px move must stay under DRAG_THRESHOLD_PX");

        input.process_pointer(&mut tree, Vec2::new(63.0, 60.0), PointerAction::Up, 0.02);
        let events = input.drain_events();
        assert_eq!(
            events.iter().filter(|e| matches!(e, UIEvent::Click { .. })).count(),
            1,
            "release without crossing the threshold must still resolve to a Click: {events:?}"
        );
        assert_eq!(
            events.iter().filter(|e| matches!(e, UIEvent::DragBegin { .. } | UIEvent::Drag { .. } | UIEvent::DragEnd { .. })).count(),
            0,
            "no drag event should fire for a sub-threshold wiggle: {events:?}"
        );
    }

    /// Regression: a drag whose pressed widget LEFT the tree before release must
    /// still emit its terminal `DragEnd` + `PointerUp`. Clip drags invalidate the
    /// tracks bitmap every frame, so the pressed node can fail to resolve at the
    /// exact moment of release; pre-fix the terminal events were gated on that
    /// resolution and silently dropped, orphaning the consumer's drag state
    /// (frozen Move cursor, un-finalized region select). The node id is `None`
    /// here — best-effort context, not a delivery precondition.
    #[test]
    fn drag_end_fires_even_when_pressed_widget_vanishes() {
        let (mut tree, mut input) = setup();

        // Press on the button, then drag past threshold (DragBegin).
        input.process_pointer(&mut tree, Vec2::new(60.0, 60.0), PointerAction::Down, 0.0);
        input.process_pointer(&mut tree, Vec2::new(80.0, 60.0), PointerAction::Move, 0.0);
        assert!(
            input
                .drain_events()
                .iter()
                .any(|e| matches!(e, UIEvent::DragBegin { .. })),
            "drag must have begun"
        );

        // Rebuild the tree WITHOUT the button — the pressed widget no longer
        // resolves to any live node (models a mid-drag tracks-bitmap rebuild
        // that dropped the node under the cursor).
        tree.clear();
        tree.add_panel(None, 0.0, 0.0, 800.0, 600.0, UIStyle::default());

        // Release. Both terminal events must still fire.
        input.process_pointer(&mut tree, Vec2::new(80.0, 60.0), PointerAction::Up, 0.0);
        let events = input.drain_events();

        let drag_end = events.iter().find(|e| matches!(e, UIEvent::DragEnd { .. }));
        assert!(
            matches!(drag_end, Some(UIEvent::DragEnd { node_id: None, .. })),
            "DragEnd must fire with a None node when the pressed widget vanished, got {events:?}"
        );
        assert!(
            events
                .iter()
                .any(|e| matches!(e, UIEvent::PointerUp { node_id: None, .. })),
            "PointerUp must also fire on release, got {events:?}"
        );

        // The producer's own drag state is torn down regardless.
        assert!(!input.is_dragging);
    }

    #[test]
    fn double_click_detection() {
        let (mut tree, mut input) = setup();

        // First click at t=0
        input.process_pointer(&mut tree, Vec2::new(60.0, 60.0), PointerAction::Down, 0.0);
        input.process_pointer(&mut tree, Vec2::new(60.0, 60.0), PointerAction::Up, 0.0);
        input.drain_events(); // clear

        // Second click at t=0.2 (within 0.3s window)
        input.process_pointer(&mut tree, Vec2::new(60.0, 60.0), PointerAction::Down, 0.2);
        input.process_pointer(&mut tree, Vec2::new(60.0, 60.0), PointerAction::Up, 0.2);

        let events = input.drain_events();
        let double_clicks: Vec<_> = events
            .iter()
            .filter(|e| matches!(e, UIEvent::DoubleClick { .. }))
            .collect();
        assert_eq!(double_clicks.len(), 1);
    }

    #[test]
    fn double_click_outside_window() {
        let (mut tree, mut input) = setup();

        // First click
        input.process_pointer(&mut tree, Vec2::new(60.0, 60.0), PointerAction::Down, 0.0);
        input.process_pointer(&mut tree, Vec2::new(60.0, 60.0), PointerAction::Up, 0.0);
        input.drain_events();

        // Second click at t=0.5 (outside 0.3s window)
        input.process_pointer(&mut tree, Vec2::new(60.0, 60.0), PointerAction::Down, 0.5);
        input.process_pointer(&mut tree, Vec2::new(60.0, 60.0), PointerAction::Up, 0.5);

        let events = input.drain_events();
        let double_clicks: Vec<_> = events
            .iter()
            .filter(|e| matches!(e, UIEvent::DoubleClick { .. }))
            .collect();
        assert_eq!(double_clicks.len(), 0);
    }

    #[test]
    fn hover_enter_exit() {
        let (mut tree, mut input) = setup();

        // Move onto button
        input.process_pointer(&mut tree, Vec2::new(60.0, 60.0), PointerAction::Move, 0.0);
        let events = input.drain_events();
        assert!(
            events
                .iter()
                .any(|e| matches!(e, UIEvent::HoverEnter { node_id, .. } if node_id.index() == 1))
        );

        // Move off button
        input.process_pointer(&mut tree, Vec2::new(200.0, 200.0), PointerAction::Move, 0.0);
        let events = input.drain_events();
        assert!(
            events
                .iter()
                .any(|e| matches!(e, UIEvent::HoverExit { node_id } if node_id.index() == 1))
        );
    }

    #[test]
    fn key_down_on_focused() {
        let (mut tree, mut input) = setup();

        // Click to focus
        input.process_pointer(&mut tree, Vec2::new(60.0, 60.0), PointerAction::Down, 0.0);
        input.process_pointer(&mut tree, Vec2::new(60.0, 60.0), PointerAction::Up, 0.0);
        input.drain_events();

        assert_eq!(input.focused_node(&tree).map(|n| n.index()), Some(1));

        // Send key
        input.process_key(&tree, Key::Space, Modifiers::default());
        let events = input.drain_events();
        assert_eq!(events.len(), 1);
        assert!(matches!(
            events[0],
            UIEvent::KeyDown {
                node_id,
                key: Key::Space,
                ..
            } if node_id.index() == 1
        ));
    }

    #[test]
    fn no_key_without_focus() {
        let (tree, mut input) = setup();

        input.process_key(&tree, Key::Space, Modifiers::default());
        let events = input.drain_events();
        assert!(events.is_empty());
    }

    #[test]
    fn right_click() {
        let (tree, mut input) = setup();

        input.process_right_click(&tree, Vec2::new(60.0, 60.0));
        let events = input.drain_events();
        assert_eq!(events.len(), 1);
        assert!(
            matches!(events[0], UIEvent::RightClick { node_id: Some(n), .. } if n.index() == 1)
        );
    }

    #[test]
    fn sub_threshold_move_is_not_drag() {
        let (mut tree, mut input) = setup();

        // Press
        input.process_pointer(&mut tree, Vec2::new(60.0, 60.0), PointerAction::Down, 0.0);
        // Move only 2px (below 4px threshold)
        input.process_pointer(&mut tree, Vec2::new(62.0, 60.0), PointerAction::Move, 0.0);
        // Release
        input.process_pointer(&mut tree, Vec2::new(62.0, 60.0), PointerAction::Up, 0.0);

        let events = input.drain_events();
        assert!(
            !events
                .iter()
                .any(|e| matches!(e, UIEvent::DragBegin { .. }))
        );
        // Should still fire a click since the button was pressed and released without drag
        // (hit_id at up may differ since pos changed slightly — both are on the button)
    }

    /// D9 repro (`docs/DRAG_CAPTURE_DESIGN.md`): Peter's live "first band-line
    /// click is always dead" trace, as a unit test. Press, then the pressed
    /// node dies (a rebuild dropped it) BEFORE the drag threshold crosses —
    /// pre-D9 this silently swallowed the entire motion stream (no DragBegin,
    /// no Drag, ever) because emission was gated on the pressed widget still
    /// resolving. Under D9 the stream is unconditional: DragBegin and Drag
    /// still arrive, with `node_id: None` and correct positions.
    #[test]
    fn d9_motion_stream_survives_pressed_node_dying_before_threshold() {
        let (mut tree, mut input) = setup();

        input.process_pointer(&mut tree, Vec2::new(60.0, 60.0), PointerAction::Down, 0.0);

        // The pressed widget dies before the threshold crosses (no button in
        // the rebuilt tree at all — models an overlay rebuild between Down
        // and the move that would cross DRAG_THRESHOLD).
        tree.clear();
        tree.add_panel(None, 0.0, 0.0, 800.0, 600.0, UIStyle::default());

        // Cross the threshold.
        input.process_pointer(&mut tree, Vec2::new(80.0, 60.0), PointerAction::Move, 0.0);
        let events = input.drain_events();
        let begin = events
            .iter()
            .find_map(|e| match e {
                UIEvent::DragBegin { node_id, pos, .. } => Some((*node_id, *pos)),
                _ => None,
            })
            .expect("DragBegin must still fire even though the pressed node died");
        assert_eq!(begin.0, None, "node_id must be None — the pressed node is gone");
        assert_eq!(begin.1, Vec2::new(80.0, 60.0), "position is still the real payload");

        // Continue the drag — Drag must keep flowing too, not just DragBegin.
        input.process_pointer(&mut tree, Vec2::new(90.0, 60.0), PointerAction::Move, 0.0);
        let events = input.drain_events();
        let moved = events
            .iter()
            .find_map(|e| match e {
                UIEvent::Drag { node_id, pos, .. } => Some((*node_id, *pos)),
                _ => None,
            })
            .expect("Drag must still fire for the rest of the gesture");
        assert_eq!(moved.0, None);
        assert_eq!(moved.1, Vec2::new(90.0, 60.0));
    }
}
