use crate::node::*;
use crate::tree::UITree;

/// Pointer action type.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum PointerAction {
    Down,
    Up,
    Move,
}

/// Keyboard modifier flags.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub struct Modifiers {
    pub shift: bool,
    pub ctrl: bool,
    pub alt: bool,
    pub command: bool,
}

impl Modifiers {
    /// No modifiers held.
    pub const NONE: Self = Self { shift: false, ctrl: false, alt: false, command: false };

    /// True when no modifier keys are pressed.
    /// Matches Unity's `ShortcutRegistry.WasPressed(kb, key, KeyModifiers.None)`.
    #[inline]
    pub fn is_none(self) -> bool {
        !self.shift && !self.ctrl && !self.alt && !self.command
    }

    /// True when EXACTLY Cmd/Super is held (no Shift, no Alt, no Ctrl).
    /// Matches Unity's `ShortcutRegistry.WasPressed(kb, key, KeyModifiers.Ctrl)`
    /// (Unity's "Ctrl" = macOS Cmd).
    #[inline]
    pub fn is_command_only(self) -> bool {
        self.command && !self.shift && !self.alt && !self.ctrl
    }

    /// True when EXACTLY Shift is held.
    #[inline]
    pub fn is_shift_only(self) -> bool {
        self.shift && !self.command && !self.alt && !self.ctrl
    }

    /// True when EXACTLY Alt is held.
    #[inline]
    pub fn is_alt_only(self) -> bool {
        self.alt && !self.command && !self.shift && !self.ctrl
    }

    /// True when EXACTLY Cmd+Shift are held.
    #[inline]
    pub fn is_command_shift(self) -> bool {
        self.command && self.shift && !self.alt && !self.ctrl
    }
}

/// Key identifier — subset of common keys used by the UI.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Key {
    Space,
    Enter,
    Escape,
    Backspace,
    Delete,
    Tab,
    Left,
    Right,
    Up,
    Down,
    Home,
    End,
    // Letters
    A, B, C, D, E, F, G, H, I, J, K, L, M,
    N, O, P, Q, R, S, T, U, V, W, X, Y, Z,
    // Numbers
    Num0, Num1, Num2, Num3, Num4, Num5, Num6, Num7, Num8, Num9,
    // Function
    F1, F2, F3, F4, F5, F6, F7, F8, F9, F10, F11, F12,
    // Misc
    Minus, Plus, Period, Comma, Slash,
}

/// UI events generated by the input system.
#[derive(Debug, Clone)]
pub enum UIEvent {
    Click { node_id: u32, pos: Vec2, modifiers: Modifiers },
    DoubleClick { node_id: u32, pos: Vec2, modifiers: Modifiers },
    RightClick { node_id: u32, pos: Vec2, modifiers: Modifiers },
    Scroll { pos: Vec2, delta: Vec2, modifiers: Modifiers },
    PointerDown { node_id: u32, pos: Vec2 },
    PointerUp { node_id: u32, pos: Vec2 },
    HoverEnter { node_id: u32, pos: Vec2 },
    HoverExit { node_id: u32 },
    DragBegin { node_id: u32, pos: Vec2, origin: Vec2, modifiers: Modifiers },
    Drag { node_id: u32, pos: Vec2, delta: Vec2 },
    DragEnd { node_id: u32, pos: Vec2 },
    KeyDown { node_id: u32, key: Key, modifiers: Modifiers },
}

/// Processes pointer and keyboard input, dispatches UI events.
///
/// Maintains hover/press/focus state and manages:
/// - Click detection (up on same node as down, no drag)
/// - Double-click detection (0.3s window)
/// - Drag detection (4px threshold)
/// - Hover enter/exit tracking
pub struct UIInputSystem {
    hovered_id: i32,
    pressed_id: i32,
    focused_id: i32,
    press_origin: Vec2,
    last_drag_pos: Vec2,
    is_dragging: bool,

    // Double-click detection
    last_click_time: f32,
    last_click_id: i32,

    // Current modifier state (set by app on ModifiersChanged)
    modifiers: Modifiers,

    // Event queue — polled each frame
    pending_events: Vec<UIEvent>,
}

const DRAG_THRESHOLD: f32 = crate::color::DRAG_THRESHOLD_PX;
const DOUBLE_CLICK_TIME: f32 = crate::color::DOUBLE_CLICK_TIME_SEC;

impl UIInputSystem {
    pub fn new() -> Self {
        Self {
            hovered_id: -1,
            pressed_id: -1,
            focused_id: -1,
            press_origin: Vec2::ZERO,
            last_drag_pos: Vec2::ZERO,
            is_dragging: false,
            last_click_time: 0.0,
            last_click_id: -1,
            modifiers: Modifiers::default(),
            pending_events: Vec::new(),
        }
    }

    pub fn hovered_id(&self) -> i32 {
        self.hovered_id
    }

    pub fn pressed_id(&self) -> i32 {
        self.pressed_id
    }

    pub fn focused_id(&self) -> i32 {
        self.focused_id
    }

    pub fn is_dragging(&self) -> bool {
        self.is_dragging
    }

    /// Drain all pending events. Call this once per frame after processing input.
    pub fn drain_events(&mut self) -> Vec<UIEvent> {
        std::mem::take(&mut self.pending_events)
    }

    /// Peek at pending events without draining.
    pub fn pending_events(&self) -> &[UIEvent] {
        &self.pending_events
    }

    /// Reset cached hover state after a tree rebuild.
    /// Only clears hovered_id — pressed_id and is_dragging are preserved so
    /// an in-progress drag survives a tree rebuild (matches Unity IsDragging pin).
    pub fn invalidate_hover(&mut self) {
        self.hovered_id = -1;
        // Do NOT clear pressed_id or is_dragging here.
    }

    /// Clear keyboard focus.
    pub fn clear_focus(&mut self) {
        self.focused_id = -1;
    }

    /// Update modifier state (called by app on ModifiersChanged).
    pub fn set_modifiers(&mut self, modifiers: Modifiers) {
        self.modifiers = modifiers;
    }

    /// Current modifier state.
    pub fn modifiers(&self) -> Modifiers {
        self.modifiers
    }

    /// Process a pointer event (down/move/up).
    /// `time` is the current time in seconds (for double-click detection).
    pub fn process_pointer(
        &mut self,
        tree: &mut UITree,
        screen_pos: Vec2,
        action: PointerAction,
        time: f32,
    ) {
        let hit_id = tree.hit_test(screen_pos);

        match action {
            PointerAction::Down => {
                self.pressed_id = hit_id;
                self.press_origin = screen_pos;
                self.last_drag_pos = screen_pos;
                self.is_dragging = false;

                if hit_id >= 0 {
                    let uid = hit_id as u32;
                    tree.set_flag(uid, UIFlags::PRESSED);
                    self.focused_id = hit_id;
                    self.pending_events.push(UIEvent::PointerDown {
                        node_id: uid,
                        pos: screen_pos,
                    });
                } else {
                    self.focused_id = -1;
                }
            }

            PointerAction::Move => {
                self.update_hover(tree, hit_id, screen_pos);

                if self.pressed_id >= 0 {
                    if !self.is_dragging {
                        let dist = screen_pos.distance(self.press_origin);
                        if dist >= DRAG_THRESHOLD {
                            self.is_dragging = true;
                            self.pending_events.push(UIEvent::DragBegin {
                                node_id: self.pressed_id as u32,
                                pos: screen_pos,
                                origin: self.press_origin,
                                modifiers: self.modifiers,
                            });
                        }
                    } else {
                        let delta = screen_pos - self.last_drag_pos;
                        self.last_drag_pos = screen_pos;
                        self.pending_events.push(UIEvent::Drag {
                            node_id: self.pressed_id as u32,
                            pos: screen_pos,
                            delta,
                        });
                    }
                }
            }

            PointerAction::Up => {
                if self.pressed_id >= 0 {
                    let uid = self.pressed_id as u32;
                    tree.clear_flag(uid, UIFlags::PRESSED);

                    if self.is_dragging {
                        self.pending_events.push(UIEvent::DragEnd {
                            node_id: uid,
                            pos: screen_pos,
                        });
                    } else if hit_id == self.pressed_id {
                        self.pending_events.push(UIEvent::Click {
                            node_id: uid,
                            pos: screen_pos,
                            modifiers: self.modifiers,
                        });

                        // Double-click detection
                        if hit_id == self.last_click_id
                            && time - self.last_click_time < DOUBLE_CLICK_TIME
                        {
                            self.pending_events.push(UIEvent::DoubleClick {
                                node_id: uid,
                                pos: screen_pos,
                                modifiers: self.modifiers,
                            });
                            self.last_click_id = -1; // prevent triple-click
                        } else {
                            self.last_click_id = hit_id;
                        }
                        self.last_click_time = time;
                    }

                    self.pending_events.push(UIEvent::PointerUp {
                        node_id: uid,
                        pos: screen_pos,
                    });
                }
                self.pressed_id = -1;
                self.is_dragging = false;
            }
        }
    }

    /// Process a right-click at `pos`.
    /// Always emits the event even if no interactive node is hit — panels
    /// use position-based routing to determine what was right-clicked.
    pub fn process_right_click(&mut self, tree: &UITree, pos: Vec2) {
        let hit_id = tree.hit_test(pos);
        self.pending_events.push(UIEvent::RightClick {
            node_id: if hit_id >= 0 { hit_id as u32 } else { u32::MAX },
            pos,
            modifiers: self.modifiers,
        });
    }

    /// Process a scroll wheel event at `pos` with pixel `delta`.
    pub fn process_scroll(&mut self, pos: Vec2, delta: Vec2) {
        self.pending_events.push(UIEvent::Scroll {
            pos,
            delta,
            modifiers: self.modifiers,
        });
    }

    /// Process a key press on the currently focused node.
    pub fn process_key(&mut self, key: Key, modifiers: Modifiers) {
        if self.focused_id >= 0 {
            self.pending_events.push(UIEvent::KeyDown {
                node_id: self.focused_id as u32,
                key,
                modifiers,
            });
        }
    }

    fn update_hover(&mut self, tree: &mut UITree, hit_id: i32, pos: Vec2) {
        if hit_id == self.hovered_id {
            return;
        }

        // Clear old hover (guard: id may be stale after tree rebuild)
        if self.hovered_id >= 0 && (self.hovered_id as usize) < tree.count() {
            let old_id = self.hovered_id as u32;
            tree.clear_flag(old_id, UIFlags::HOVERED);
            self.pending_events.push(UIEvent::HoverExit {
                node_id: old_id,
            });
        }

        self.hovered_id = hit_id;

        if self.hovered_id >= 0 && (self.hovered_id as usize) < tree.count() {
            let new_id = self.hovered_id as u32;
            tree.set_flag(new_id, UIFlags::HOVERED);
            self.pending_events.push(UIEvent::HoverEnter {
                node_id: new_id,
                pos,
            });
        } else {
            self.hovered_id = -1;
        }
    }
}

impl Default for UIInputSystem {
    fn default() -> Self {
        Self::new()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn setup() -> (UITree, UIInputSystem) {
        let mut tree = UITree::new();
        // Root panel
        tree.add_panel(-1, 0.0, 0.0, 800.0, 600.0, UIStyle::default());
        // Button at (50,50) size 100x30
        tree.add_button(0, 50.0, 50.0, 100.0, 30.0, UIStyle::default(), "Click me");
        (tree, UIInputSystem::new())
    }

    #[test]
    fn click_detection() {
        let (mut tree, mut input) = setup();

        // Press on button
        input.process_pointer(&mut tree, Vec2::new(60.0, 60.0), PointerAction::Down, 0.0);
        // Release on same button
        input.process_pointer(&mut tree, Vec2::new(60.0, 60.0), PointerAction::Up, 0.0);

        let events = input.drain_events();
        let clicks: Vec<_> = events
            .iter()
            .filter(|e| matches!(e, UIEvent::Click { .. }))
            .collect();
        assert_eq!(clicks.len(), 1);
        if let UIEvent::Click { node_id, .. } = clicks[0] {
            assert_eq!(*node_id, 1); // button id
        }
    }

    #[test]
    fn drag_detection() {
        let (mut tree, mut input) = setup();

        // Press
        input.process_pointer(&mut tree, Vec2::new(60.0, 60.0), PointerAction::Down, 0.0);
        // Move past drag threshold
        input.process_pointer(&mut tree, Vec2::new(70.0, 60.0), PointerAction::Move, 0.0);

        let events = input.drain_events();
        let drags: Vec<_> = events
            .iter()
            .filter(|e| matches!(e, UIEvent::DragBegin { .. }))
            .collect();
        assert_eq!(drags.len(), 1);

        // Continue dragging
        input.process_pointer(&mut tree, Vec2::new(80.0, 60.0), PointerAction::Move, 0.0);
        let events = input.drain_events();
        let drag_moves: Vec<_> = events
            .iter()
            .filter(|e| matches!(e, UIEvent::Drag { .. }))
            .collect();
        assert_eq!(drag_moves.len(), 1);

        // Release
        input.process_pointer(&mut tree, Vec2::new(80.0, 60.0), PointerAction::Up, 0.0);
        let events = input.drain_events();
        let drag_ends: Vec<_> = events
            .iter()
            .filter(|e| matches!(e, UIEvent::DragEnd { .. }))
            .collect();
        assert_eq!(drag_ends.len(), 1);

        // No click event after drag
        let clicks: Vec<_> = events
            .iter()
            .filter(|e| matches!(e, UIEvent::Click { .. }))
            .collect();
        assert_eq!(clicks.len(), 0);
    }

    #[test]
    fn double_click_detection() {
        let (mut tree, mut input) = setup();

        // First click at t=0
        input.process_pointer(&mut tree, Vec2::new(60.0, 60.0), PointerAction::Down, 0.0);
        input.process_pointer(&mut tree, Vec2::new(60.0, 60.0), PointerAction::Up, 0.0);
        input.drain_events(); // clear

        // Second click at t=0.2 (within 0.3s window)
        input.process_pointer(&mut tree, Vec2::new(60.0, 60.0), PointerAction::Down, 0.2);
        input.process_pointer(&mut tree, Vec2::new(60.0, 60.0), PointerAction::Up, 0.2);

        let events = input.drain_events();
        let double_clicks: Vec<_> = events
            .iter()
            .filter(|e| matches!(e, UIEvent::DoubleClick { .. }))
            .collect();
        assert_eq!(double_clicks.len(), 1);
    }

    #[test]
    fn double_click_outside_window() {
        let (mut tree, mut input) = setup();

        // First click
        input.process_pointer(&mut tree, Vec2::new(60.0, 60.0), PointerAction::Down, 0.0);
        input.process_pointer(&mut tree, Vec2::new(60.0, 60.0), PointerAction::Up, 0.0);
        input.drain_events();

        // Second click at t=0.5 (outside 0.3s window)
        input.process_pointer(&mut tree, Vec2::new(60.0, 60.0), PointerAction::Down, 0.5);
        input.process_pointer(&mut tree, Vec2::new(60.0, 60.0), PointerAction::Up, 0.5);

        let events = input.drain_events();
        let double_clicks: Vec<_> = events
            .iter()
            .filter(|e| matches!(e, UIEvent::DoubleClick { .. }))
            .collect();
        assert_eq!(double_clicks.len(), 0);
    }

    #[test]
    fn hover_enter_exit() {
        let (mut tree, mut input) = setup();

        // Move onto button
        input.process_pointer(&mut tree, Vec2::new(60.0, 60.0), PointerAction::Move, 0.0);
        let events = input.drain_events();
        assert!(events.iter().any(|e| matches!(e, UIEvent::HoverEnter { node_id: 1, .. })));

        // Move off button
        input.process_pointer(&mut tree, Vec2::new(200.0, 200.0), PointerAction::Move, 0.0);
        let events = input.drain_events();
        assert!(events.iter().any(|e| matches!(e, UIEvent::HoverExit { node_id: 1 })));
    }

    #[test]
    fn key_down_on_focused() {
        let (mut tree, mut input) = setup();

        // Click to focus
        input.process_pointer(&mut tree, Vec2::new(60.0, 60.0), PointerAction::Down, 0.0);
        input.process_pointer(&mut tree, Vec2::new(60.0, 60.0), PointerAction::Up, 0.0);
        input.drain_events();

        assert_eq!(input.focused_id(), 1);

        // Send key
        input.process_key(Key::Space, Modifiers::default());
        let events = input.drain_events();
        assert_eq!(events.len(), 1);
        assert!(matches!(
            events[0],
            UIEvent::KeyDown { node_id: 1, key: Key::Space, .. }
        ));
    }

    #[test]
    fn no_key_without_focus() {
        let (_tree, mut input) = setup();

        input.process_key(Key::Space, Modifiers::default());
        let events = input.drain_events();
        assert!(events.is_empty());
    }

    #[test]
    fn right_click() {
        let (tree, mut input) = setup();

        input.process_right_click(&tree, Vec2::new(60.0, 60.0));
        let events = input.drain_events();
        assert_eq!(events.len(), 1);
        assert!(matches!(events[0], UIEvent::RightClick { node_id: 1, .. }));
    }

    #[test]
    fn sub_threshold_move_is_not_drag() {
        let (mut tree, mut input) = setup();

        // Press
        input.process_pointer(&mut tree, Vec2::new(60.0, 60.0), PointerAction::Down, 0.0);
        // Move only 2px (below 4px threshold)
        input.process_pointer(&mut tree, Vec2::new(62.0, 60.0), PointerAction::Move, 0.0);
        // Release
        input.process_pointer(&mut tree, Vec2::new(62.0, 60.0), PointerAction::Up, 0.0);

        let events = input.drain_events();
        assert!(!events.iter().any(|e| matches!(e, UIEvent::DragBegin { .. })));
        // Should still fire a click since the button was pressed and released without drag
        // (hit_id at up may differ since pos changed slightly — both are on the button)
    }
}
