//! Bulk param tooltips — node-library coverage pass.
//!
//! Generated by a fan-out draft then voice-gated and reviewed. Same
//! `(type_id, param)` inventory channel as [`param_tooltips_table`]
//! (`crate::node_graph::param_doc`); kept in a separate file so the
//! hand-curated table stays small and this coverage pass is auditable in
//! one place. Voice rules identical: natural, no em-dashes or semicolons,
//! no AI-speak. See `feedback_product_copy_voice`.

// ─── Color & Tone ───

crate::param_tooltips!("node.brightness", {
    "weights" => "How much each of red, green, and blue counts toward the grey value. The defaults are the Rec.709 luma weights, which match how the eye sees brightness.",
});

crate::param_tooltips!("node.channel_mix", {
    "row0" => "How much red, green, blue, and alpha each feed into the new red channel. The default takes red straight through.",
    "row1" => "How much red, green, blue, and alpha each feed into the new green channel. The default takes green straight through.",
    "row2" => "How much red, green, blue, and alpha each feed into the new blue channel. The default takes blue straight through.",
    "row3" => "How much red, green, blue, and alpha each feed into the new alpha channel. The default takes alpha straight through.",
});

crate::param_tooltips!("node.color_lut", {
    "amount" => "Crossfades between the original image and the palette-mapped version. 0 leaves the source untouched and 1 is the full lookup.",
    "contrast" => "Pushes brightness around the midpoint before the lookup, which spreads the image across more of the palette. 1 leaves it unchanged, higher is punchier.",
});

crate::param_tooltips!("node.color_ramp", {
    "color_a" => "The colour mapped to the dark end of the image. Black areas pick up this colour.",
    "color_b" => "The colour mapped to the bright end of the image. White areas pick up this colour.",
});

crate::param_tooltips!("node.invert", {
    "intensity" => "How far to blend toward the inverted image, from 0 for the original up to 1 for the full negative. Values in between give a partial invert.",
});

crate::param_tooltips!("node.reinhard_tone_map", {
    "intensity" => "Brightens the image before the curve is applied, from 0 up to 16. 1 leaves it as is, higher pushes more of the picture toward the highlights.",
    "contrast" => "A second multiplier on the signal before tone mapping, from 0 to 8. 1 leaves it unchanged.",
    "curve" => "Which Reinhard curve to use. Extended keeps more detail in bright highlights, while Simple is the textbook version that crushes them harder.",
});

crate::param_tooltips!("node.saturation", {
    "saturation" => "How vivid the colours are. 0 is full greyscale, 1 leaves it unchanged, and above 1 oversaturates.",
});

crate::param_tooltips!("node.tone_map", {
    "exposure" => "Brightens or dims the image before the curve is applied. 1 leaves it unchanged, above 1 brightens, below 1 darkens.",
    "curve" => "How the bright highlights roll off. Narkowicz and Hill ACES are the filmic standards, AgX gives a more natural look, and Khronos PBR Neutral holds onto saturation in very bright colours.",
    "mode" => "What kind of display you are mapping to. SDR for a normal screen or export, PQ for HDR10 export, EDR for a macOS HDR display, and EDR Passthrough to skip the curve.",
    "paper_white" => "The brightness in nits that plain white should hit on an HDR display. Only used in the HDR output modes.",
    "max_nits" => "The peak brightness in nits your HDR display can reach, used to set where the brightest highlights land. Only used in the HDR output modes.",
});

// ─── Blur & Sharpen ───

crate::param_tooltips!("node.blur", {
    "radius" => "How far the blur reaches, in pixels. 0 leaves the image sharp and higher values soften it more.",
    "mode" => "The blur shape. Gaussian gives a smooth falloff, Box is a flat even spread, and Radial smears outward from the centre.",
});

crate::param_tooltips!("node.blur_3d_separable", {
    "mode" => "What kind of volume to blur. Scalar handles a density field that lives in one channel, Vector handles a force field across all four.",
    "axis" => "Which direction this pass blurs along, X, Y, or Z. Chain three instances, one per axis, for an even blur in all directions.",
    "vol_res" => "The grid size of the volume, default 128. It has to match the actual dimensions of the input and output volume or the blur reads the wrong cells.",
    "radius" => "How wide the blur reaches, in voxels. Higher values soften more and cost more. Wire it from a scalar to drive the width live.",
});

crate::param_tooltips!("node.convolution_2d_9tap", {
    "k0" => "The top-left weight of the 3x3 kernel. The nine weights read in reading order, top row first.",
    "k1" => "The top-centre weight of the 3x3 kernel.",
    "k2" => "The top-right weight of the 3x3 kernel.",
    "k3" => "The middle-left weight of the 3x3 kernel.",
    "k4" => "The centre weight of the 3x3 kernel, applied to the pixel itself. Defaults to 1 so an untouched node passes the image straight through.",
    "k5" => "The middle-right weight of the 3x3 kernel.",
    "k6" => "The bottom-left weight of the 3x3 kernel.",
    "k7" => "The bottom-centre weight of the 3x3 kernel.",
    "k8" => "The bottom-right weight of the 3x3 kernel.",
    "bias" => "A constant added to every pixel after the kernel runs. Useful for lifting emboss and edge-detect results out of black.",
    "normalise" => "Divides the result by the sum of the weights so brightness is preserved. Turn it on for blurs and off for sharpen or edge-detect kernels.",
});

crate::param_tooltips!("node.gaussian_blur_variable_width", {
    "axis" => "Which direction this pass blurs, Horizontal or Vertical. Run one of each in sequence for a full blur in both directions.",
    "max_radius" => "The widest the blur can reach at full strength, in pixels. The control image scales each pixel between sharp and this maximum.",
    "quality" => "How many samples the blur takes, Low, Medium, or High. Higher is smoother but slower, and Medium matches the original.",
    "weighting_mode" => "None is a plain blur. ScatterAsGatherByCoC stops sharp areas from bleeding into blurry ones, which is what depth of field needs.",
});

// ─── Distort & Warp ───

crate::param_tooltips!("node.affine_transform", {
    "translate_x" => "Slides the image sideways. Negative moves it left, positive moves it right, and the range runs from -1 to 1 across the frame.",
    "translate_y" => "Slides the image up and down. The range runs from -1 to 1 across the frame and 0 leaves it centred.",
    "scale" => "Zooms the image around its centre. 1 is original size, below 1 shrinks it, above 1 enlarges it.",
    "rotation" => "Spins the image around its centre in degrees. Positive turns it clockwise on screen and 0 leaves it level.",
});

crate::param_tooltips!("node.mirror_fold_uv", {
    "mode" => "Which fold to apply, from a simple Mirror or FlipY to a four-way QuadMirror or a FoldBoth kaleidoscope. This node outputs the folded coordinates, so send it into Remap to fold a picture.",
});

crate::param_tooltips!("node.radial_offset_field", {
    "mode" => "Which way the push points. Radial fans outward from the centre and fades toward the edge. Linear pushes everything the same way along the Angle you set.",
    "angle" => "The push direction for Linear mode, measured in degrees. Ignored in Radial mode.",
    "falloff" => "How much the radial push fades from centre to edge. 1 keeps the full centre-to-edge ramp, and 0 makes the push the same strength everywhere. Only matters in Radial mode.",
});

crate::param_tooltips!("node.remap", {
    "wrap" => "What happens when the map points outside the image. Clamp holds the edge pixel, Repeat tiles the image, and Mirror bounces it back.",
    "mode" => "How to read the coordinate map. Absolute treats it as the exact spot to sample, while Relative treats it as an offset added to each pixel's own position so displacement fields stack cleanly.",
});

crate::param_tooltips!("node.uv_strip_clamp", {
    "width" => "How wide the centre strip is before it gets smeared to the edges. Smaller values pin a thinner strip and stretch it further.",
    "direction" => "Which way to smear, with Horiz stretching the middle row outward, Vert the middle column, and Both at once.",
});

// ─── Stylize ───

crate::param_tooltips!("node.dither_pattern", {
    "algorithm" => "The threshold pattern used to decide where pixels flip. Choose from Bayer, Halftone, Lines, X-Hatch, Noise and Diamond.",
});

crate::param_tooltips!("node.edge_detect", {
    "amount" => "Crossfades the outline back over the source. 0 leaves the image untouched and 1 shows the bare edges on black.",
    "threshold" => "How strong an edge has to be before it draws. Raise it to keep only the boldest outlines and drop the fine texture.",
});

// ─── Generate ───

crate::param_tooltips!("node.gradient_ramp", {
    "stops" => "The list of colour stops that make up the gradient, each set at a position along the strip. Add as many as you need up to 16.",
    "domain" => "How far along the value range the strip covers. 1 is the normal range, and 2 reaches past the last stop to catch bright overshoots for a thermal look.",
});

crate::param_tooltips!("node.image_folder", {
    "folder" => "The folder of images to play through. Files are sorted alphabetically and laid out as a strip you scrub with the position knob.",
    "position" => "Where you are in the folder, from the first image at 0 to the last at 1. Drive it with an LFO to sweep through the sequence.",
    "uv_scale" => "Zooms into the current image. 1 fits it to frame and higher values crop in closer.",
    "next" => "Steps forward one image each time it fires. Wire a MIDI button or clip retrigger to it.",
    "prev" => "Steps back one image each time it fires. Wire a MIDI button or clip retrigger to it.",
});

crate::param_tooltips!("node.render_filled_rects", {
    "color" => "The colour of every rectangle drawn on top of the image.",
    "alpha" => "How opaque the rectangles are. The blend is additive so even at full alpha the rectangles add their colour to whatever is underneath rather than fully covering it.",
    "rect_count" => "How many rectangles from the list to draw. It is safe to leave high since empty zero size entries are skipped automatically.",
});

crate::param_tooltips!("node.render_lines", {
    "edge_thickness" => "How thick each line is drawn, as a fraction of the frame height. Around 0.002 is roughly one pixel at 1080p.",
    "closed_loop" => "Joins the last point back to the first so the path closes into a loop. Turn it off to leave an open strip.",
    "show_verts" => "Draws a dot at each point as well as the connecting lines.",
    "vert_size" => "How large the vertex dots are drawn, where 1 matches the classic generator size.",
    "animate" => "Reveals the lines as a scrolling window that travels along the path rather than drawing them all at once.",
    "speed" => "How fast the reveal window scrolls when Animate is on.",
    "window" => "The fraction of the path shown at once when Animate is on. Small values draw a short travelling segment, larger values show more of the line.",
    "beat_flash_amount" => "How hard the lines pulse brighter on each beat. Set it to 0 to hold a steady brightness.",
    "color_r" => "The red amount of the line colour. Values above 1 push into HDR for a brighter additive glow.",
    "color_g" => "The green amount of the line colour. Values above 1 push into HDR for a brighter additive glow.",
    "color_b" => "The blue amount of the line colour. Values above 1 push into HDR for a brighter additive glow.",
    "color_a" => "The opacity of the lines, from invisible at 0 to fully solid at 1.",
});

crate::param_tooltips!("node.render_text", {
    "size" => "The text height as a fraction of the frame, default 0.25 for about a quarter of the screen.",
    "pos_x" => "Moves the text left and right across the frame, from -1 at the left edge to 1 at the right, 0 is centred.",
    "pos_y" => "Moves the text up and down the frame, from -1 to 1, 0 is centred.",
    "scale" => "An extra size multiplier on top of the size setting. 1 leaves it as is, higher enlarges the text.",
    "h_align" => "How the lines line up sideways, Left, Center, or Right.",
    "v_align" => "How the block anchors vertically, Top, Center, or Bottom.",
    "letter_spacing" => "Extra gap between letters. 0 is the font's normal spacing, higher spreads them apart and negative packs them tighter.",
    "line_spacing" => "The gap between lines, default 1.2. Lower tightens the lines, higher opens them up.",
    "stroke_width" => "Outline thickness around the letters, as a fraction of the text size. 0 is no outline, higher draws a thicker border.",
    "fill_color" => "The colour of the letters themselves.",
    "stroke_color" => "The colour of the outline drawn around the letters when stroke width is above 0.",
    "text" => "The words to draw. Wire this through the card so you can change the message live during a show.",
    "fontFamily" => "The font to use by name. Leave it blank to fall back to the built-in default.",
});

crate::param_tooltips!("node.render_value_overlay", {
    "format" => "What the labels show. Index is the array number, Hex is a hex ID, Coord prints the X and Y position, and Float3 shows a wired value.",
    "color" => "The colour of the printed text.",
    "alpha" => "Overall opacity of the labels. 1 is solid and lower values fade them into the image.",
    "font_scale" => "Size of the text. 1 is the base size, raise it for bigger labels.",
    "label_count" => "The most labels to draw. Lower it to thin out a crowded readout.",
    "offset_x" => "Nudges every label sideways from its anchor point, in fractions of the frame width.",
    "offset_y" => "Nudges every label up or down from its anchor point, in fractions of the frame height.",
    "anchor" => "Which corner or centre of each region the label sits on, from Top Left through to Center.",
});

// ─── Noise ───

crate::param_tooltips!("node.flow_field_noise", {
    "z_scale" => "How fast the flow evolves over time. The default 0.01 drifts slowly, raise it for quicker swirling motion.",
    "warp_scale" => "How much the field folds back on itself for swirlier flow. 0 gives a plain direct field and higher values get more turbulent.",
    "resolution" => "What size to generate the field at. Full is sharpest, while half and quarter are 4x and 16x cheaper and upscale cleanly since the flow is low detail.",
});

crate::param_tooltips!("node.noise", {
    "type" => "Which kind of noise. Perlin and Simplex are both smooth and organic, with Simplex showing fewer grid-aligned streaks. Random is uncorrelated per-pixel grain for film and dither.",
    "scale" => "How zoomed in the noise pattern is. Low values give big soft blobs, higher values pack in finer detail.",
    "offset_x" => "Slides the noise field sideways. Wire an LFO in to drift or animate the pattern over time.",
    "offset_y" => "Slides the noise field up and down. Wire an LFO in to drift or animate the pattern over time.",
    "octaves" => "How many layers of finer noise stack on top of each other for fractal detail. 1 is a single smooth layer, raise it toward 8 for richer texture. Ignored when Type is Random.",
    "lacunarity" => "How much smaller each stacked layer gets than the one before. 2 is the classic setting. Only matters when Detail is above 1.",
    "persistence" => "How much quieter each stacked layer is than the one before. 0.5 gives the familiar natural look, lower makes the fine detail fainter. Only matters when Detail is above 1.",
});

crate::param_tooltips!("node.simplex_field_2d", {
    "scale_x" => "How many noise features fit across the width. Higher values make finer, busier horizontal detail.",
    "scale_y" => "How many noise features fit down the height. Higher values make finer, busier vertical detail.",
    "offset_x" => "Pans the noise sideways through the frozen field. Animate it for directional horizontal flow.",
    "offset_y" => "Pans the noise up and down through the frozen field. Animate it for directional vertical flow.",
    "z" => "Picks which slice of the noise to sample. Animate it over time for shimmer in place, and use a large gap between nodes for uncorrelated fields.",
    "output_channel" => "Which channel the noise is written to, with options R, G, B, and A. The signed value lands here and the other channels stay flat.",
});

// ─── Mask ───

crate::param_tooltips!("node.chroma_key", {
    "key_color" => "The colour to key on. Pixels close to this become the mask, the classic move is the green or blue of a screen behind your subject.",
    "tolerance" => "How far a pixel's colour can sit from the key and still count as a match. Higher pulls in a wider range, and above about 0.5 it starts grabbing most of the image.",
    "softness" => "Fades the edge of the mask. 0 gives a clean hard edge, higher values blur the transition between keyed and untouched.",
    "mode" => "Select outputs white where the colour matches, good for applying an effect to that colour. Reject flips it for a traditional green screen knockout.",
});

crate::param_tooltips!("node.ellipse_mask", {
    "cx" => "Horizontal centre of the circle across the frame, where 0 is the left edge and 1 is the right.",
    "cy" => "Vertical centre of the circle up the frame, where 0 is the bottom edge and 1 is the top.",
    "radius_x" => "Half the width of the shape. Make it different from Radius Y to stretch the circle into an oval. At 0 the shape collapses to a line along that axis.",
    "radius_y" => "Half the height of the shape. Make it different from Radius X to stretch the circle into an oval. At 0 the shape collapses to a line along that axis.",
    "rotation" => "Turns the oval around its centre, measured in degrees. Has no visible effect on a perfect circle.",
    "softness" => "Feathers the edge of the mask. 0 gives a clean hard edge, and higher values fade it out, measured in radius units so 1 spreads the falloff a full radius past the edge.",
});

crate::param_tooltips!("node.threshold", {
    "level" => "The brightness cutoff. Pixels brighter than this are kept and darker ones are dropped.",
    "softness" => "Fades the edge of the cutoff. 0 gives a hard line and higher values blend the keep and drop regions together.",
});

// ─── Composite ───

crate::param_tooltips!("node.hdr_retention_mix", {
    "retention" => "How much of the reference image's above-white highlights to keep. At 1 the bright detail stays anchored to the reference, and at 0 the compressed image passes through untouched.",
});

crate::param_tooltips!("node.masked_mix", {
    "amount" => "Scales the whole mask up or down so you can crossfade the effect in and out from one knob. At 0 the output is always A regardless of the mask.",
});

crate::param_tooltips!("node.texture_sum_5", {
    "divisor" => "Divides the summed result. 1 keeps it a plain sum, 5 turns the five inputs into an average. A divisor of 0 falls back to black.",
});

// ─── 3D Geometry ───

crate::param_tooltips!("node.array_replicate_polyline_rings", {
    "max_rings" => "The most copies this node will stack, from 1 up to 32. The actual count is whatever is smaller, this ceiling or the number of scales fed in.",
});

crate::param_tooltips!("node.camera_orbit", {
    "orbit" => "Swings the camera left and right around the target, in degrees. This is the horizontal angle of the orbit.",
    "tilt" => "Raises and lowers the camera over the target, in degrees. Positive looks down from above, negative looks up from below.",
    "distance" => "How far the camera sits from the target. Larger values pull back for a wider view, smaller values move in close.",
    "fov_y" => "The vertical field of view in degrees. Wider angles take in more of the scene and exaggerate perspective, narrower angles flatten it.",
    "look_y" => "Raises or lowers the point the camera looks at, shifting the whole framing up or down in the scene.",
    "roll" => "Tilts the camera sideways around its own view direction, in degrees, so the horizon leans. 0 keeps it level.",
    "near" => "Closest distance the camera can see. Anything nearer is clipped away. Leave it small unless the scene has extreme depth.",
    "far" => "Furthest distance the camera can see. Anything beyond is clipped away. Leave the default unless the scene is very deep.",
});

crate::param_tooltips!("node.consecutive_edges", {
    "count" => "How many points to connect in order. Wire it from a variable point source to grow or shrink the shape live.",
    "closed" => "When on, joins the last point back to the first to close the loop, giving a full polygon. Turn it off for an open line that leaves the ends apart.",
    "max_capacity" => "The most points this can ever connect, which sizes the buffer. Set it once to cover your largest shape and leave it alone.",
});

crate::param_tooltips!("node.cylinder_wrap_field", {
    "base_radius" => "How wide the cylinder is at its base. Larger values push the copies further out from the centre axis.",
    "height_scale" => "How tall the wrapped shape stands. Larger values stretch the copies further up and down the axis.",
    "taper" => "How sharply the radius narrows toward the top, giving cone and conifer shapes. 0 is a straight cylinder, higher makes a pointier top.",
    "instance_scale" => "Scales every copy placed on the surface. Feed the same value into a paired torus wrap so copies stay the same size across a morph.",
});

crate::param_tooltips!("node.digital_plants_render", {
    "instance_count" => "How many cubes to draw, counted from the start of the field. Drop it to thin out the look or lighten the load.",
    "light_x" => "Horizontal position of the light in the scene. Move it to swing the shadows side to side.",
    "light_y" => "Height of the light above the scene. Higher places it overhead for short shadows, lower for long raking ones.",
    "light_z" => "Depth position of the light, toward or away from the camera.",
    "light_intensity" => "Brightness of the light. 0 leaves the cubes in shadow, and higher values blow out the lit faces.",
});

crate::param_tooltips!("node.displace_mesh", {
    "cols" => "How many columns are in the source grid. This must match the grid the mesh came from or the height image will sample at the wrong spots.",
    "rows" => "How many rows are in the source grid. This must match the grid the mesh came from.",
    "displacement" => "How far the height image pushes each point up or down. 0 leaves the mesh flat, and negative values push the other way.",
    "height_bias" => "The grey level that counts as no movement, from 0 to 1. At the default 0.5, mid grey stays put while brighter pixels rise and darker ones sink.",
});

crate::param_tooltips!("node.edges_from_grid_uv", {
    "grid_size" => "How many points across each side of the grid. Drive this from the same value as the matching grid points node so the layout and the edges agree.",
});

crate::param_tooltips!("node.generate_cube_mesh", {
    "max_capacity" => "How much room to reserve in the vertex buffer, set when the effect is built. 36 holds exactly one cube, and larger values only help if a downstream node expects a bigger buffer.",
    "size" => "Scales the cube. 1 is the default unit cube, smaller shrinks it, larger grows it.",
});

crate::param_tooltips!("node.generate_grid_mesh", {
    "max_capacity" => "The most vertices the grid can ever hold. Set it once when building the effect since changing it rebuilds the graph, and keep it at or above resolution X times resolution Y.",
    "resolution_x" => "How many points across the grid. More points give finer detail at the cost of memory.",
    "resolution_y" => "How many points down the grid. More points give finer detail at the cost of memory.",
    "size_x" => "The width of the grid in world units.",
    "size_y" => "The depth of the grid in world units.",
});

crate::param_tooltips!("node.generate_grid_uv", {
    "grid_size" => "How many steps to sample along each axis, giving you that many points squared. Changing it rebuilds the chain, so set it while authoring rather than driving it live.",
    "u_max" => "The end of the U range that gets sampled. Defaults to a full turn, which is the right shape for closed surfaces like a torus, or set it to 1 for flat UV meshes.",
    "v_max" => "The end of the V range that gets sampled. Defaults to a full turn, or set it to 1 for flat UV meshes.",
});

crate::param_tooltips!("node.generate_instance_transforms", {
    "max_capacity" => "The largest number of copies this node can ever hold. It sets the memory allocation, so size it for your worst case and leave it.",
    "active_count" => "How many copies to actually place this frame, default 64. Slide it freely up to the max capacity to thin out or fill the field.",
    "layout" => "The pattern the copies fall into, Grid, Ring, Spiral, or Random.",
    "seed" => "Changes the random layout. Move it to get a different spread. Only matters when the layout is set to Random.",
    "extent_x" => "How far the layout reaches along X, default 4. Larger values spread the copies wider apart.",
    "extent_y" => "How far the layout reaches along Y, default 4. Larger values spread the copies wider apart.",
    "extent_z" => "How far the layout reaches along Z, default 4. Larger values spread the copies wider apart.",
    "base_scale" => "The size every copy starts at. 1 leaves the base mesh at its native size, higher grows them all together.",
    "rot_x" => "Tilts every copy around the X axis by the same amount, in degrees.",
    "rot_y" => "Spins every copy around the Y axis by the same amount, in degrees.",
    "rot_z" => "Rolls every copy around the Z axis by the same amount, in degrees.",
});

crate::param_tooltips!("node.nested_cubes_geometry", {
    "filter" => "How quickly the cubes ease toward their target rotation. Higher values snap faster, lower values glide more slowly.",
    "scale" => "Overall size of the cube field. 1 is the default framing, higher fills more of the frame.",
    "scatter" => "How far the faces break apart from each cube. 0 keeps the cubes solid, higher pulls the faces outward.",
    "decay_rate" => "How fast the rotation kick fades after each trigger, per second. Higher values make a quick snap, lower values let the kick linger.",
});

crate::param_tooltips!("node.pack_curve_xy", {
    "scale" => "Rescales the whole curve. At 1 it fills the inner half of the screen, and 4 cancels the built-in screen-fit so the X and Y values land at their raw screen-fractional size.",
});

crate::param_tooltips!("node.polytope_edges", {
    "shape" => "Which of the five Platonic solids to outline, from Tetra and Cube through to Icosa and Dodeca. Drive the matching points node from the same value so corners and edges agree.",
});

crate::param_tooltips!("node.polytope_vertices", {
    "shape" => "Which of the five Platonic solids to build, from Tetrahedron through Cube, Octahedron, Icosahedron, to Dodecahedron. Drive the same choice into the matching edges node so corners and lines agree.",
});

crate::param_tooltips!("node.project_3d", {
    "mode" => "How the 3D points flatten to 2D. Orthographic keeps a flat scale and ignores depth, while Perspective shrinks far points toward a vanishing point.",
    "proj_scale" => "How much the flattened shape is zoomed. Higher values fill more of the frame.",
    "proj_dist" => "The camera distance in Perspective mode. Closer distances exaggerate the depth foreshortening, farther ones flatten it out. Orthographic mode ignores it.",
});

crate::param_tooltips!("node.project_4d", {
    "proj_scale" => "How large the flattened shape comes out, default 0.25. Higher fills more of the frame.",
    "proj_dist" => "How far the 4D camera sits from the shape, default 3. Small values exaggerate the four-dimensional warp, large values flatten it out.",
});

crate::param_tooltips!("node.render_instanced_3d_mesh", {
    "instance_count" => "How many copies of the mesh to draw. It is capped to the size of the transform list you wire in.",
});

crate::param_tooltips!("node.rotate_3d", {
    "angle_x" => "Spin around the horizontal axis, in degrees. Wire an LFO or a beat in to keep it tumbling.",
    "angle_y" => "Spin around the vertical axis, in degrees.",
    "angle_z" => "Spin around the axis facing the camera, in degrees, which rolls the mesh in the plane of the screen.",
});

crate::param_tooltips!("node.rotate_4d", {
    "angle_xy" => "Rotation in the XY plane, in degrees. Wire it through time for a continuous tumble.",
    "angle_zw" => "Rotation in the ZW plane, in degrees. This plane reaches into the fourth dimension and is what makes a tesseract turn inside out.",
    "angle_xw" => "Rotation in the XW plane, in degrees. Combine it with the other two planes for a full 4D tumble.",
});

crate::param_tooltips!("node.torus_wrap_field", {
    "base_radius" => "The thickness of the tube, the fatness of the donut. Larger values make a chunkier ring.",
    "torus_radius" => "The overall radius of the ring from its centre to the middle of the tube. Larger values make a wider donut.",
    "fold_angle" => "Rotates the whole ring around its X axis, in degrees. Wire a time source here to keep it folding continuously.",
    "instance_scale" => "Scales every copy placed on the torus surface. When morphing between shapes, feed the same scale into the matching wrap node so the size stays continuous.",
});

// ─── Materials & Lighting ───

crate::param_tooltips!("node.bake_equirect_envmap", {
    "width" => "Width of the baked panorama in pixels. Keep it at twice the height for a correct equirect ratio, so 512 wide pairs with 256 tall.",
    "height" => "Height of the baked panorama in pixels. Keep it at half the width so the longitude and latitude mapping stays undistorted.",
    "horizon_strength" => "How bright the horizon band glows. 1 matches the default studio look, higher pushes a stronger rim of light into reflections.",
    "azimuth_variation" => "How much the lighting changes as you turn around the horizon. 0 is perfectly even, higher breaks up the ring so reflections shift with angle.",
});

crate::param_tooltips!("node.blinn_specular", {
    "light_x" => "The X part of the light direction, from -1 to 1. Wiring a Light into the light port overrides this and the other two direction knobs.",
    "light_y" => "The Y part of the light direction, from -1 to 1. The direction is normalised in the shader so only the ratio between X, Y, and Z matters.",
    "light_z" => "The Z part of the light direction, from -1 to 1. Default 0.75 points the light mostly toward the camera for a forward-facing highlight.",
    "view_x" => "The X part of the viewing direction, from -1 to 1. This is where the camera sits relative to the surface.",
    "view_y" => "The Y part of the viewing direction, from -1 to 1.",
    "view_z" => "The Z part of the viewing direction, from -1 to 1. Default 1 looks straight on, which puts the highlight where the light reflects back at the camera.",
    "power" => "How tight the highlight is. Higher values give a small pinpoint glint while lower values spread it into a broad sheen.",
    "color" => "The colour of the highlight. Alpha is ignored, and a wired light tints this further by multiplying its own colour in.",
});

crate::param_tooltips!("node.cel_material", {
    "color_r" => "The red amount of the base colour, from 0 to 1. This is the colour the bands are tinted before lighting snaps them into steps.",
    "color_g" => "The green amount of the base colour, from 0 to 1.",
    "color_b" => "The blue amount of the base colour, from 0 to 1.",
    "color_a" => "How opaque the material is, from 0 for see-through up to 1 for solid.",
    "cel_bands" => "How many flat lighting steps the surface snaps into. 2 gives a stark lit and shadow split, and higher counts toward 16 ease back into smooth shading.",
    "band_low" => "How dark the shadow side gets, as a fraction of full brightness. 0.08 leaves the shadows nearly black, higher lifts them.",
    "band_high" => "How bright the lit side gets, as a fraction of full brightness. 1 is full brightness on the lit face.",
    "emission_r" => "The red amount of light the surface gives off on its own, from 0 to 1, independent of any scene light.",
    "emission_g" => "The green amount of light the surface gives off on its own, from 0 to 1.",
    "emission_b" => "The blue amount of light the surface gives off on its own, from 0 to 1.",
    "emission_intensity" => "How strongly the emission colour glows, from 0 for off up to 10. Leave it at 0 unless you want the material to light itself.",
});

crate::param_tooltips!("node.fresnel_rim", {
    "view_x" => "The X part of the viewing direction the rim is measured against, from -1 to 1. The default looks straight down the Z axis at the surface.",
    "view_y" => "The Y part of the viewing direction the rim is measured against, from -1 to 1.",
    "view_z" => "The Z part of the viewing direction the rim is measured against, from -1 to 1. Default of 1 points the camera straight at the surface.",
    "power" => "How tight the glowing edge is, from 0.5 for a wide soft rim up to 16 for a thin sharp line right at the silhouette.",
    "color" => "The colour of the rim glow. This output is additive, so wire it onto your base shading with a Mix in Add mode.",
});

crate::param_tooltips!("node.heightmap_to_normal", {
    "z_scale" => "How pronounced the surface detail reads. Larger values flatten the bumps out, smaller values make them steeper and more dramatic.",
    "aspect" => "Scales the vertical slope so non-square frames keep the right shape. Leave it at 1 unless your canvas is stretched, then wire the frame aspect in.",
    "coord_space" => "Which normal convention to output. TangentZ suits flat screen-space shading, while WorldYUp suits a 3D mesh lying flat with Y pointing up.",
});

crate::param_tooltips!("node.lambert_directional", {
    "light_x" => "Horizontal direction the light comes from. Positive lights the surface from the right, negative from the left.",
    "light_y" => "Vertical direction the light comes from. Positive lights from above, negative from below.",
    "light_z" => "How much the light points straight out of the screen toward the surface. The direction is normalised so only the balance between the three axes matters.",
    "ambient" => "A flat fill that keeps the unlit side from going fully black. 0 gives hard shadows, higher values lift the whole surface toward flat.",
});

crate::param_tooltips!("node.light", {
    "mode" => "The kind of light. Sun throws parallel rays from far away like daylight, Point glows outward from a single spot in the scene.",
    "pos_x" => "Where the light sits along X, in world units. For a Sun this anchors the shadow frame rather than the brightness direction.",
    "pos_y" => "Where the light sits along Y, in world units, default 30 so it starts overhead.",
    "pos_z" => "Where the light sits along Z, in world units.",
    "aim_x" => "The X of the point the light looks at. For a Sun this sets the direction the rays travel, for a Point it aims the shadow.",
    "aim_y" => "The Y of the point the light looks at, setting which way it shines.",
    "aim_z" => "The Z of the point the light looks at, setting which way it shines.",
    "color_r" => "The red part of the light colour, from 0 to 1. The colour is multiplied by intensity before it reaches the surface.",
    "color_g" => "The green part of the light colour, from 0 to 1. The colour is multiplied by intensity before it reaches the surface.",
    "color_b" => "The blue part of the light colour, from 0 to 1. The colour is multiplied by intensity before it reaches the surface.",
    "intensity" => "How bright the light is, default 1. 0 turns it off, higher pushes more light onto the scene.",
    "range" => "How far the light reaches, default 30. For a Sun it sizes the shadow area, for a Point it is the distance where brightness halves. Set it to your scene scale.",
    "cast_shadows" => "Whether this light drops shadows. Above 0.5 turns them on, below skips the shadow pass entirely for speed.",
    "shadow_softness" => "How fuzzy the shadow edges are, Hard, Soft, or VerySoft. Softer edges look nicer but cost more to render.",
    "shadow_bias" => "Nudges the shadow off the surface to stop a surface shadowing itself, default 0.003. Raise it if you see speckled self-shadowing, lower it if shadows float away from contact points.",
    "shadow_resolution" => "The detail of the shadow map, default 2048. Higher gives sharper shadows on big scenes, lower runs faster. Rarely needs changing during a show.",
});

crate::param_tooltips!("node.matcap_two_tone", {
    "color_y_low" => "The shadow colour along the vertical axis, used where the surface faces down.",
    "color_y_high" => "The highlight colour along the vertical axis, used where the surface faces up.",
    "color_x_low" => "The colour along the left side of the surface. Set it equal to the right colour to drop the horizontal tint.",
    "color_x_high" => "The colour along the right side of the surface.",
});

crate::param_tooltips!("node.pbr_material", {
    "color_r" => "The red part of the base colour, from 0 to 1. On metal this also tints the reflections.",
    "color_g" => "The green part of the base colour, from 0 to 1. On metal this also tints the reflections.",
    "color_b" => "The blue part of the base colour, from 0 to 1. On metal this also tints the reflections.",
    "color_a" => "How opaque the surface is, from fully see-through at 0 to solid at 1.",
    "ambient" => "A flat fill light so shadowed faces are not pure black, default 0.05. Raise it to lift the darks, drop it for more contrast.",
    "metallic" => "How metal the surface reads. 0 is a dielectric like plastic or wood, 1 is bare metal like chrome or gold.",
    "roughness" => "How rough the surface is, default 0.5. Near 0 gives a sharp mirror finish, 1 is fully matte. It never reaches true zero to keep the highlight stable.",
    "emission_r" => "The red part of the colour the surface glows on its own, before intensity scales it.",
    "emission_g" => "The green part of the colour the surface glows on its own, before intensity scales it.",
    "emission_b" => "The blue part of the colour the surface glows on its own, before intensity scales it.",
    "emission_intensity" => "How strongly the surface glows on its own, default 0 for no glow. Raise it to make the material light up regardless of the scene lights.",
});

crate::param_tooltips!("node.phong_material", {
    "color_r" => "Red component of the surface colour, from 0 to 1.",
    "color_g" => "Green component of the surface colour, from 0 to 1.",
    "color_b" => "Blue component of the surface colour, from 0 to 1.",
    "color_a" => "How opaque the surface is. 1 is solid, lower values let what is behind show through.",
    "ambient" => "How lit the shadowed side stays. 0 leaves unlit faces fully dark for hard contrast, and higher values raise the floor so the whole object reads. Around 0.3 gives a half-lit look.",
    "specular_color_r" => "Red component of the highlight colour, from 0 to 1. Tint it to colour the shine.",
    "specular_color_g" => "Green component of the highlight colour, from 0 to 1. Tint it to colour the shine.",
    "specular_color_b" => "Blue component of the highlight colour, from 0 to 1. Tint it to colour the shine.",
    "specular_power" => "How tight the shiny highlight is. Around 1 is very soft and almost matte, 32 is a normal glossy spot, and 256 is a tiny pinpoint glint.",
    "emission_r" => "Red component of the glow colour the surface gives off on its own, from 0 to 1. Needs Emission Intensity above 0 to show.",
    "emission_g" => "Green component of the glow colour the surface gives off on its own, from 0 to 1. Needs Emission Intensity above 0 to show.",
    "emission_b" => "Blue component of the glow colour the surface gives off on its own, from 0 to 1. Needs Emission Intensity above 0 to show.",
    "emission_intensity" => "How brightly the surface glows on its own, independent of any light. 0 means no glow, and higher values make it self-lit.",
});

crate::param_tooltips!("node.unlit_material", {
    "color_r" => "The red amount of the flat base colour.",
    "color_g" => "The green amount of the flat base colour.",
    "color_b" => "The blue amount of the flat base colour.",
    "color_a" => "The opacity of the material, from clear at 0 to solid at 1. Note that v1 renders opaque only, so this is informational for now.",
    "emission_r" => "The red amount of the glow added on top of the base colour.",
    "emission_g" => "The green amount of the glow added on top of the base colour.",
    "emission_b" => "The blue amount of the glow added on top of the base colour.",
    "emission_intensity" => "How strongly the surface glows. At 0 there is no glow, and higher values push the emission colour brighter.",
});

// ─── Particles 2D ───

crate::param_tooltips!("node.anti_clump_particles", {
    "strength" => "How hard each particle gets nudged off its spot every frame. 0 leaves the cloud alone, and higher values spread it out faster. The useful range is small, so keep it low for a gentle drift.",
    "active_count" => "How many particles in the buffer get the kick. It is clamped to whatever the buffer can actually hold.",
});

crate::param_tooltips!("node.apply_radial_burst_to_particles", {
    "point_x" => "Horizontal centre of the burst across the canvas, from 0 at the left to 1 at the right. Wire it from a hit position to fire the shockwave wherever the action is.",
    "point_y" => "Vertical centre of the burst, from 0 at the bottom to 1 at the top.",
    "amplitude" => "How hard the push is. 0 means no burst at all, and higher values throw particles further out from the centre.",
    "envelope" => "Fades the burst in and out over the hit. Wire it from a decay envelope so the kick lands and settles instead of pushing forever.",
    "radius" => "How far from the centre the push reaches, as a fraction of the canvas. Particles past this radius barely feel it.",
    "active_count" => "How many particles to push, counted from the start of the buffer. Keep it matched to your live particle count so dead slots stay still.",
});

crate::param_tooltips!("node.array_diffuse_particles", {
    "diffusion" => "How hard the random kick hits each particle every frame. 0 leaves the cloud exactly as it is, and the useful range tops out around 0.05 before things scatter wildly.",
    "active_count" => "How many particles in the buffer actually get kicked, counted from the front. It is capped to the real buffer size so a value above the particle count just affects all of them.",
});

crate::param_tooltips!("node.fbm_per_instance", {
    "scale" => "How zoomed in the noise is. Higher values pack more detail into the same space so neighbouring copies vary more.",
    "z" => "Slides through the noise along a third axis. Animate this from time to make the value on each copy drift smoothly.",
    "offset_x" => "Shifts the noise sideways. Move it to pan the whole field or to reach a fresh patch of randomness.",
    "offset_y" => "Shifts the noise vertically. Move it to pan the field or sample a different part of the pattern.",
    "octaves" => "How many layers of detail to stack. More octaves add finer grain at the cost of more work, and 5 matches the classic fractal noise.",
    "lacunarity" => "How much finer each stacked layer gets. Larger values open the cells up and spread the detail apart.",
    "gain" => "How much each finer layer adds, from 0 to 1. Lower values keep the result smooth while higher values make it rougher and busier.",
});

crate::param_tooltips!("node.instance_position_jitter", {
    "frequency" => "How tightly the noise varies across the copies. Higher values make neighbouring copies wander in different directions, lower values move whole regions together.",
    "amplitude" => "How far each copy is pushed off its spot. 0 leaves the grid perfect, higher values scatter the copies further.",
    "time_uvx_drift" => "Slides the noise pattern along over time so the scatter animates. Drive it from a time wire for slow drift.",
    "z_coord" => "Picks which slice of the noise field to sample. Animate it from time to make the whole pattern evolve in place rather than slide.",
    "axis_seed" => "Separates the noise used for each axis so the three directions wobble independently. Move it to land in a different part of the noise.",
});

crate::param_tooltips!("node.instance_rotation_jitter", {
    "amplitude" => "How much random twist to add to each copy. 0 leaves every copy aligned, and higher values scatter their angles more. The twist is added on top of any rotation the copies already had.",
});

crate::param_tooltips!("node.lerp_instance_fields", {
    "t" => "How far to blend from the first arrangement toward the second. 0 is all the first, 1 is all the second, and 0.5 is the midway morph. Values outside that range overshoot.",
});

crate::param_tooltips!("node.radial_burst_force_field", {
    "point_x" => "Horizontal centre of the blast, from 0 at the left edge to 1 at the right.",
    "point_y" => "Vertical centre of the blast, from 0 at the top to 1 at the bottom.",
    "amplitude" => "How hard the burst pushes. At 0 the field is empty and the node costs nothing, raise it to throw particles harder.",
    "envelope" => "The current strength of the burst from 0 to 1, usually driven by a decay so the impulse fades after it fires. At 0 the field is empty.",
    "radius" => "How far the push reaches from the centre point, in fractions of the frame. The force falls off smoothly to nothing at the edge of this radius.",
    "time" => "Feeds the noise that breaks up the push so it looks organic rather than perfectly radial. Wire your time source in to keep it animating.",
});

crate::param_tooltips!("node.sample_texture_at_particles", {
    "active_count" => "How many particles to sample for, counted from the start of the list. Keep it matched to the particle count feeding the rest of the chain.",
});

crate::param_tooltips!("node.scatter_particles", {
    "active_count" => "How many particles to splat, counted from the start of the buffer. Match it to your live particle count so empty slots add nothing.",
    "scaled_energy" => "How much brightness each particle deposits where it lands. Higher values build the image up faster, so dense clouds bloom sooner.",
    "boundary" => "What happens to particles that land outside the canvas. Wrap tiles them back around so fluids flow without a seam, Discard drops them to avoid a hard edge when projecting from 3D.",
});

crate::param_tooltips!("node.seed_particles_from_texture", {
    "max_capacity" => "The most particles this node will ever hold, which sets the buffer size. Raise it only if you need more than the active count.",
    "active_count" => "How many particles to spawn this frame. Every one lands on a bright part of the image, wrapping round if there are more particles than bright pixels.",
    "output_width" => "The width of the space the image maps into, in pixels. Match it to your render size so the mask lands where you expect.",
    "output_height" => "The height of the space the image maps into, in pixels. Match it to your render size so the mask lands where you expect.",
    "frame_seed" => "Changes the random sub-pixel jitter on placement. Move it to reshuffle how particles sit within each bright pixel.",
});

crate::param_tooltips!("node.simplex_noise_force_at_particles", {
    "amplitude" => "How hard the noise field pushes each particle, from 0 for still up to 0.05. Small values already give plenty of swirl, so keep it low.",
    "modulator_gain" => "How much a wired modulator texture boosts the noise where it is bright, from 0 to 20. Only does anything when something is wired into the modulator input.",
    "z" => "Slides the noise field through its third dimension, which animates the flow. Wire time times a rate here to keep the turbulence moving.",
    "noise_scale" => "How zoomed in the noise pattern is, from 0 for huge soft swells up to 16 for fine busy detail.",
    "active_count" => "How many particles the noise force is applied to. Keep it matched to the particle count feeding the sim.",
});

crate::param_tooltips!("node.simplex_per_instance", {
    "scale" => "Frequency of the noise. Around 1 gives one broad swell across the field, higher values pack in fine grain.",
    "z" => "Slices through the noise at a different depth. Wire a time value in to make the field drift and animate.",
    "offset_x" => "Slides the noise field sideways. Wire an LFO in to scroll it across the copies.",
    "offset_y" => "Slides the noise field up and down.",
});

crate::param_tooltips!("node.wrap_particles_torus", {
    "active_count" => "How many particles get wrapped, counted from the front of the buffer. It is capped to the real particle count.",
});

// ─── Particles 3D ───

crate::param_tooltips!("node.apply_radial_burst_3d_to_particles", {
    "inject_index" => "Picks which of the four fixed burst zones to fire into, numbered 0 to 3. Set it to -1 to switch the burst off entirely.",
    "inject_force" => "How hard the burst pushes new material in, from 0 for nothing up to 1 for a full puff. Wire a trigger envelope here to fire it on a hit.",
    "inject_phase" => "Where the burst sits in its attack and decay envelope, from 0 to 1. Drive it from the same trigger that fires the burst so the push fades in and out.",
    "active_count" => "How many particles the burst is allowed to touch. Keep it matched to the particle count feeding the sim so the whole field reacts.",
});

crate::param_tooltips!("node.container_bounds_3d", {
    "container" => "The shape that holds the particles in. None wraps them around the edges, while Cube, Sphere, and Torus bounce them back inside the surface.",
    "ctr_scale" => "How big the container is inside the unit cube, from 0.2 to 1. Smaller values pull the walls in tighter. This has no effect when the container is set to None.",
    "active_count" => "How many particles from the front of the buffer to contain. Set this to match the live particle count so idle slots are left alone.",
});

crate::param_tooltips!("node.container_repel_force_3d", {
    "container" => "The shape of the wall particles get pushed away from. None turns the push off entirely, the rest pick a Cube, Sphere, or Torus boundary.",
    "ctr_scale" => "How big the container is. Smaller packs the particles into a tighter volume, larger gives them more room before the walls start pushing back.",
    "active_count" => "How many particles in the buffer feel the wall push, counted from the front. It is capped to the real particle count.",
});

crate::param_tooltips!("node.curl_slope_force_3d", {
    "vol_res" => "The width and height of the force volume in cells, default 128. Keep it matched to the gradient volume feeding in.",
    "vol_depth" => "The depth of the force volume in cells, default 128. Keep it matched to the gradient volume feeding in.",
    "curl_strength" => "How hard the swirl pulls particles into orbiting eddies. 0 is no swirl, higher spins them up. This is the dial that makes the flow read as smoke.",
    "slope_strength" => "How hard particles push along the gradient. Negative pulls them toward dense spots, positive pushes them away, default -500.",
    "ref_axis_x" => "The X part of the axis the swirl rotates around. The three axis values get normalised together, so feed raw sine and cosine without worrying about length.",
    "ref_axis_y" => "The Y part of the axis the swirl rotates around, default 1. The three axis values get normalised together before the swirl is built.",
    "ref_axis_z" => "The Z part of the axis the swirl rotates around. The three axis values get normalised together, so a length of zero falls back to straight up.",
});

crate::param_tooltips!("node.diffuse_force_3d_at_particles", {
    "diffusion" => "How strong a random kick each particle gets, from 0 for none up to 0.5. Higher spreads tight clumps apart faster, and the push is stronger where particles are densest.",
    "active_count" => "How many particles get the random kick. Keep it matched to the particle count feeding the sim.",
});

crate::param_tooltips!("node.euler_step_particles_3d", {
    "active_count" => "How many particles to move each frame, counted from the start of the buffer. Match it to your live particle count so dead slots stay put.",
    "speed" => "Scales how far every particle travels per step. 1 moves them at the force's natural pace, higher is faster. Wire an LFO or audio band in to drive the energy live.",
});

crate::param_tooltips!("node.flatten_to_camera_plane", {
    "flatten" => "How far to squash the particle cloud flat toward the camera. 0 leaves the full volume, 1 presses it into a sheet facing the screen.",
    "active_count" => "How many particles to process, capped at the buffer size. Match it to the live particle count from the rest of the chain.",
});

crate::param_tooltips!("node.sample_texture_3d_at_particles", {
    "active_count" => "How many particles read the volume this frame, capped to the size of the particle list. Entries beyond this count are left untouched.",
});

crate::param_tooltips!("node.scatter_particles_3d", {
    "active_count" => "How many particles from the front of the buffer to splat into the volume. Set this to match the live particle count.",
    "vol_res" => "The width and height of the volume grid in cells. Higher gives a finer density field at the cost of memory and speed.",
    "vol_depth" => "How many cells deep the volume grid is. Together with the resolution this sets how much detail the density field holds.",
    "scaled_energy" => "How much density each particle adds to its cell. The default 4096 reads back as roughly 1.0 in float density downstream.",
});

crate::param_tooltips!("node.scatter_particles_camera", {
    "active_count" => "How many particles get drawn, counted from the front of the buffer. It is capped to the real particle count.",
    "disp_w" => "Width of the image the particles splat onto, in pixels. Wire this from the canvas size so the splat matches your output resolution.",
    "disp_h" => "Height of the image the particles splat onto, in pixels. Wire this from the canvas size so the splat matches your output resolution.",
    "mode" => "Perspective gives true depth and hides particles behind the camera. Orthographic keeps everything flat and wraps the edges so the field tiles without a visible seam.",
    "scaled_energy" => "How much brightness each particle deposits where it lands. Higher makes a denser, more glowing splat.",
});

crate::param_tooltips!("node.simplex_noise_force_3d_at_particles", {
    "turbulence" => "How strongly the 3D noise pushes the particles around. 0 leaves them on their existing path, and higher values stir up more swirl. The useful range is small, so keep it low.",
    "anti_clump" => "How much extra push the noise adds where particles are already crowded, which spreads dense clumps apart. 0 turns the boost off, and higher values separate clusters more aggressively.",
    "active_count" => "How many particles the noise force is applied to. It is clamped to whatever the particle and force buffers can hold.",
});

// ─── Control ───

crate::param_tooltips!("node.canvas_area_scale", {
    "width" => "The canvas width in pixels. Wire this from the generator's output width so it tracks the real resolution.",
    "height" => "The canvas height in pixels. Wire this from the generator's output height so it tracks the real resolution.",
    "reference_area" => "The baseline pixel count the ratio is measured against. Default is 1920 by 1080. The output reads 1 at that size and rises as the canvas gets bigger. Set to 0 and it falls back to 1 so nothing breaks.",
    "min_width" => "Floors the input width before the area is worked out, so a tiny window does not dim the output below something usable. 0 means no floor. Set to 640 for FluidSim2D behaviour.",
    "min_height" => "Floors the input height before the area is worked out, so a tiny window does not dim the output below something usable. 0 means no floor. Set to 360 for FluidSim2D behaviour.",
});

crate::param_tooltips!("node.clip_trigger_cycle", {
    "modulus" => "How many values to cycle through, so the output lands in 0 up to this minus 1. Default 7 matches the fluid seed patterns. Set it to your own row count.",
});

crate::param_tooltips!("node.clip_trigger_index", {
    "modulus" => "How many slots to cycle through before wrapping back to the start. Set it to 3 for a three-way swap or 8 for an eight-step bank.",
});

crate::param_tooltips!("node.cycle_table_row", {
    "table" => "The built-in table of number rows it steps through. Each clip trigger advances to the next row and emits it.",
});

crate::param_tooltips!("node.trigger_gate", {
    "enable" => "Lets the trigger stream pass through while on. Triggers that arrive while it is off are dropped, so turning it back on does not replay the ones you missed.",
});

// ─── Detection & Sampling ───

crate::param_tooltips!("node.blob_detect_ffi", {
    "max_capacity" => "The most blobs this can track at once, up to 8. It is read once when the effect is built, so changing it live has no effect.",
    "threshold" => "The brightness cutoff for what counts as a blob. Lower picks up dimmer regions, higher only catches the brightest spots.",
    "sensitivity" => "How eagerly nearby bright regions get merged into one blob. Higher pulls neighbours together into bigger blobs, lower keeps them as separate smaller ones.",
    "analysis_max_dim" => "The longest side the image is shrunk to before detection runs, in pixels. Smaller is faster but loses small blobs, larger is slower but more precise.",
    "update_interval" => "How many frames to wait between detection passes. 1 runs every frame for the snappiest tracking, higher values save work but lag behind motion.",
});

crate::param_tooltips!("node.blob_overlay_render", {
    "color" => "The colour of the boxes drawn around each blob.",
    "alpha" => "How opaque the boxes are over the image. 0 is invisible and 1 is solid.",
    "border_width" => "Thickness of the box outline, in UV units where 0.003 is roughly 2 pixels at 720p. Push it past the blob size to get solid filled boxes instead of outlines.",
    "blob_count" => "The most blobs to draw boxes for, up to 32. It is safe to leave at 32 since entries with no size are skipped.",
});

crate::param_tooltips!("node.color_sample", {
    "uv" => "Where in the image to read the colour, as a point from 0 to 1 across width and height. The centre is 0.5, 0.5.",
    "radius_px" => "Averages a square window of this many pixels around the sample point. 0 reads a single pixel, higher values smooth out noise so the reading reflects the region.",
});

crate::param_tooltips!("node.depth_estimate_midas", {
    "analysis_max_dim" => "The longest side, in pixels, the frame is shrunk to before the AI looks at it. Lower runs faster but reads depth coarsely, higher is sharper but slower.",
    "update_interval" => "How many frames to wait between depth estimates. 1 runs every frame for the freshest result, higher values ease the CPU load but the depth lags the picture a little.",
});

crate::param_tooltips!("node.optical_flow_estimate", {
    "analysis_max_dim" => "The longest side the image is shrunk to before flow is measured, in pixels. Smaller is faster and softer while larger catches finer motion at more cost.",
    "update_interval" => "How many frames between each flow measurement. Higher values save work but the motion lags further behind the picture.",
});

crate::param_tooltips!("node.track_persist", {
    "match_radius" => "How far a blob can move between frames and still count as the same one, in normalised canvas units. Raise it for fast movers, lower it for crowded scenes where IDs swap.",
    "grace_frames" => "How many frames to keep holding a blob after it drops out, measured in frames. Raise it to ride through flickery detections, lower it to clear stale blobs fast.",
});

// ─── Math & Convert ───

crate::param_tooltips!("node.array_connect_nearest", {
    "max_distance" => "How close two items must be before a line connects them, in the input's own coordinate space which is 0 to 1 for blob detections. Lower values only link items that are nearly touching.",
    "max_edges" => "Caps how many connecting lines can be drawn. Once this many edges exist the rest are skipped, which keeps a busy scene from filling with lines.",
});

crate::param_tooltips!("node.array_math", {
    "op" => "The operation run over every number in the list. Binary ops like Add, Multiply, Min and Mix read both inputs, while unary ops like Sine, Abs and Clamp01 read only the first.",
    "scale" => "The multiplier used by ScaleOffset and ShapePowClip, and the blend amount for Mix. Other operations ignore it.",
    "offset" => "Added after scaling in ScaleOffset. Only that operation reads it.",
    "exp" => "The power applied in ShapePowClip, where 1 is linear and higher bends the response into a steeper curve. Only that operation reads it.",
    "bias" => "Shifts the input before the power in ShapePowClip. Only that operation reads it.",
});

crate::param_tooltips!("node.fract_texture", {
    "scale" => "Multiplies the input before keeping only the fractional part, which sets how many times the gradient repeats. 10 gives ten tiled stripes from 0 to 1.",
});

crate::param_tooltips!("node.generate_range", {
    "start" => "The first number in the list.",
    "end" => "The last number in the list, or just short of it when End Inclusive is off.",
    "max_capacity" => "How many evenly spaced numbers to produce between the start and end.",
    "end_inclusive" => "Whether the last value lands exactly on the end. On is right for closed curves that loop back, off is right for spacing points evenly around a circle.",
});

crate::param_tooltips!("node.pack_channels", {
    "default_r" => "The value the red channel falls back to when nothing is wired into the red input.",
    "default_g" => "The value the green channel falls back to when nothing is wired into the green input.",
    "default_b" => "The value the blue channel falls back to when nothing is wired into the blue input.",
    "default_a" => "The value the alpha channel falls back to when nothing is wired into the alpha input. Defaults to 1 so the result stays fully opaque.",
});

crate::param_tooltips!("node.power_texture", {
    "exponent" => "Raises each value to this power. Above 1 pushes the midtones toward black for sharper points, and below 1 lifts the darks like a gamma brighten. Negative input is clamped to 0 first.",
});

crate::param_tooltips!("node.resolve_3d_accumulator", {
    "vol_res" => "Width and height of the volume in cells. This must match the particle scatter that filled the buffer.",
    "vol_depth" => "Depth of the volume in cells. This must match the particle scatter that filled the buffer.",
});

crate::param_tooltips!("node.resolve_accumulator", {
    "fixed_point_scale" => "The divisor that turns the raw counter values back into density. It must match the scale the scatter step wrote with, default 4096, or the brightness comes out wrong.",
});

crate::param_tooltips!("node.scalar_array_accumulator", {
    "increment" => "How much is added to every slot on each trigger. Use 90 to step every value by a quarter turn per hit, negative to count down.",
    "capacity" => "How many slots the running list holds. Set it to match the number of values the downstream node expects.",
    "initial" => "The starting values for the slots, taken from the first row of a table. Left unset, every slot starts at zero.",
});

crate::param_tooltips!("node.scale_offset_texture", {
    "scale" => "Multiplies every colour before the offset is added. 1 leaves it unchanged, and a negative value inverts. Use 2 with offset -1 to turn a 0 to 1 field back into a signed -1 to 1 one.",
    "offset" => "Added to every colour after the scale. 0 leaves it unchanged. Use 0.5 with scale 0.5 to fit a signed -1 to 1 field into the 0 to 1 range.",
});

crate::param_tooltips!("node.trig_texture", {
    "freq" => "Scales the input before the wave is applied, setting how many cycles fit across the range. The default of about 6.28 fits one full cycle across a 0 to 1 input.",
    "phase" => "Shifts the wave along, in degrees, so you can slide the ripples or animate them by sweeping this value.",
    "mode" => "Picks the wave shape from Sin, Cos, or Tan. Sin and Cos stay in the minus one to one range, Tan is clamped to keep the output stable.",
});

// ─── Fields & Coordinates ───

crate::param_tooltips!("node.block_displace_field", {
    "amount" => "How far blocks slide and how many of them move. At 0 nothing shifts, and as you raise it the displacement grows from sparse to dense.",
    "block_size" => "The size of each block in pixels. Smaller blocks give a fine grain and larger blocks give chunky datamosh tearing.",
    "speed" => "How fast the random pattern reshuffles over time. Higher values churn the blocks more often.",
});

crate::param_tooltips!("node.centered_uv", {
    "cx" => "Horizontal point the coordinates measure from, where 0.5 is the middle of the canvas. Move it to slide a radial or zoom effect off centre.",
    "cy" => "Vertical point the coordinates measure from, where 0.5 is the middle of the canvas.",
    "scale_x" => "Stretches the horizontal coordinates. 1 leaves them as is, higher spreads the pattern wider, and a negative value flips it left to right.",
    "scale_y" => "Stretches the vertical coordinates. 1 leaves them as is, and a negative value flips it top to bottom.",
});

crate::param_tooltips!("node.field_combine", {
    "a" => "How much of the input's red channel feeds the output value. At 1 the red passes through, 0 ignores it, negative flips its sign.",
    "b" => "How much of the input's green channel feeds the output value. At 0 the green is ignored, higher mixes more of it in.",
    "c" => "A constant added to the result, useful for shifting the whole field up or down to centre it where you want.",
});

crate::param_tooltips!("node.gradient_central_diff", {
    "channel" => "Which colour channel the slope is measured from, R, G, B, or A. Use R for a greyscale height field.",
    "scale_mode" => "How the slope is scaled. Texel measures the raw pixel-to-pixel difference and suits normal maps and heightfields. UV scales by the image size so the result is in per-UV-unit space, which fluid-sim flow needs.",
    "wrap_mode" => "How edge pixels read their neighbours. Clamp holds the edge for normal images. Repeat wraps around to the far side, which you want for a tiling or cyclic fluid field.",
});

crate::param_tooltips!("node.gradient_central_diff_3d", {
    "vol_res" => "The width and height of the volume in voxels, from 16 to 512. Match it to the density volume you are feeding in.",
    "vol_depth" => "How many slices deep the volume is, from 16 to 512. Match it to the density volume you are feeding in.",
});

crate::param_tooltips!("node.grid_uv_field", {
    "grid_size" => "How many sample points across and down, so the total is this number squared. Changing it rebuilds the chain since it sets the buffer size.",
});

crate::param_tooltips!("node.hash_field_by_seed", {
    "seed" => "Picks which random layout you get. The same seed always gives the same result, so wire a beat or trigger here to reshuffle the pattern on cue.",
    "seed_x" => "How strongly the seed shifts the field along its first axis before hashing. Changing it gives a different family of random offsets.",
    "seed_y" => "How strongly the seed shifts the field along its second axis before hashing. Changing it gives a different family of random offsets.",
    "mode" => "Hash2 returns a random pair in the red and green channels, good for 2D offsets. Hash1 returns a single random value across red, green, and blue.",
});

crate::param_tooltips!("node.lic_integrate", {
    "steps" => "How many samples to walk along the flow in each direction. More steps draw longer smears, up to a limit of 64.",
    "dt" => "How far each step travels, in pixels. Steps times this sets the total streak length.",
});

crate::param_tooltips!("node.neighbor_smooth", {
    "grid_size" => "The width of the square grid the points are laid out on. This has to match the producer feeding it, since that is how each point finds its four neighbours.",
    "center_weight" => "How much each point keeps its own value versus averaging in its neighbours. 1 leaves it untouched and lower values smooth harder, with 0.2 being heavy smoothing.",
});

crate::param_tooltips!("node.polar_field", {
    "cx" => "The horizontal centre that angle and distance are measured from, where 0.5 is the middle of the frame.",
    "cy" => "The vertical centre that angle and distance are measured from, where 0.5 is the middle of the frame.",
});

crate::param_tooltips!("node.rotate_2d", {
    "angle" => "How far to spin the coordinate field around the centre, in degrees. A positive angle turns the +X direction toward +Y. This rotates the coordinates used for a warp, not the picture itself.",
});

crate::param_tooltips!("node.rotate_vec2_by_angle", {
    "angle" => "Turns every vector in the field by this amount, in degrees. The default 90 gives the perpendicular curl flow used for fluid sims.",
});

crate::param_tooltips!("node.sample_volume_2d", {
    "slice_z" => "How deep into the volume to cut the slice, from the front at 0 to the back at 1. Sweep it smoothly to animate through the volume.",
    "uv_scale" => "Zooms the slice into the output frame. 1 fills it normally, higher crops in tighter, lower pulls back.",
    "center_x" => "Shifts which part of the slice you see along X, from -1 to 1. Use it to pan across the volume when zoomed in.",
    "center_y" => "Shifts which part of the slice you see along Y, from -1 to 1. Use it to pan across the volume when zoomed in.",
});

crate::param_tooltips!("node.scanline_jitter_field", {
    "amount" => "How far the torn rows slide sideways and how many of them tear, from 0 for none up to 1. Feed the output into a Remap in Relative mode.",
    "scanline" => "How many rows tear at once, from 0 for a clean image up to 1 for heavy tearing across the frame.",
    "speed" => "How fast the tearing pattern reshuffles over time, from 0.1 for a slow drift up to 10 for a fast jitter.",
});

crate::param_tooltips!("node.sin_term", {
    "a" => "How much the field's red channel feeds the wave, usually the X coordinate. Set a and b together to aim the wave along X, Y, or a diagonal.",
    "b" => "How much the field's green channel feeds the wave, usually the Y coordinate. Leave it at 0 to read only the red channel from a scalar field.",
    "c" => "A constant added to the projection before the wave, which shifts its phase.",
    "freq" => "The base frequency of the wave, so higher values pack more cycles into the same space. Wire one shared value into every term to keep them in phase.",
    "freq_scale" => "A per-term multiplier on the base frequency. Give each term a different scale to layer waves at related rates.",
    "time" => "The base time that moves the wave along. Wire the generator time in so every term advances together.",
    "time_scale" => "A per-term multiplier on time, which sets how fast this wave drifts. Negative values send it the other way.",
});

crate::param_tooltips!("node.slope_displace", {
    "strength" => "How much the embossed base layer drives the displacement. Higher pushes pixels further along the contrast contours for a more liquid pull.",
    "step" => "How far apart the gradient is sampled, in pixels. Larger reads a broader slope for a softer, wider warp.",
    "weight" => "Scales the final pixel shift, measured in UV units. The default is tiny on purpose since even small values move pixels noticeably.",
});

crate::param_tooltips!("node.texture_advect", {
    "dt" => "How far the flow drags the image each frame, in pixels, default 1. Negative runs the flow backwards for trail-erase tricks. Wire it to an LFO to pulse the motion.",
    "boundary" => "What happens at the edges, Repeat for looping fluid sims or Clamp to fade off-frame samples into the edge colour.",
});

crate::param_tooltips!("node.uv_displace_by_flow", {
    "weight" => "How far the flow field pushes the image, default 0.001 which is about one pixel at 1080p. Higher smears it more, negative pushes the other way.",
    "bias" => "The neutral midpoint of the flow channels, default 0.5 for standard 0 to 1 flow. Set it to 0 when the flow data is already signed around zero.",
});
