mod camera_conformance;
mod render_scene_exposure;
mod render_scene_fog;
mod render_scene_glass;
mod render_scene_ibl;
mod render_scene_instances;
mod render_scene_lights;
mod render_scene_object_visibility;
mod render_scene_pcss;
mod render_scene_punctual_fidelity;
mod render_scene_shadows;
mod render_scene_uv1_preservation;
mod rt_6caster_shadow;
mod rt_bug17r3_lightless_gi;
mod rt_bug88m_blend_specular_gate;
mod rt_dynamic_fusion;
#[cfg(feature = "rt-perf-proofs")]
mod rt_dynamic_perf;
mod rt_edc_enclosure;
mod rt_emissive_direct;
mod rt_furnace_oracle;
mod rt_instancing;
mod rt_multi_caster_shadow;
mod rt_object_cast_shadows;
mod rt_p1_region_probe;
mod rt_p1_shadow;
mod rt_p3_emissive_gi;
mod rt_p4_metalfx_temporal;
mod rt_r1_reflection;
mod rt_r3_textured_roughness;
mod rt_t2a_alpha_mask;
mod rt_t2b_temporal_wiring;
mod rt_t2c_shadow_temporal_stability;
mod rt_tl_b_transmission;
mod rt_tl_c_sun_tint;
mod scene_viewport_navigate;

use manifold_nodes_scene as _;
