#!/usr/bin/env python3
"""Generate docs/README.md — an index of the active docs/ set.

Scans docs/*.md (top level only; docs/archive/ is the historical bin and is
not indexed), pulls each doc's title and a one-line summary, and writes a
sorted table to docs/README.md.

Do not hand-edit docs/README.md. Run this script to refresh it. A drift-guard
test (crates/manifold-core/tests/docs_index_sync.rs) fails the suite if the
committed index falls out of structural sync with docs/.

Usage: python3 scripts/gen_docs_index.py
"""
from __future__ import annotations
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
DOCS = REPO / "docs"
OUT = DOCS / "README.md"

# Lines that are not a real description — status banners, dated update notes,
# metadata keys, "if you're picking this up cold", etc. Skip these when hunting
# for a summary. A doc can override all of this with an `<!-- index: ... -->`
# marker, which is always preferred.
SKIP_PREFIXES = (
    "status", "update", "historical", "⚠", "if you're", "if you are",
    "author", "authored", "scope ", "working doc", "landed", "seams,",
    "last updated", "branch:", "owner:", "established", "companion docs",
    "estimated", "related:", "see ",
)

MARKER_RE = re.compile(r"<!--\s*index:\s*(.+?)\s*-->", re.IGNORECASE | re.DOTALL)


def clean(text: str) -> str:
    """Strip markdown noise from a candidate summary line."""
    text = text.strip()
    text = re.sub(r"^>+\s*", "", text)            # blockquote markers
    text = re.sub(r"^\*\*|\*\*$", "", text)       # bold wrapping
    text = re.sub(r"\[([^\]]+)\]\([^)]+\)", r"\1", text)  # links -> link text
    text = re.sub(r"[`*]", "", text)              # stray code/emphasis ticks
    text = re.sub(r"\s+", " ", text).strip()
    return text


def title_for(lines: list[str], stem: str) -> str:
    for ln in lines:
        if ln.startswith("# "):
            return clean(ln[2:])
    # No H1 — try a frontmatter `name:` value, else the filename stem.
    for ln in lines[:10]:
        m = re.match(r"\s*name:\s*(.+)", ln)
        if m:
            return clean(m.group(1))
    return stem


def summary_for(text: str, lines: list[str]) -> str:
    # An explicit `<!-- index: ... -->` marker always wins.
    m = MARKER_RE.search(text)
    if m:
        return clean(m.group(1))

    seen_title = False
    for ln in lines:
        if ln.startswith("# "):
            seen_title = True
            continue
        if not seen_title:
            continue
        raw = ln.strip()
        if raw.startswith("|") or raw == "---" or raw.startswith("```"):
            continue  # table row, frontmatter rule, code fence
        c = clean(ln)
        if not c or c.startswith("#") or len(c) < 25:
            continue
        if c.lower().startswith(SKIP_PREFIXES):
            continue
        # Truncate to a readable hook at a word boundary.
        if len(c) > 140:
            c = c[:140].rsplit(" ", 1)[0] + "…"
        return c
    return "(no summary — add an <!-- index: ... --> marker)"


def main() -> int:
    docs = sorted(p for p in DOCS.glob("*.md") if p.name != "README.md")
    rows = []
    for p in docs:
        text = p.read_text(encoding="utf-8")
        lines = text.splitlines()
        stem = p.stem
        rows.append((stem, title_for(lines, stem), summary_for(text, lines)))

    out = []
    out.append("# MANIFOLD — docs index")
    out.append("")
    out.append(
        "_Generated by `scripts/gen_docs_index.py` — do not hand-edit. "
        "Run the script to refresh. A drift-guard test "
        "(`crates/manifold-core/tests/docs_index_sync.rs`) fails the suite if "
        "this falls out of sync with `docs/`. Closed and historical docs live "
        "in [`archive/`](archive/)._"
    )
    out.append("")
    out.append(f"{len(rows)} active docs.")
    out.append("")
    out.append("| Doc | What it covers |")
    out.append("|---|---|")
    for stem, title, summary in rows:
        out.append(f"| [{title}]({stem}.md) | {summary} |")
    out.append("")

    OUT.write_text("\n".join(out), encoding="utf-8")
    print(f"Wrote {OUT.relative_to(REPO)} — {len(rows)} docs indexed.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
