#!/usr/bin/env python3
"""Regenerate docs/GLB_CONFORMANCE_STATUS.md from
tests/fixtures/gltf/khronos/manifest.json — the GLB_CONFORMANCE_DESIGN.md
G-P7 certification record (asset x status x gap). Pure formatting: this
script asserts nothing about renderability, it only reflects what the
manifest already says. Re-run after any manifest classification change.

Run: python3 scripts/gen_glb_conformance_status.py
"""
import json
import os

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MANIFEST = os.path.join(REPO_ROOT, "tests/fixtures/gltf/khronos/manifest.json")
OUT = os.path.join(REPO_ROOT, "docs/GLB_CONFORMANCE_STATUS.md")

# Gap descriptions for each xfail reason tag, kept in sync by hand with
# docs/GLB_CONFORMANCE_DESIGN.md §7 (Deferred) and docs/BUG_BACKLOG.md.
GAP_TEXT = {
    "deferred-3": "unsupported material extension (sheen / iridescence / "
                   "volume / transmission-family / anisotropy-the-extension) "
                   "— GLB_CONFORMANCE_DESIGN.md §7 deferred item 3",
    "BUG-164": "per-texture wrap/filter ignored (one shared REPEAT sampler)",
    "BUG-165": "multi-texture asset never converges within 300 frames",
    "BUG-166": "gltf crate vetoes extensionsRequired entries we already "
               "support downstream (clearcoat / unlit)",
    "BUG-167": "KHR_materials_pbrSpecularGlossiness entirely unhandled",
    "BUG-168": "EXT_mesh_gpu_instancing entirely unhandled",
    "BUG-169": "texture-less PBR materials render fully black",
    "BUG-170": "gltf crate 'missing field node' parse failure "
               "(KHR_animation_pointer / KHR_node_visibility)",
    "BUG-171": "materialless primitive skipped instead of using the glTF "
               "default material",
    "BUG-172": "glb with no default scene rejected instead of falling back "
               "to root nodes",
    "BUG-173": "10,000 materials exceeds OBJECT_SAFETY_MAX by design (D4) "
               "— not a defect",
    "BUG-184": "EXT_texture_webp is extensionsRequired and unsupported (no "
               "webp decoder) — correctly rejected, but the crate's raw "
               "textures[].source validation error surfaces instead of our "
               "own clean extensionsRequired veto message",
    "diffuse-transmission-deferred": "KHR_materials_diffuse_transmission "
               "full BTDF (and, for ScatteringSkull, "
               "KHR_materials_volume_scatter) explicitly deferred per "
               "GLTF_MATERIAL_EXTENSIONS_DESIGN.md §5 — renders as a plain "
               "opaque material, no crash",
    "G-P7": "no glTF-Binary variant in the pinned Khronos commit — not "
            "fetched (TextureTransformTest's sidecar-fetch exception, G-P4, "
            "is not extended to this set)",
}


def main() -> None:
    with open(MANIFEST, encoding="utf-8") as f:
        entries = json.load(f)

    expect_pass = [e for e in entries if e["status"] == "expect_pass"]
    xfail = [e for e in entries if e["status"].startswith("xfail:")]
    unclassified = [
        e for e in entries
        if e["status"] != "expect_pass" and not e["status"].startswith("xfail:")
    ]
    assert not unclassified, f"unclassified entries found: {unclassified}"

    xfail_by_reason: dict[str, list] = {}
    for e in xfail:
        reason = e["status"].split(":", 1)[1]
        xfail_by_reason.setdefault(reason, []).append(e)

    lines = []
    lines.append("# GLB Conformance Status — certification record")
    lines.append("")
    lines.append(
        "<!-- index: Generated by scripts/gen_glb_conformance_status.py from "
        "tests/fixtures/gltf/khronos/manifest.json (GLB_CONFORMANCE_DESIGN.md "
        "G-P7). Do not hand-edit the tables below — edit the manifest and "
        "regenerate. -->"
    )
    lines.append("")
    lines.append(
        "Certification record for GLB_CONFORMANCE_DESIGN.md G-P7 (burn-down "
        "and certification): every glTF-Sample-Assets asset at the pinned "
        "Khronos commit, classified `expect_pass` (numeric checks + a "
        "regression-pinning golden) or `xfail:<reason>` (a named deferred "
        "item, phase, or BUG-NNN) — no third state."
    )
    lines.append("")
    lines.append(
        f"**{len(entries)} assets total — {len(expect_pass)} expect_pass, "
        f"{len(xfail)} xfail across {len(xfail_by_reason)} reasons, 0 "
        "unclassified.**"
    )
    lines.append("")

    lines.append("## expect_pass")
    lines.append("")
    lines.append("| Asset | Checks |")
    lines.append("|---|---|")
    for e in sorted(expect_pass, key=lambda e: e["asset"]):
        kinds = ", ".join(c["kind"] for c in e["checks"])
        lines.append(f"| `{e['asset']}` | {kinds} |")
    lines.append("")

    lines.append("## xfail (by reason)")
    lines.append("")
    for reason in sorted(xfail_by_reason):
        group = xfail_by_reason[reason]
        gap = GAP_TEXT.get(reason, "(gap description not in this script's GAP_TEXT map)")
        lines.append(f"### `xfail:{reason}` — {len(group)} asset(s)")
        lines.append("")
        lines.append(f"**Gap:** {gap}")
        lines.append("")
        for e in sorted(group, key=lambda e: e["asset"]):
            lines.append(f"- `{e['asset']}`")
        lines.append("")

    with open(OUT, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")

    print(f"wrote {OUT}: {len(expect_pass)} expect_pass, {len(xfail)} xfail")


if __name__ == "__main__":
    main()
