//! `node.render_scene` — multi-object 3D scene renderer: N objects drawn
//! into ONE shared depth buffer (real occlusion between objects) lit by
//! any number of shared lights.
//!
//! Hand-written dynamic [`EffectNode`] (mux_texture-shaped, NOT the
//! `primitive!` macro): the `objects` param and `lights` param each
//! rebuild the port list in [`reconfigure`](EffectNode::reconfigure) —
//! same pattern as `node.switch_texture`'s `num_inputs`. Object count has
//! no structural cap — per-object port names (`mesh_{i}`, `transform_{i}`,
//! …) are generated by `format!` into the `Cow<'static, str>` name fields, and
//! the draw path issues one draw call per object. `OBJECT_SLIDER_MAX` is
//! only the editor slider's range, trivially raisable. Light count is
//! likewise uncapped: lights ride a runtime-sized `@binding(8)` storage
//! buffer, and `LIGHT_SLIDER_MAX` is only the editor slider's soft bound.
//!
//! `node.render_mesh` / `node.render_copies` each render into their own
//! private depth buffer — objects from either of those primitives cannot
//! occlude each other. `render_scene` closes that gap: every object draws
//! into ONE shared 4x-MSAA colour+depth target (cleared once) via
//! `manifold_gpu`'s `draw_instanced_depth_msaa_batch`, so the shared depth
//! test resolves real occlusion regardless of draw order, and the pass
//! resolves out to the single-sample `color` output with alpha-to-coverage
//! antialiasing the cutout edges.
//!
//! Per docs/REALTIME_3D_DESIGN.md §5 P2 (shipped): shadow maps for the
//! first `MAX_SHADOW_CASTING_LIGHTS` lights whose `cast_shadows` is set (in
//! slot order) — one depth-only pre-pass per caster into a private
//! `Depth32Float` map, consumed by PCF (`textureSampleCompareLevel`) in the
//! lit fragment shaders; lights past the caster cap still illuminate. No
//! atmosphere/fog yet (P3). Lights ride a ring-buffered `@binding(8)`
//! storage buffer (no 4KB `setBytes` cap). Per
//! docs/SCENE_BUILD_AND_GROUP_PARAMS_DESIGN.md §2 D3 (P2 of that design,
//! amending REALTIME_3D D3): each object's per-object TRS is no longer a
//! plain param — `rebuild` emits an optional `transform_n: PortType::Transform`
//! port per object instead of the retired nine scattered position/rotation/
//! scale params, fed by a `node.transform_3d` atom (unwired = identity). This
//! closes "transforms not beat-addressable": an LFO wired into the
//! transform atom's `rot_y` scalar port spins the object; a `beat_ramp`
//! into `pos_z` is a drop hit. Old saves carry a one-time migration
//! (`crate::migrations::scene_transform_v1120` in `manifold-io`) that
//! synthesizes the atom and re-points any card binding. Each object also
//! has an optional `base_color_map_n` albedo/alpha input (M6 addendum);
//! normal/roughness/metallic maps remain unwired per object (dummy-bound)
//! — a documented additive follow-up. ONE shared `envmap` input lights
//! every PBR object in the scene (an environment map is scene-wide by
//! nature, not per-object).
//!
//! Per docs/REALTIME_3D_DESIGN.md §10 D11+P8 (shipped): each object also
//! grows an optional `instances_n: Array(InstanceTransform)` port. Wired,
//! that object draws `instance_count = buffer_size / 32` copies (main pass
//! AND every caster's shadow pass), each instance's world transform
//! composed as `model_n · T_instance` — instance TRS applies first, the
//! object group's `transform_n` second, so wiring the SAME `node.transform_3d`
//! into two object groups keeps their instances glued together under a
//! group move. Unwired = a cached 1-entry identity stub, drawn with count 1
//! — the same shared depth buffer that resolves inter-object occlusion now
//! resolves occlusion between instances and every other object too, which
//! `node.render_copies`' private-depth-buffer instancing cannot do inside a
//! scene.

use ahash::AHashMap;
use manifold_gpu::GpuBinding;

use crate::generators::mesh_common::{InstanceTransform, MeshVertex};
use crate::node_graph::atmosphere::Atmosphere;
use crate::node_graph::camera::Camera;
use crate::node_graph::effect_node::{
    EffectNode, EffectNodeContext, EffectNodeType, ParamValues,
};
use crate::node_graph::material::{AlphaMode, Material, MaterialKind};
use crate::node_graph::parameters::{ParamDef, ParamType, ParamValue};
use crate::node_graph::ports::{ArrayType, NodeInput, NodeOutput, NodePort, PortKind, PortType};
use crate::node_graph::primitive::PrimitiveDescription;

pub const RENDER_SCENE_TYPE_ID: &str = "node.render_scene";

/// 4x MSAA for the scene pass. On Apple Silicon TBDR the multisample
/// color + depth live in tile memory (memoryless) and resolve on-chip —
/// no extra VRAM, one resolve at pass end. Paired with alpha-to-coverage
/// so cutout (`AlphaMode::Mask`) edges antialias too.
const MSAA_SAMPLES: u32 = 4;

/// Soft upper bound for the `objects` slider in the editor — NOT a
/// structural cap. Object ports are generated by `format!` in
/// `rebuild`, and the draw path issues one draw call per object, so
/// nothing in the type system, the shader, or the GPU bindings limits
/// object count. This constant only bounds the editor slider's range and
/// guards against a runaway port-list explosion (each object adds 4
/// ports: mesh/material/base_color_map/transform); raise it freely — it
/// is a single number with no coupling to anything else. Was a hard
/// `MAX_OBJECTS = 8` baked into static name tables until 2026-07-05.
pub(crate) const OBJECT_SLIDER_MAX: u32 = 64;
/// Soft upper bound for the `lights` slider — NOT a structural cap. Lights
/// ride a runtime-sized `array<vec4<f32>>` storage buffer at `@binding(8)`
/// (two vec4s per light), so nothing in the shader or the ABI limits the
/// count; each light gets its own dynamic `light_N` port. 64 lights ×
/// 32 B = 2 KB, half the Metal `setBytes` ceiling of 4 KB. HARD CEILING:
/// `setBytes` caps at 4 KB = 127 lights — do NOT raise this past 127
/// without first switching the `@binding(8)` arm from `GpuBinding::Bytes`
/// to a pooled `GpuBuffer` (docs/RENDER_SCENE_UNBOUNDED_LIGHTS_DESIGN.md
/// §6). Was a hard `MAX_LIGHTS = 4` baked into a fixed uniform array
/// until 2026-07-10.
const LIGHT_SLIDER_MAX: u32 = 64;

const DEFAULT_OBJECTS: u32 = 2;
const DEFAULT_LIGHTS: u32 = 1;

/// Shadow-caster cap (REALTIME_3D_DESIGN D4, F2 amendment). Shadow maps are
/// honoured for the first `K` lights *in slot order* whose
/// `cast_shadows == true`; lights beyond the first `K` casters still
/// illuminate the scene, they just cast no shadow. This is a SEPARATE,
/// tighter budget than the (uncapped) object/light sliders: it bounds the
/// worst case at `objects × K` shadow-depth draws (64 × 4 = 256), not
/// `objects × lights`. Bumpable like any cap — the shader's caster table
/// (`@binding(9)`) and shadow-map bindings (`@binding(10..)`) size to it.
pub(crate) const MAX_SHADOW_CASTING_LIGHTS: usize = 4;

/// Ring depth for the per-frame light storage buffer. The content thread is
/// triple-buffered and its tick loop waits on the surface from ~2 frames ago
/// (`content_thread.rs`), so up to ~2 frames of GPU work read a given
/// frame's light buffer while the CPU wants to write the next. Rotating
/// through `FRAMES_IN_FLIGHT` buffers guarantees the CPU never overwrites a
/// buffer the GPU is still reading — the correctness the single shared
/// `create_buffer_shared` buffer (mesh_pipeline/line_pipeline) leaves to
/// frame-pacing luck.
const FRAMES_IN_FLIGHT: usize = 3;

/// Per-caster shadow metadata, packed as 5 `vec4<f32>` into the
/// `@binding(9)` caster table (`MAX_SHADOW_CASTING_LIGHTS` slots, always
/// bound). Columns 0–3 are the light's `shadow_view_proj`; the 5th vec4 is
/// `(bias, kernel_half_width, texel_size, light_size)` — `light_size` is
/// the D12/PCSS spare `.w` (REALTIME_3D_DESIGN §11): zero for the fixed
/// Hard/Soft/VerySoft tiers, the light's `Contact { light_size }` value
/// otherwise, paired with a negative `kernel_half_width` sentinel that
/// tells `render_scene.wgsl`'s `shadow_factor` to run the PCSS branch
/// instead of the fixed-kernel PCF loop. Kept as a plain vec4 stride
/// (not a struct with a mat4 member) so the storage layout is unambiguous
/// through SPIRV-Cross → MSL — same discipline as the light buffer.
const CASTER_VEC4_STRIDE: usize = 5;

// Per-object AND per-light port names are generated on demand
// (`mesh_{i}`, `transform_{i}`, `light_{i}`, …) now that `NodePort.name` is
// `Cow<'static, str>` — no static name tables, no object cap, no light cap.

// `static`, not `const`: `NodePort.name` is now `Cow<'static, str>`, whose
// `Owned` variant carries drop glue, so `&RENDER_SCENE_OUTPUTS` can no longer
// be rvalue-static-promoted out of a `const`. A `static` gives the slice a
// genuine `'static` address to borrow.
static RENDER_SCENE_OUTPUTS: [NodeOutput; 1] = [NodePort {
    name: std::borrow::Cow::Borrowed("color"),
    ty: PortType::Texture2D,
    kind: PortKind::Output,
    required: false,
}];

/// Per-object uniform, one draw call per object. Superset shape shared
/// with `render_3d_mesh.wgsl`'s Material fields, plus a per-object
/// `model` matrix. Lights are NOT here — they live in the runtime-sized
/// `@binding(8)` storage buffer (see `evaluate`). See
/// `shaders/render_scene.wgsl` for the authoritative layout comment.
#[repr(C)]
#[derive(Clone, Copy, bytemuck::Pod, bytemuck::Zeroable)]
struct RenderSceneUniforms {
    view_proj: [[f32; 4]; 4],
    model: [[f32; 4]; 4],
    camera_pos: [f32; 4],
    base_color: [f32; 4],
    emission: [f32; 4],
    pbr_metallic_roughness: [f32; 4],
    specular: [f32; 4],
    cel_params: [f32; 4],
    /// `z` = 1.0 when this object's `base_color_map_n` is wired (matches
    /// `resolve_albedo`'s `texture_flags.z` gate); x/y/w remain zero — no
    /// normal_map/roughness_map/metallic_map inputs per object yet.
    texture_flags: [f32; 4],
    alpha_params: [f32; 4],
    /// `(light_count, ambient, exposure_ev, 0)`. `light_count` is the sole
    /// source of truth for how many `@binding(8)` entries the shader reads —
    /// NOT `arrayLength` (D1). `exposure_ev` (CAMERA_AND_LENS_DESIGN.md §2
    /// D5, was zero-padded until P2) is the camera's `lens.exposure_ev` —
    /// the shader multiplies its final straight rgb by `exp2(exposure_ev)`.
    scene_params: [f32; 4],
    /// Atmosphere (P3): fog colour (rgb; a reserved). Scene-wide — the same
    /// values are copied into every object's uniform.
    fog_color: [f32; 4],
    /// `(fog_density, height_falloff, 0, 0)`. `fog_density == 0` → no fog
    /// (unwired atmosphere = byte-identical to no atmosphere).
    fog_params: [f32; 4],
    /// Scene-wide ambient/sky tint (rgb multiplier on the ambient term).
    ambient_tint: [f32; 4],
}

// 320 = 20 × 16 → the naga 16-byte uniform-size rule holds. Was 272 before
// the P3 atmosphere fields (fog_color + fog_params + ambient_tint = 3 vec4).
const _: () = assert!(std::mem::size_of::<RenderSceneUniforms>() == 320);

/// Per-(caster, object) uniform for the shadow depth pass
/// (`shaders/shadow_depth.wgsl`). The vertex shader composes
/// `light_view_proj · model · position` and writes only depth. 128 bytes.
#[repr(C)]
#[derive(Clone, Copy, bytemuck::Pod, bytemuck::Zeroable)]
struct ShadowUniforms {
    light_view_proj: [[f32; 4]; 4],
    model: [[f32; 4]; 4],
}
const _: () = assert!(std::mem::size_of::<ShadowUniforms>() == 128);

pub struct RenderScene {
    inputs: Vec<NodeInput>,
    params: Vec<ParamDef>,
    num_objects: u32,
    num_lights: u32,
    pipelines: AHashMap<MaterialKind, manifold_gpu::GpuRenderPipeline>,
    depth_stencil: Option<manifold_gpu::GpuDepthStencilState>,
    /// Memoryless 4x-MSAA color + depth targets for the scene pass, sized
    /// to the render target. Both resolve on-chip; only `msaa_color`
    /// resolves out to the single-sample output.
    msaa_color: Option<manifold_gpu::GpuTexture>,
    depth_texture: Option<manifold_gpu::GpuTexture>,
    depth_width: u32,
    depth_height: u32,
    dummy_texture: Option<manifold_gpu::GpuTexture>,
    sampler: Option<manifold_gpu::GpuSampler>,
    /// Ring of per-frame light storage buffers (see [`FRAMES_IN_FLIGHT`]).
    /// Grown on demand; rotated each `evaluate` so a frame's write never
    /// lands on a buffer an in-flight frame is still reading.
    light_buffers: Vec<manifold_gpu::GpuBuffer>,
    light_frame: usize,
    light_capacity: u64,
    /// Depth-only pipeline + depth-stencil state for the shadow passes.
    shadow_pipeline: Option<manifold_gpu::GpuRenderPipeline>,
    shadow_depth_stencil: Option<manifold_gpu::GpuDepthStencilState>,
    /// Per-caster private shadow maps, cached `(resolution, texture)`;
    /// recreated when a caster's `shadow_resolution` changes. Created
    /// `RENDER_TARGET | SHADER_READ` (AGX 0x78 guard).
    shadow_maps: [Option<(u32, manifold_gpu::GpuTexture)>; MAX_SHADOW_CASTING_LIGHTS],
    /// PCF comparison sampler (`compare = Less`).
    shadow_sampler: Option<manifold_gpu::GpuSampler>,
    /// 1×1 `Depth32Float` (`SHADER_READ`) bound to unused/non-caster
    /// shadow-map slots so every `@binding(10..)` is always a valid depth
    /// texture even in a scene with no casters.
    dummy_depth: Option<manifold_gpu::GpuTexture>,
    /// Cached 1-entry `Array(InstanceTransform)` bound to `instances_n`
    /// for any object that leaves it unwired: `pos_scale = [0,0,0,1]`,
    /// `rot_pad = [0,0,0,0]` — the same always-bind ABI-stub pattern as
    /// `dummy_depth` (D11). Drawn with `instance_count = 1`, so the
    /// vertex shader's `model_n · T_instance` composition collapses to
    /// exactly `model_n` — an unwired object costs one extra 32-byte L1
    /// storage-buffer read, nothing observable in the output.
    identity_instance_stub: Option<manifold_gpu::GpuBuffer>,
}

impl RenderScene {
    pub fn new() -> Self {
        let mut s = Self {
            inputs: Vec::new(),
            params: Vec::new(),
            num_objects: 0,
            num_lights: 0,
            pipelines: AHashMap::new(),
            depth_stencil: None,
            msaa_color: None,
            depth_texture: None,
            depth_width: 0,
            depth_height: 0,
            dummy_texture: None,
            sampler: None,
            light_buffers: Vec::new(),
            light_frame: 0,
            light_capacity: 0,
            shadow_pipeline: None,
            shadow_depth_stencil: None,
            shadow_maps: std::array::from_fn(|_| None),
            shadow_sampler: None,
            dummy_depth: None,
            identity_instance_stub: None,
        };
        s.rebuild(DEFAULT_OBJECTS, DEFAULT_LIGHTS);
        s
    }

    /// (Re)build the input port list AND the parameter list for
    /// `objects` objects / `lights` lights (each clamped to its cap).
    fn rebuild(&mut self, objects: u32, lights: u32) {
        let objects = objects.clamp(1, OBJECT_SLIDER_MAX);
        let lights = lights.clamp(0, LIGHT_SLIDER_MAX);
        let n_obj = objects as usize;
        let n_lights = lights as usize;

        let mut inputs = Vec::with_capacity(3 + n_lights + n_obj * 5);
        inputs.push(NodePort {
            name: std::borrow::Cow::Borrowed("camera"),
            ty: PortType::Camera,
            kind: PortKind::Input,
            required: true,
        });
        inputs.push(NodePort {
            name: std::borrow::Cow::Borrowed("envmap"),
            ty: PortType::Texture2D,
            kind: PortKind::Input,
            required: false,
        });
        // Optional scene-wide atmosphere (P3). Unwired = fog off,
        // byte-identical to no atmosphere.
        inputs.push(NodePort {
            name: std::borrow::Cow::Borrowed("atmosphere"),
            ty: PortType::Atmosphere,
            kind: PortKind::Input,
            required: false,
        });
        for i in 0..n_lights {
            inputs.push(NodePort {
                name: std::borrow::Cow::Owned(format!("light_{i}")),
                ty: PortType::Light,
                kind: PortKind::Input,
                required: false,
            });
        }
        let mesh_ty = PortType::Array(ArrayType::of_known::<MeshVertex>());
        let instance_ty = PortType::Array(ArrayType::of_known::<InstanceTransform>());
        for i in 0..n_obj {
            inputs.push(NodePort {
                name: std::borrow::Cow::Owned(format!("mesh_{i}")),
                ty: mesh_ty,
                kind: PortKind::Input,
                required: true,
            });
            inputs.push(NodePort {
                name: std::borrow::Cow::Owned(format!("material_{i}")),
                ty: PortType::Material,
                kind: PortKind::Input,
                required: true,
            });
            inputs.push(NodePort {
                name: std::borrow::Cow::Owned(format!("base_color_map_{i}")),
                ty: PortType::Texture2D,
                kind: PortKind::Input,
                required: false,
            });
            inputs.push(NodePort {
                name: std::borrow::Cow::Owned(format!("transform_{i}")),
                ty: PortType::Transform,
                kind: PortKind::Input,
                required: false,
            });
            // D11: unwired = this object draws once with a cached 1-entry
            // identity stub (see `ensure_identity_instance_stub`); wired =
            // instance_count = buffer_size / 32, each instance transformed
            // by `model_n · T_instance`.
            inputs.push(NodePort {
                name: std::borrow::Cow::Owned(format!("instances_{i}")),
                ty: instance_ty,
                kind: PortKind::Input,
                required: false,
            });
        }

        let params = vec![
            ParamDef {
                name: std::borrow::Cow::Borrowed("objects"),
                label: "Objects",
                ty: ParamType::Int,
                default: ParamValue::Float(DEFAULT_OBJECTS as f32),
                range: Some((1.0, OBJECT_SLIDER_MAX as f32)),
                enum_values: &[],
            },
            ParamDef {
                name: std::borrow::Cow::Borrowed("lights"),
                label: "Lights",
                ty: ParamType::Int,
                default: ParamValue::Float(DEFAULT_LIGHTS as f32),
                range: Some((0.0, LIGHT_SLIDER_MAX as f32)),
                enum_values: &[],
            },
        ];
        // Per-object TRS is no longer a param loop here — `transform_{i}`
        // (added above) carries it as a `Transform` port fed by a
        // `node.transform_3d` atom (SCENE_BUILD_AND_GROUP_PARAMS_DESIGN.md
        // §2 D3). Do NOT re-add per-object params as an unwired fallback —
        // that is the forbidden parallel-old-path shape D3 names explicitly.

        self.inputs = inputs;
        self.params = params;
        self.num_objects = objects;
        self.num_lights = lights;
    }

    /// Ensure the memoryless MSAA color + depth targets match the render
    /// target size. Both are `MSAA_SAMPLES`x multisample, tile-resident
    /// (never leave the GPU); the color resolves out at pass end.
    fn ensure_msaa_targets(&mut self, device: &manifold_gpu::GpuDevice, width: u32, height: u32) {
        if self.depth_width == width
            && self.depth_height == height
            && self.depth_texture.is_some()
            && self.msaa_color.is_some()
        {
            return;
        }
        self.msaa_color = Some(device.create_texture_msaa_memoryless(
            width,
            height,
            manifold_gpu::GpuTextureFormat::Rgba16Float,
            MSAA_SAMPLES,
            "node.render_scene msaa color",
        ));
        self.depth_texture = Some(device.create_texture_msaa_memoryless(
            width,
            height,
            manifold_gpu::GpuTextureFormat::Depth32Float,
            MSAA_SAMPLES,
            "node.render_scene msaa depth",
        ));
        self.depth_width = width;
        self.depth_height = height;
    }

    fn ensure_sampler(&mut self, device: &manifold_gpu::GpuDevice) {
        if self.sampler.is_none() {
            self.sampler = Some(device.create_sampler(&manifold_gpu::GpuSamplerDesc {
                mag_filter: manifold_gpu::GpuFilterMode::Linear,
                min_filter: manifold_gpu::GpuFilterMode::Linear,
                mip_filter: manifold_gpu::GpuFilterMode::Linear,
                address_mode_u: manifold_gpu::GpuAddressMode::Repeat,
                address_mode_v: manifold_gpu::GpuAddressMode::ClampToEdge,
                address_mode_w: manifold_gpu::GpuAddressMode::ClampToEdge,
                compare: None,
            }));
        }
    }

    fn ensure_dummy_texture(&mut self, device: &manifold_gpu::GpuDevice) {
        if self.dummy_texture.is_none() {
            self.dummy_texture = Some(device.create_texture(&manifold_gpu::GpuTextureDesc {
                width: 1,
                height: 1,
                depth: 1,
                format: manifold_gpu::GpuTextureFormat::Rgba16Float,
                dimension: manifold_gpu::GpuTextureDimension::D2,
                usage: manifold_gpu::GpuTextureUsage::SHADER_READ,
                label: "node.render_scene dummy",
                mip_levels: 1,
            }));
        }
    }

    /// Ensure the shader-ABI binding stubs the main pass ALWAYS needs: the
    /// PCF comparison sampler (`@binding(14)`) and the 1×1 dummy depth
    /// texture bound to non-caster shadow-map slots. Cheap; called every
    /// frame regardless of whether any light casts. The depth-only shadow
    /// *pipeline* and per-caster maps are NOT created here — that is real
    /// shadow work, gated on there actually being a caster
    /// ([`Self::ensure_shadow_pass`]), so an unwired scene pays nothing.
    fn ensure_shadow_binding_stubs(&mut self, device: &manifold_gpu::GpuDevice) {
        if self.shadow_sampler.is_none() {
            // Comparison sampler: linear filtering gives hardware 2×2 PCF per
            // tap, clamp addressing so off-map samples read the border depth.
            self.shadow_sampler = Some(device.create_sampler(&manifold_gpu::GpuSamplerDesc {
                mag_filter: manifold_gpu::GpuFilterMode::Linear,
                min_filter: manifold_gpu::GpuFilterMode::Linear,
                mip_filter: manifold_gpu::GpuFilterMode::Linear,
                address_mode_u: manifold_gpu::GpuAddressMode::ClampToEdge,
                address_mode_v: manifold_gpu::GpuAddressMode::ClampToEdge,
                address_mode_w: manifold_gpu::GpuAddressMode::ClampToEdge,
                compare: Some(manifold_gpu::GpuCompareFunction::Less),
            }));
        }
        if self.dummy_depth.is_none() {
            // Bound to unused/non-caster shadow-map slots. Never sampled (the
            // shader returns "lit" before sampling a non-caster slot), but
            // Metal requires every declared binding to be a valid texture.
            // RENDER_TARGET | SHADER_READ, like the real maps, so no depth
            // format needs a render-target-only exception (AGX 0x78 guard).
            self.dummy_depth = Some(device.create_texture(&manifold_gpu::GpuTextureDesc {
                width: 1,
                height: 1,
                depth: 1,
                format: manifold_gpu::GpuTextureFormat::Depth32Float,
                dimension: manifold_gpu::GpuTextureDimension::D2,
                usage: manifold_gpu::GpuTextureUsage::RENDER_TARGET
                    | manifold_gpu::GpuTextureUsage::SHADER_READ,
                label: "node.render_scene dummy shadow",
                mip_levels: 1,
            }));
        }
    }

    /// Ensure the depth-only shadow pipeline + its depth-stencil state exist.
    /// Called ONLY when at least one caster is present — compiling the shadow
    /// shader is real work an unwired scene must not pay.
    fn ensure_shadow_pass(&mut self, device: &manifold_gpu::GpuDevice) {
        if self.shadow_pipeline.is_none() {
            self.shadow_pipeline = Some(device.create_render_pipeline_depth_only(
                include_str!("shaders/shadow_depth.wgsl"),
                "vs_main",
                "fs_shadow",
                manifold_gpu::GpuTextureFormat::Depth32Float,
                "node.render_scene shadow depth",
            ));
        }
        if self.shadow_depth_stencil.is_none() {
            self.shadow_depth_stencil = Some(device.create_depth_stencil_state(
                &manifold_gpu::GpuDepthStencilDesc {
                    compare: manifold_gpu::GpuCompareFunction::Less,
                    write_enabled: true,
                },
            ));
        }
    }

    /// Ensure shadow map `slot` is a private `Depth32Float` of `resolution`²,
    /// recreating it if the caster's requested resolution changed.
    /// `RENDER_TARGET | SHADER_READ`: rendered as a depth target, then sampled
    /// as a shadow map — both usages at creation (AGX 0x78 guard).
    fn ensure_shadow_map(&mut self, device: &manifold_gpu::GpuDevice, slot: usize, resolution: u32) {
        let res = resolution.clamp(256, 4096);
        let needs = match &self.shadow_maps[slot] {
            Some((cached, _)) => *cached != res,
            None => true,
        };
        if needs {
            let tex = device.create_texture(&manifold_gpu::GpuTextureDesc {
                width: res,
                height: res,
                depth: 1,
                format: manifold_gpu::GpuTextureFormat::Depth32Float,
                dimension: manifold_gpu::GpuTextureDimension::D2,
                usage: manifold_gpu::GpuTextureUsage::RENDER_TARGET
                    | manifold_gpu::GpuTextureUsage::SHADER_READ,
                label: "node.render_scene shadow map",
                mip_levels: 1,
            });
            self.shadow_maps[slot] = Some((res, tex));
        }
    }

    /// Ensure the cached 1-entry identity `InstanceTransform` stub bound to
    /// any object's `instances_n` when that port is unwired (D11). Created
    /// once; cheap, called every frame like the shadow ABI stubs.
    fn ensure_identity_instance_stub(&mut self, device: &manifold_gpu::GpuDevice) {
        if self.identity_instance_stub.is_none() {
            let stub = InstanceTransform {
                pos_scale: [0.0, 0.0, 0.0, 1.0],
                rot_pad: [0.0, 0.0, 0.0, 0.0],
            };
            let buf =
                device.create_buffer_shared(std::mem::size_of::<InstanceTransform>() as u64);
            unsafe {
                buf.write(0, bytemuck::bytes_of(&stub));
            }
            self.identity_instance_stub = Some(buf);
        }
    }

    fn pipeline_for(
        &mut self,
        device: &manifold_gpu::GpuDevice,
        kind: MaterialKind,
    ) -> &manifold_gpu::GpuRenderPipeline {
        let fs_entry = match kind {
            MaterialKind::Unlit => "fs_unlit",
            MaterialKind::Phong => "fs_phong",
            MaterialKind::Pbr => "fs_pbr",
            MaterialKind::Cel => "fs_cel",
        };
        self.pipelines.entry(kind).or_insert_with(|| {
            device.create_render_pipeline_depth_msaa(
                include_str!("shaders/render_scene.wgsl"),
                "vs_main",
                fs_entry,
                manifold_gpu::GpuTextureFormat::Rgba16Float,
                manifold_gpu::GpuTextureFormat::Depth32Float,
                None,
                MSAA_SAMPLES,
                true, // alpha-to-coverage: antialias the cutout `discard` edge, not just silhouettes
                "node.render_scene",
            )
        })
    }

    /// AI-composition surface metadata.
    pub fn description() -> PrimitiveDescription {
        PrimitiveDescription {
            type_id: RENDER_SCENE_TYPE_ID,
            purpose: "Multi-object 3D scene renderer: draws `objects` separate Array<MeshVertex> meshes (one draw call each, no fixed cap on object count) into ONE shared depth buffer, so nearer objects correctly occlude farther ones — the gap node.render_mesh / node.render_copies can't close (each of those renders into its own private depth buffer). Each object carries its own material_n: Material, an optional base_color_map_n: Texture2D albedo/alpha map, an optional transform_n: Transform (from node.transform_3d; unwired = identity) composed CPU-side into a model matrix, and an optional instances_n: Array(InstanceTransform) — wired, that object draws instance_count = buffer_size / 32 copies (main pass AND every caster's shadow pass), each instance's world transform composed as model_n · T_instance (instance TRS first, the object group's transform_n second, so scattered instances stay glued to their group under a group move); unwired draws once with an identity instance. Instances share the shared depth buffer too, so they correctly occlude and are occluded by every other object in the scene — the gap node.render_copies' private-depth-buffer instancing can't close. When base_color_map_n is wired, the sampled texel modulates material_n's base_color (rgb × rgb) and its alpha drives that material's alpha-cutout discard when alpha_mode is Mask — same resolve_albedo path as node.render_mesh. Normal/roughness/metallic maps remain unwired per object (dummy-bound) — a documented additive follow-up. `lights` shared Light inputs light_0..light_{lights-1} (no fixed cap — lights ride a runtime-sized storage buffer) accumulate in the Phong/PBR/Cel shading — each light's direct term is summed, ambient + emission are added once. ONE shared envmap input lights every PBR object in the scene (an environment map is scene-wide, not per-object). Shadows: the first 4 lights (in slot order) whose cast_shadows is set drop real shadow maps onto the scene (PCF-softened per the light's shadow_softness); lights past that cap still illuminate but cast no shadow. No atmosphere/fog yet (P3).",
            composition_notes: "objects and lights are reconfigure params: changing either rebuilds the port list (mesh_n/material_n/base_color_map_n/transform_n/instances_n quintuples, light_0..N); the render node itself carries only `objects`/`lights` as params now, same dynamic-port pattern as node.switch_texture's num_inputs. Wire a node.transform_3d into transform_n to place/animate that object — each of its nine scalar ports (pos/rot/scale) is independently port-shadowed, so an LFO into rot_y spins it live; leaving transform_n unwired renders the object at the origin, unrotated, unit scale. base_color_map_n is optional — leaving it unwired renders that object with material_n's flat base_color, exactly as before this port existed. instances_n is optional and carries no per-object instance_count param — wire node.scatter_on_mesh (or any Array(InstanceTransform) producer) to draw that many copies; density control lives on the producer (e.g. scatter_on_mesh's port-shadowed count), not on render_scene. A missing mesh_n or material_n, or a PBR material_n with envmap left unwired, is a structured error (ctx.error + magenta clear on `color`), matching render_mesh's no-silent-fallbacks contract. Object 0 clears the shared color+depth target; objects 1..N load onto it — the shared depth buffer resolves occlusion regardless of which object happens to be object 0.",
            examples: &[],
            inputs: &[],
            outputs: &RENDER_SCENE_OUTPUTS,
            params: &[],
        }
    }
}

impl Default for RenderScene {
    fn default() -> Self {
        Self::new()
    }
}

fn cached_type_id() -> &'static EffectNodeType {
    static CELL: std::sync::OnceLock<EffectNodeType> = std::sync::OnceLock::new();
    CELL.get_or_init(|| EffectNodeType::new(RENDER_SCENE_TYPE_ID))
}

/// Build a column-major 4×4 model matrix from TRS params: `model = T *
/// R * S`. Rotation order matches `render_instanced_3d_mesh.wgsl`'s
/// `euler_xyz` (X → Y → Z, i.e. `R = Rz * Ry * Rx`) so render_scene and
/// render_copies agree on what a given `(rot_x, rot_y, rot_z)` means.
/// Non-uniform scale's normal skew is NOT corrected (no
/// inverse-transpose) — v1 limitation, documented on the shader side.
fn model_matrix(pos: [f32; 3], rot: [f32; 3], scale: [f32; 3]) -> [[f32; 4]; 4] {
    let r = euler_xyz_columns(rot);
    [
        [
            r[0][0] * scale[0],
            r[0][1] * scale[0],
            r[0][2] * scale[0],
            0.0,
        ],
        [
            r[1][0] * scale[1],
            r[1][1] * scale[1],
            r[1][2] * scale[1],
            0.0,
        ],
        [
            r[2][0] * scale[2],
            r[2][1] * scale[2],
            r[2][2] * scale[2],
            0.0,
        ],
        [pos[0], pos[1], pos[2], 1.0],
    ]
}

/// Column-major 3×3 rotation matrix for XYZ Euler angles (radians),
/// composed as `Rz * Ry * Rx` — bit-for-bit the same column layout as
/// `render_instanced_3d_mesh.wgsl`'s `euler_xyz`.
fn euler_xyz_columns(rot: [f32; 3]) -> [[f32; 3]; 3] {
    let (cx, sx) = (rot[0].cos(), rot[0].sin());
    let (cy, sy) = (rot[1].cos(), rot[1].sin());
    let (cz, sz) = (rot[2].cos(), rot[2].sin());

    let rx = [[1.0, 0.0, 0.0], [0.0, cx, sx], [0.0, -sx, cx]];
    let ry = [[cy, 0.0, -sy], [0.0, 1.0, 0.0], [sy, 0.0, cy]];
    let rz = [[cz, sz, 0.0], [-sz, cz, 0.0], [0.0, 0.0, 1.0]];

    mat3_mul(mat3_mul(rz, ry), rx)
}

/// Multiply two 3×3 column-major matrices: result = A * B. Mirrors
/// `generators::mesh_pipeline::mat4_mul`'s convention one dimension down.
fn mat3_mul(a: [[f32; 3]; 3], b: [[f32; 3]; 3]) -> [[f32; 3]; 3] {
    let mut out = [[0.0f32; 3]; 3];
    for col in 0..3 {
        for row in 0..3 {
            out[col][row] =
                a[0][row] * b[col][0] + a[1][row] * b[col][1] + a[2][row] * b[col][2];
        }
    }
    out
}

#[allow(clippy::too_many_arguments)]
fn build_uniforms(
    view_proj: [[f32; 4]; 4],
    model: [[f32; 4]; 4],
    cam: &Camera,
    material: &Material,
    light_count: f32,
    atmosphere: &Atmosphere,
) -> RenderSceneUniforms {
    RenderSceneUniforms {
        view_proj,
        model,
        camera_pos: [cam.pos[0], cam.pos[1], cam.pos[2], 1.0],
        base_color: material.base_color,
        emission: material.emission,
        pbr_metallic_roughness: [material.metallic, material.roughness, 0.0, 0.0],
        specular: [
            material.specular_color[0],
            material.specular_color[1],
            material.specular_color[2],
            material.specular_power,
        ],
        cel_params: [
            material.cel_bands as f32,
            material.band_low,
            material.band_high,
            0.0,
        ],
        texture_flags: [0.0, 0.0, 0.0, 0.0],
        alpha_params: [
            match material.alpha_mode {
                AlphaMode::Mask => 1.0,
                AlphaMode::Opaque => 0.0,
            },
            material.alpha_cutoff,
            0.0,
            0.0,
        ],
        // z = exposure_ev (CAMERA_AND_LENS_DESIGN.md §2 D5) — the fragment
        // shaders multiply their final straight rgb by exp2(scene_params.z).
        // Every builder defaults `cam.lens` to `LensParams::PINHOLE`
        // (exposure_ev = 0.0), so an unwired lens is byte-identical (I2/I5).
        scene_params: [light_count, material.ambient, cam.lens.exposure_ev, 0.0],
        fog_color: atmosphere.fog_color,
        fog_params: [atmosphere.fog_density, atmosphere.height_falloff, 0.0, 0.0],
        ambient_tint: atmosphere.ambient_tint,
    }
}

impl EffectNode for RenderScene {
    fn type_id(&self) -> &EffectNodeType {
        cached_type_id()
    }

    fn inputs(&self) -> &[NodeInput] {
        &self.inputs
    }

    fn outputs(&self) -> &[NodeOutput] {
        &RENDER_SCENE_OUTPUTS
    }

    fn parameters(&self) -> &[ParamDef] {
        &self.params
    }

    fn reconfigure(&mut self, params: &ParamValues) {
        let objects = params
            .get("objects")
            .and_then(|v| v.as_scalar())
            .map(|f| f.round().clamp(1.0, OBJECT_SLIDER_MAX as f32) as u32)
            .unwrap_or(DEFAULT_OBJECTS);
        let lights = params
            .get("lights")
            .and_then(|v| v.as_scalar())
            .map(|f| f.round().clamp(0.0, LIGHT_SLIDER_MAX as f32) as u32)
            .unwrap_or(DEFAULT_LIGHTS);
        if objects != self.num_objects || lights != self.num_lights {
            self.rebuild(objects, lights);
        }
    }

    fn evaluate<'ctx, 'gpu>(&mut self, ctx: &mut EffectNodeContext<'ctx, 'gpu>) {
        let objects = self.num_objects as usize;
        let lights_n = self.num_lights as usize;

        let cam = ctx
            .inputs
            .camera("camera")
            .unwrap_or_else(Camera::default_perspective);
        let envmap_wired = ctx.inputs.texture_2d("envmap");
        // Scene-wide atmosphere (P3). Unwired = Atmosphere::default() = fog
        // density 0 = no fog (the shader's exp fog collapses to identity), so
        // an unwired atmosphere is byte-identical to no atmosphere.
        let atmosphere = ctx.inputs.atmosphere("atmosphere").unwrap_or_default();

        // Build the shared lights buffer from whichever light_N ports are
        // actually wired (unwired slots simply don't contribute — 0 lights
        // is a valid scene state, matched by ambient + emission only). Two
        // vec4s per light. As lights are collected, the first
        // `MAX_SHADOW_CASTING_LIGHTS` of them whose `cast_shadows` is set
        // (in slot order — D4/F2) are recorded as shadow casters; each
        // caster's light-space matrix + PCF params go into the caster table
        // below, and its slot index rides the previously-unused `.w` of the
        // light's colour vec4 (−1.0 = not a caster). Lights beyond the cap
        // still illuminate; they simply carry slot −1 and cast no shadow.
        let mut light_data: Vec<[f32; 4]> = Vec::with_capacity(lights_n * 2);
        let mut light_count: u32 = 0;
        let mut casters: Vec<crate::node_graph::light::Light> =
            Vec::with_capacity(MAX_SHADOW_CASTING_LIGHTS);
        for i in 0..lights_n {
            if let Some(l) = ctx.inputs.light(&format!("light_{i}")) {
                let slot: f32 = if l.cast_shadows && casters.len() < MAX_SHADOW_CASTING_LIGHTS {
                    let s = casters.len() as f32;
                    casters.push(l);
                    s
                } else {
                    -1.0
                };
                light_data.push([-l.dir[0], -l.dir[1], -l.dir[2], 1.0]);
                light_data.push([l.color[0], l.color[1], l.color[2], slot]);
                light_count += 1;
            }
        }
        // D4: `@binding(8)` must ALWAYS be bound (the fragment shaders
        // declare it unconditionally), so a zero-light scene binds one
        // zeroed entry the shader never reads (`light_count == 0`). Skipping
        // the binding on empty is the forbidden silent-fallback shape.
        if light_data.is_empty() {
            light_data.extend([[0.0f32; 4]; 2]);
        }

        // Caster table (`@binding(9)`): `MAX_SHADOW_CASTING_LIGHTS` slots ×
        // `CASTER_VEC4_STRIDE` vec4, zeroed then filled per active caster.
        // Columns 0–3 = shadow_view_proj; vec4 4 = (bias, kernel_half_width,
        // texel_size, light_size). Always fully sized so `@binding(9)` is a
        // fixed bind regardless of caster count (Bytes, copy-at-encode,
        // hazard-free).
        let mut caster_table: Vec<[f32; 4]> =
            vec![[0.0; 4]; MAX_SHADOW_CASTING_LIGHTS * CASTER_VEC4_STRIDE];
        for (slot, l) in casters.iter().enumerate() {
            let vp = l.shadow_view_proj();
            let base = slot * CASTER_VEC4_STRIDE;
            caster_table[base] = vp[0];
            caster_table[base + 1] = vp[1];
            caster_table[base + 2] = vp[2];
            caster_table[base + 3] = vp[3];
            // D12: `Contact` has no fixed kernel width — `kernel_half_width()`
            // returns the sentinel `-1`, which `render_scene.wgsl`'s
            // `shadow_factor` reads as "run the PCSS blocker-search branch,
            // using `light_size` below" instead of the fixed PCF loop.
            let khw = l.shadow_softness.kernel_half_width() as f32;
            let light_size = match l.shadow_softness {
                crate::node_graph::light::ShadowSoftness::Contact { light_size } => light_size,
                _ => 0.0,
            };
            let texel = 1.0 / l.shadow_resolution.clamp(256, 4096) as f32;
            caster_table[base + 4] = [l.shadow_bias, khw, texel, light_size];
        }

        let Some(dims_tex) = ctx.outputs.texture_2d("color") else {
            return;
        };
        let width = dims_tex.width;
        let height = dims_tex.height;
        if width == 0 || height == 0 {
            return;
        }
        let aspect = width as f32 / height as f32;
        let view_proj = cam.view_proj(aspect);

        // ---- Pass 1 (mutable phase): validate every object's required
        // inputs, compose its model matrix + uniforms, and get-or-compile
        // its pipeline. Structured error + magenta clear + return on the
        // first unmet requirement (no-silent-fallbacks, matching
        // render_mesh / render_copies).
        struct ObjectDraw<'ctx> {
            vertices: &'ctx manifold_gpu::GpuBuffer,
            uniforms: RenderSceneUniforms,
            pipeline: manifold_gpu::GpuRenderPipeline,
            base_color_map: Option<&'ctx manifold_gpu::GpuTexture>,
            /// Wired `instances_n` buffer, or `None` (unwired — bind the
            /// identity stub at draw time; see `identity_instance_stub`).
            instances: Option<&'ctx manifold_gpu::GpuBuffer>,
            /// `buffer_size / 32` when wired, else 1 (identity stub).
            instance_count: u32,
        }

        let instance_size = std::mem::size_of::<InstanceTransform>() as u64;

        let mut draws: Vec<ObjectDraw<'ctx>> = Vec::with_capacity(objects);

        for n in 0..objects {
            // Per-object port/param names, generated once (no static
            // name tables — object count is unbounded).
            let mesh_name = format!("mesh_{n}");
            let material_name = format!("material_{n}");
            let Some(vertices) = ctx.inputs.array(&mesh_name) else {
                ctx.error(format!(
                    "missing required `{mesh_name}` input; renderer fell back to magenta clear"
                ));
                if let Some(target) = ctx.outputs.texture_2d("color") {
                    let gpu = ctx.gpu_encoder();
                    gpu.native_enc.clear_texture(target, 1.0, 0.0, 1.0, 1.0);
                }
                return;
            };
            let Some(material) = ctx.inputs.material(&material_name) else {
                ctx.error(format!(
                    "missing required `{material_name}` input; renderer fell back to magenta clear"
                ));
                if let Some(target) = ctx.outputs.texture_2d("color") {
                    let gpu = ctx.gpu_encoder();
                    gpu.native_enc.clear_texture(target, 1.0, 0.0, 1.0, 1.0);
                }
                return;
            };
            if material.requires_envmap() && envmap_wired.is_none() {
                ctx.error(format!(
                    "{:?} material on `{material_name}` requires `envmap` input but it is unwired; renderer fell back to magenta",
                    material.kind
                ));
                if let Some(target) = ctx.outputs.texture_2d("color") {
                    let gpu = ctx.gpu_encoder();
                    gpu.native_enc.clear_texture(target, 1.0, 0.0, 1.0, 1.0);
                }
                return;
            }
            let base_color_map = ctx.inputs.texture_2d(&format!("base_color_map_{n}"));

            // Unwired `transform_n` = identity (`Transform::default()`) —
            // matches the old scattered params' defaults exactly (pos 0,
            // rot 0, scale 1). See SCENE_BUILD_AND_GROUP_PARAMS_DESIGN.md §2
            // D3: no per-object param fallback — `node.transform_3d` is the
            // only producer now.
            let t = ctx
                .inputs
                .transform(&format!("transform_{n}"))
                .unwrap_or_default();
            let model = model_matrix(t.pos, t.rot_euler, t.scale);
            let mut uniforms = build_uniforms(
                view_proj,
                model,
                &cam,
                &material,
                light_count as f32,
                &atmosphere,
            );
            if base_color_map.is_some() {
                uniforms.texture_flags[2] = 1.0; // z = base_color_map present (matches resolve_albedo's texture_flags.z gate)
            }

            let pipeline = {
                let gpu = ctx.gpu_encoder();
                self.pipeline_for(gpu.device, material.kind).clone()
            };

            // D11: wired instances_n draws instance_count = buffer_size / 32
            // copies (0 → that object's draw becomes a legal instance-count-0
            // no-op); unwired draws once via the identity stub (bound at
            // Pass 2 — this object carries no self-owned buffer reference).
            let instances = ctx.inputs.array(&format!("instances_{n}"));
            let instance_count = match instances {
                Some(buf) => (buf.size / instance_size) as u32,
                None => 1,
            };

            draws.push(ObjectDraw {
                vertices,
                uniforms,
                pipeline,
                base_color_map,
                instances,
                instance_count,
            });
        }

        if draws.is_empty() {
            return;
        }

        // ---- Ensure cached GPU resources (mutable phase). ----
        let has_casters = !casters.is_empty();
        {
            let gpu = ctx.gpu_encoder();
            if self.depth_stencil.is_none() {
                self.depth_stencil = Some(gpu.device.create_depth_stencil_state(
                    &manifold_gpu::GpuDepthStencilDesc {
                        compare: manifold_gpu::GpuCompareFunction::Less,
                        write_enabled: true,
                    },
                ));
            }
            self.ensure_msaa_targets(gpu.device, width, height);
            self.ensure_sampler(gpu.device);
            self.ensure_dummy_texture(gpu.device);
            // Identity instance stub (D11) — bound to any object's
            // instances_n when unwired, both in the main pass and every
            // caster's shadow pass below.
            self.ensure_identity_instance_stub(gpu.device);
            // Shadow ABI stubs (comparison sampler + 1×1 dummy depth) are
            // always needed — the main shader declares @binding(10..14) even
            // in a scene with no casters. The shadow *pipeline* + per-caster
            // maps are created only when a caster exists (unwired = zero cost).
            self.ensure_shadow_binding_stubs(gpu.device);
            if has_casters {
                self.ensure_shadow_pass(gpu.device);
                for (slot, l) in casters.iter().enumerate() {
                    self.ensure_shadow_map(gpu.device, slot, l.shadow_resolution);
                }
            }
            // Rotate + (re)size the light ring buffer, then write this
            // frame's light data into the current ring slot. Rotating across
            // FRAMES_IN_FLIGHT buffers guarantees the CPU never overwrites a
            // buffer an in-flight frame is still reading (kills the 4KB
            // setBytes cap that bounded the old Bytes binding to 127 lights).
            let needed = (light_data.len() * std::mem::size_of::<[f32; 4]>()) as u64;
            if self.light_buffers.len() < FRAMES_IN_FLIGHT || self.light_capacity < needed {
                let cap = needed.max(self.light_capacity).max(64).next_power_of_two();
                self.light_buffers = (0..FRAMES_IN_FLIGHT)
                    .map(|_| gpu.device.create_buffer_shared(cap))
                    .collect();
                self.light_capacity = cap;
            }
            self.light_frame = (self.light_frame + 1) % FRAMES_IN_FLIGHT;
            unsafe {
                self.light_buffers[self.light_frame]
                    .write(0, bytemuck::cast_slice(&light_data));
            }
        }

        // ---- Shadow depth pre-passes. One depth-only pass per caster
        // (cleared once), every object drawn through that light's
        // view-projection into its private Depth32Float map. Runs before the
        // main lit pass so the maps are ready to sample; skipped entirely
        // when no light casts (has_casters == false → zero passes). ----
        let vsize = std::mem::size_of::<MeshVertex>() as u64;
        let vcount = |buf: &manifold_gpu::GpuBuffer| ((buf.size / vsize) as u32 / 3) * 3;
        // D11: the shadow pass instances too — bound once here, reused by
        // Pass 2 below (both only ever take an immutable borrow of self).
        let identity_stub = self.identity_instance_stub.as_ref().expect("ensured");
        if has_casters {
            let shadow_pipeline = self.shadow_pipeline.as_ref().expect("ensured").clone();
            let shadow_ds = self.shadow_depth_stencil.as_ref().expect("ensured");
            for (slot, l) in casters.iter().enumerate() {
                let Some((_, shadow_map)) = self.shadow_maps[slot].as_ref() else {
                    continue;
                };
                let vp = l.shadow_view_proj();
                let shadow_uniforms: Vec<ShadowUniforms> = draws
                    .iter()
                    .map(|d| ShadowUniforms {
                        light_view_proj: vp,
                        model: d.uniforms.model,
                    })
                    .collect();
                let shadow_bindings: Vec<[GpuBinding; 3]> = draws
                    .iter()
                    .zip(&shadow_uniforms)
                    .map(|(d, su)| {
                        [
                            GpuBinding::Bytes {
                                binding: 0,
                                data: bytemuck::bytes_of(su),
                            },
                            GpuBinding::Buffer {
                                binding: 1,
                                buffer: d.vertices,
                                offset: 0,
                            },
                            GpuBinding::Buffer {
                                binding: 2,
                                buffer: d.instances.unwrap_or(identity_stub),
                                offset: 0,
                            },
                        ]
                    })
                    .collect();
                let shadow_draws: Vec<manifold_gpu::DepthMsaaDraw> = draws
                    .iter()
                    .zip(&shadow_bindings)
                    .map(|(d, b)| {
                        manifold_gpu::GpuEncoder::depth_msaa_draw(
                            &shadow_pipeline,
                            b,
                            vcount(d.vertices),
                            d.instance_count,
                        )
                    })
                    .collect();
                ctx.gpu_encoder()
                    .native_enc
                    .draw_instanced_depth_only_batch(
                        shadow_map,
                        shadow_ds,
                        &shadow_draws,
                        "node.render_scene shadow",
                    );
            }
        }

        // ---- Pass 2 (immutable phase): draw. Every object composites into
        // ONE 4x-MSAA color+depth pass (cleared once); the shared depth
        // buffer resolves inter-object occlusion, and the pass resolves out
        // to the single-sample `target` at the end.
        let Some(target) = ctx.outputs.texture_2d("color") else {
            return;
        };
        let depth_stencil = self.depth_stencil.as_ref().expect("just inserted");
        let depth_tex = self.depth_texture.as_ref().expect("just inserted");
        let msaa_color = self.msaa_color.as_ref().expect("just inserted");
        let sampler = self.sampler.as_ref().expect("just inserted");
        let dummy = self.dummy_texture.as_ref().expect("just inserted");
        let shadow_sampler = self.shadow_sampler.as_ref().expect("stubs ensured");
        let dummy_depth = self.dummy_depth.as_ref().expect("stubs ensured");
        let envmap_texture = envmap_wired.unwrap_or(dummy);
        // Shadow map per slot → the real map if that slot has a caster, else
        // the 1×1 dummy depth. The shader never samples a −1 (non-caster)
        // slot, but every declared @binding(10..13) must be a valid depth
        // texture. Hand-unrolled for K=4 (WGSL has no dynamic texture-binding
        // indexing); the assert trips if K changes and this list doesn't.
        const _: () = assert!(
            MAX_SHADOW_CASTING_LIGHTS == 4,
            "shadow-map bindings @10..13 + shader switch are hand-unrolled for K=4"
        );
        let shadow_tex = |slot: usize| -> &manifold_gpu::GpuTexture {
            self.shadow_maps[slot]
                .as_ref()
                .map(|(_, t)| t)
                .unwrap_or(dummy_depth)
        };
        let shadow_0 = shadow_tex(0);
        let shadow_1 = shadow_tex(1);
        let shadow_2 = shadow_tex(2);
        let shadow_3 = shadow_tex(3);

        let vertex_size = std::mem::size_of::<MeshVertex>() as u64;
        let vertex_count = |draw: &ObjectDraw| ((draw.vertices.size / vertex_size) as u32 / 3) * 3;

        if !draws.iter().any(|d| vertex_count(d) > 0) {
            // Every object had zero drawable vertices — clear so stale
            // pool contents don't leak through (matches render_mesh's
            // vertex_count == 0 fallback).
            ctx.gpu_encoder().native_enc.clear_texture(target, 0.0, 0.0, 0.0, 0.0);
            return;
        }

        // Binding arrays must outlive the batch call, so build them all
        // first, then reference each from a `DepthMsaaDraw`. The light buffer
        // (this frame's ring slot) and caster table are scene-wide — every
        // object's set borrows the same ones.
        let light_buffer = &self.light_buffers[self.light_frame];
        let caster_bytes: &[u8] = bytemuck::cast_slice(&caster_table);
        let binding_sets: Vec<[GpuBinding; 16]> = draws
            .iter()
            .map(|draw| {
                [
                    GpuBinding::Bytes {
                        binding: 0,
                        data: bytemuck::bytes_of(&draw.uniforms),
                    },
                    GpuBinding::Buffer {
                        binding: 1,
                        buffer: draw.vertices,
                        offset: 0,
                    },
                    GpuBinding::Texture {
                        binding: 2,
                        texture: envmap_texture,
                    },
                    GpuBinding::Sampler {
                        binding: 3,
                        sampler,
                    },
                    GpuBinding::Texture {
                        binding: 4,
                        texture: dummy,
                    },
                    GpuBinding::Texture {
                        binding: 5,
                        texture: dummy,
                    },
                    GpuBinding::Texture {
                        binding: 6,
                        texture: draw.base_color_map.unwrap_or(dummy),
                    },
                    GpuBinding::Texture {
                        binding: 7,
                        texture: dummy,
                    },
                    // Lights: ring-buffered storage buffer (was a 4KB-capped
                    // Bytes bind). Holds one zeroed entry when no light is
                    // wired; the shader gates reads on `light_count` (D4).
                    GpuBinding::Buffer {
                        binding: 8,
                        buffer: light_buffer,
                        offset: 0,
                    },
                    // Caster table (fixed K×5 vec4, zeroed for empty slots) —
                    // always bound, same D4 discipline as the light buffer.
                    GpuBinding::Bytes {
                        binding: 9,
                        data: caster_bytes,
                    },
                    GpuBinding::Texture {
                        binding: 10,
                        texture: shadow_0,
                    },
                    GpuBinding::Texture {
                        binding: 11,
                        texture: shadow_1,
                    },
                    GpuBinding::Texture {
                        binding: 12,
                        texture: shadow_2,
                    },
                    GpuBinding::Texture {
                        binding: 13,
                        texture: shadow_3,
                    },
                    GpuBinding::Sampler {
                        binding: 14,
                        sampler: shadow_sampler,
                    },
                    // D11: per-object instances_n, or the identity stub when
                    // that object leaves it unwired.
                    GpuBinding::Buffer {
                        binding: 15,
                        buffer: draw.instances.unwrap_or(identity_stub),
                        offset: 0,
                    },
                ]
            })
            .collect();
        let draw_calls: Vec<manifold_gpu::DepthMsaaDraw> = draws
            .iter()
            .zip(&binding_sets)
            .map(|(draw, bindings)| {
                manifold_gpu::GpuEncoder::depth_msaa_draw(
                    &draw.pipeline,
                    bindings,
                    vertex_count(draw),
                    draw.instance_count,
                )
            })
            .collect();

        ctx.gpu_encoder().native_enc.draw_instanced_depth_msaa_batch(
            msaa_color,
            target,
            depth_tex,
            depth_stencil,
            &draw_calls,
            "node.render_scene",
        );
    }
}

inventory::submit! {
    crate::node_graph::persistence::PrimitiveFactory {
        type_id: RENDER_SCENE_TYPE_ID,
        create: || Box::new(RenderScene::new()),
        picker: Some(crate::node_graph::palette::PickerInfo {
            label: "Render Scene",
            category: crate::node_graph::palette::PaletteCategory::Atom,
        }),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn params_with(objects: f32, lights: f32) -> ParamValues {
        let mut p = ParamValues::default();
        p.insert(std::borrow::Cow::Borrowed("objects"), ParamValue::Float(objects));
        p.insert(std::borrow::Cow::Borrowed("lights"), ParamValue::Float(lights));
        p
    }

    #[test]
    fn defaults_to_two_objects_one_light() {
        let s = RenderScene::new();
        // camera + envmap + atmosphere + light_0 +
        // (mesh_0,material_0,base_color_map_0,transform_0,instances_0) +
        // (mesh_1,material_1,base_color_map_1,transform_1,instances_1)
        assert_eq!(s.inputs().len(), 3 + 1 + 10);
        assert!(s.inputs().iter().any(|p| p.name == "atmosphere"));
        assert!(!s.inputs().iter().find(|p| p.name == "atmosphere").unwrap().required);
        assert_eq!(
            s.inputs().iter().find(|p| p.name == "atmosphere").unwrap().ty,
            PortType::Atmosphere
        );
        assert!(s.inputs().iter().any(|p| p.name == "mesh_1"));
        assert!(s.inputs().iter().any(|p| p.name == "material_1"));
        assert!(!s.inputs().iter().any(|p| p.name == "mesh_2"));
        assert!(s.inputs().iter().any(|p| p.name == "light_0"));
        assert!(!s.inputs().iter().any(|p| p.name == "light_1"));
        let by_name = |n: &str| s.inputs().iter().find(|p| p.name == n).unwrap();
        assert!(!by_name("base_color_map_0").required);
        assert!(!by_name("base_color_map_1").required);
        assert!(!by_name("transform_0").required);
        assert!(!by_name("transform_1").required);
        assert_eq!(by_name("transform_0").ty, PortType::Transform);
        assert!(!by_name("instances_0").required);
        assert!(!by_name("instances_1").required);
        assert_eq!(
            by_name("instances_0").ty,
            PortType::Array(ArrayType::of_known::<InstanceTransform>())
        );
        assert!(!s.inputs().iter().any(|p| p.name == "base_color_map_2"));
        assert!(!s.inputs().iter().any(|p| p.name == "transform_2"));
        assert!(!s.inputs().iter().any(|p| p.name == "instances_2"));
        // Only `objects` + `lights` remain as params — per-object TRS moved
        // to the `transform_n` port (SCENE_BUILD_AND_GROUP_PARAMS_DESIGN.md
        // §2 D3); instances_n carries no per-object instance_count param
        // either (REALTIME_3D_DESIGN.md §10 D11).
        assert_eq!(s.parameters().len(), 2);
        assert!(!s.parameters().iter().any(|p| p.name.contains("pos_x")));
    }

    #[test]
    fn reconfigure_grows_and_shrinks_ports_and_params() {
        let mut s = RenderScene::new();
        let node: &mut dyn EffectNode = &mut s;
        node.reconfigure(&params_with(5.0, 3.0));
        assert!(node.inputs().iter().any(|p| p.name == "mesh_4"));
        assert!(node.inputs().iter().any(|p| p.name == "material_4"));
        assert!(node.inputs().iter().any(|p| p.name == "base_color_map_4"));
        assert!(node.inputs().iter().any(|p| p.name == "transform_4"));
        assert!(node.inputs().iter().any(|p| p.name == "instances_4"));
        assert!(!node.inputs().iter().any(|p| p.name == "mesh_5"));
        assert!(!node.inputs().iter().any(|p| p.name == "transform_5"));
        assert!(!node.inputs().iter().any(|p| p.name == "instances_5"));
        assert!(node.inputs().iter().any(|p| p.name == "light_2"));
        assert!(!node.inputs().iter().any(|p| p.name == "light_3"));
        assert_eq!(node.parameters().len(), 2, "object count never grows the param list anymore");

        node.reconfigure(&params_with(1.0, 0.0));
        assert!(!node.inputs().iter().any(|p| p.name == "mesh_1"));
        assert!(!node.inputs().iter().any(|p| p.name == "base_color_map_1"));
        assert!(!node.inputs().iter().any(|p| p.name == "transform_1"));
        assert!(!node.inputs().iter().any(|p| p.name == "instances_1"));
        assert!(!node.inputs().iter().any(|p| p.name == "light_0"));
        assert!(node.inputs().iter().any(|p| p.name == "mesh_0"));
        assert!(node.inputs().iter().any(|p| p.name == "transform_0"));
        assert!(node.inputs().iter().any(|p| p.name == "instances_0"));
    }

    #[test]
    fn reconfigure_clamps_objects_and_lights_to_their_slider_max() {
        let mut s = RenderScene::new();
        let node: &mut dyn EffectNode = &mut s;
        node.reconfigure(&params_with(9999.0, 999.0));
        // Objects clamp to OBJECT_SLIDER_MAX (soft UI bound, not structural).
        let last_obj = OBJECT_SLIDER_MAX - 1;
        assert!(node.inputs().iter().any(|p| p.name == format!("mesh_{last_obj}")));
        assert!(!node
            .inputs()
            .iter()
            .any(|p| p.name == format!("mesh_{OBJECT_SLIDER_MAX}")));
        assert!(node
            .inputs()
            .iter()
            .any(|p| p.name == format!("base_color_map_{last_obj}")));
        assert!(node
            .inputs()
            .iter()
            .any(|p| p.name == format!("transform_{last_obj}")));
        assert!(node
            .inputs()
            .iter()
            .any(|p| p.name == format!("instances_{last_obj}")));
        // Lights clamp to LIGHT_SLIDER_MAX — a soft UI bound now, NOT a
        // structural cap (lights ride a runtime-sized storage buffer).
        let last_light = LIGHT_SLIDER_MAX - 1;
        assert!(node.inputs().iter().any(|p| p.name == format!("light_{last_light}")));
        assert!(!node
            .inputs()
            .iter()
            .any(|p| p.name == format!("light_{LIGHT_SLIDER_MAX}")));
    }

    #[test]
    fn lights_generalize_well_past_the_old_cap_of_4() {
        // The whole point of the 2026-07-10 unbounded-lights change: light
        // count is no longer capped at 4. Prove 8 lights (twice the old
        // cap) wire cleanly.
        let mut s = RenderScene::new();
        let node: &mut dyn EffectNode = &mut s;
        node.reconfigure(&params_with(1.0, 8.0));
        assert!(node.inputs().iter().any(|p| p.name == "light_7"));
        assert!(!node.inputs().iter().any(|p| p.name == "light_8"));
    }

    #[test]
    fn objects_generalize_well_past_the_old_cap_of_8() {
        // The whole point of the 2026-07-05 generalization: object count
        // is no longer capped at 8. Prove 32 objects wire cleanly.
        let mut s = RenderScene::new();
        let node: &mut dyn EffectNode = &mut s;
        node.reconfigure(&params_with(32.0, 2.0));
        assert!(node.inputs().iter().any(|p| p.name == "mesh_31"));
        assert!(node.inputs().iter().any(|p| p.name == "material_31"));
        assert!(node.inputs().iter().any(|p| p.name == "transform_31"));
        // objects/lights only — object count never grows the param list.
        assert_eq!(node.parameters().len(), 2);
    }

    #[test]
    fn camera_and_mesh_material_ports_are_required_envmap_and_lights_are_not() {
        let s = RenderScene::new();
        let by_name = |n: &str| s.inputs().iter().find(|p| p.name == n).unwrap();
        assert!(by_name("camera").required);
        assert!(!by_name("envmap").required);
        assert!(!by_name("light_0").required);
        assert!(by_name("mesh_0").required);
        assert!(by_name("material_0").required);
        assert!(!by_name("base_color_map_0").required);
        assert!(!by_name("transform_0").required);
        assert!(!by_name("instances_0").required);
    }

    #[test]
    fn registers_with_palette_type_id() {
        let s = RenderScene::new();
        let node: &dyn EffectNode = &s;
        assert_eq!(node.type_id().as_str(), "node.render_scene");
    }

    #[test]
    fn model_matrix_identity_at_origin_no_rotation_unit_scale() {
        let m = model_matrix([0.0, 0.0, 0.0], [0.0, 0.0, 0.0], [1.0, 1.0, 1.0]);
        let expected = [
            [1.0, 0.0, 0.0, 0.0],
            [0.0, 1.0, 0.0, 0.0],
            [0.0, 0.0, 1.0, 0.0],
            [0.0, 0.0, 0.0, 1.0],
        ];
        for c in 0..4 {
            for r in 0..4 {
                assert!(
                    (m[c][r] - expected[c][r]).abs() < 1e-6,
                    "col {c} row {r}: got {} expected {}",
                    m[c][r],
                    expected[c][r]
                );
            }
        }
    }

    #[test]
    fn model_matrix_translates_a_point() {
        let m = model_matrix([2.0, 3.0, 4.0], [0.0, 0.0, 0.0], [1.0, 1.0, 1.0]);
        // Column 3 (translation) should carry the position.
        assert_eq!(m[3], [2.0, 3.0, 4.0, 1.0]);
    }

    #[test]
    fn model_matrix_scales_columns_independently() {
        let m = model_matrix([0.0, 0.0, 0.0], [0.0, 0.0, 0.0], [2.0, 3.0, 4.0]);
        assert!((m[0][0] - 2.0).abs() < 1e-6);
        assert!((m[1][1] - 3.0).abs() < 1e-6);
        assert!((m[2][2] - 4.0).abs() < 1e-6);
    }
}
